### ISSUE TITLE
better caching of protocolbuffers in ci

### ISSUE THREAD

**Issue by toffaletti** [apple/swift-protobuf#1003]
For some background see https://github.com/actions/cache/issues/310 the TL;DR is that for security reasons the actions cache is not shared between master and PR builds. One possible solution to this would be moving the caching down a layer into the docker image we're using.

1. create a pipeline that triggers on updates to protocolbuffers/protobuf master and builds a new docker image. tag image with commit hash (or a tag?).
2. use docker image for our builds.

I am not sure if it is possible to create actions that trigger on changes to other repos, but I think I saw that it is possible. I'm not sure how to specify the dependency between swift-protobuf CI workflow and the docker build workflow, without that there could be a race condition where a change to protobuf master and a PR submitted to swift-protobuf within a short window could try to pull a docker image that is not yet built.

**Comment by thomasvl** [comment]
Is there a way to have a github action trigger on a cron?  i.e. - say daily/once a week just do a build to validate against protobuf master changes.  It would then have the side effect of sorta updating the cache incase a PR comes in without that master having changed?

Also, when I made the comment about things not appearing to cache before, it was when we were pinned, so it really seemed like things should have been cached there, but given master floats, the caching really is just an optimization, and I wouldn't want to waste too many cycles just updating things incase something new comes in.

**Comment by thomasvl** [comment]
To answer my own question, yes, you can cron trigger.  I set that up for checking up changes to the proto files we have to mirror from protocolbuffers/protobuf.

@toffaletti Is there a way to check how well caching is working and do we cache a built protobuf or do we cache just the checkout?  From the flow, I'm not completely clear what the current setup does?  I'm asking in part because we seem to only use the `platform` in the cache key, but since we're using different Swift docker images, I wasn't sure if they have different things in them (like the missing zlib.h in the 5.0.x image), so would we be better off using the swift version in the key rather than just platform so each CI job in the matrix is its own cache?

**Comment by toffaletti** [comment]
I am not sure if there are any metrics exposed for the cache, I haven’t seen anything like that. I had to check the logs of each build to understand whether the cache was working or not. The current setup does cache the protobuf build (and source I think, just because it was easier to do the whole thing).

**Comment by toffaletti** [comment]
For missing zlib, we should be able to add the zlib package to the list of install deps. It will be a no-op on the images that already have it.

**Comment by thomasvl** [comment]
#1097 reduces what we build (slightly) and adds `-j CPU_COUNT` to the builds to hopefully speed things up a little bit also.

**Comment by thomasvl** [comment]
Actually, that PR used cached protobuf, so maybe they do allow PRs to use a cache from someplace else?  it was a new branch for me, but maybe results from my other PRs that had the same cache key got used?

**Comment by toffaletti** [comment]
The run I checked did not look like it used a cache, but I’m squinting at this on mobile right now and maybe wrong.

**Comment by thomasvl** [comment]
> The run I checked did not look like it used a cache, but I’m squinting at this on mobile right now and maybe wrong.

Look at the checks on the first commit on that PR; it didn't build protobuf.  The second did because that commit switched to the v2 cache module, so it couldn't reuse the v1 cache.

**Comment by thomasvl** [comment]
I'm going to close this out, we have some caching, but since we're also tracking protobuf head most of the time for new conformance tests/etc. on CI, I'm not really sure we'd get much better caching. As odds are there will always be some new things.  If we have issue with CI times in the future we can always revisit/open a new issue.
