### ISSUE TITLE
Should we generate field number constants?

### ISSUE THREAD

**Issue by thomasvl** [apple/swift-protobuf#104]
Most consumers don't need them, but if a developer wants to manually parse a binary protobuf stream, they can be useful.  The generator actually could use those constants also in the code it has for getting the `.proto` file comments, and has instead manually hardcoded field numbers.

Hopefully if the values aren't used they'd dead strip, but it doesn't mean bloat for anyone build frameworks.

**Comment by tbkka** [comment]
Perhaps the field number constants should be an enum?

I've also been considering moving the type metadata (package name constant, etc) into a subtype.  Maybe something like:
```
struct Foo: ProtobufMessage {
   struct Metadata: ProtobufMessageMetadata {
      static let protoPackageName = "bar.baz";
      static let jsonFieldNames: [String: ProtoFieldNumbers] = [ ... ];
      enum ProtoFieldNumbers: Int {
      case field1 = 1
      case field2 = 2
      }
   }
}
```

In particular, that would reduce conflict opportunities with these extra names.

**Comment by allevato** [comment]
Enums would require users to use `rawValue` whenever they wanted them; since we'd be defining them for the sole purpose of giving them access to the numeric value itself, it would probably be better to just use `static let field1 = 1` instead.

We could still use a case-less `enum` to make the type non-instantiable, but that's an implementation detail.

**Comment by thomasvl** [comment]
The metadata as a struct is also nice because it moves a bunch of stuff out of the same namespace the message fields are in.

**Comment by thomasvl** [comment]
Opened https://github.com/apple/swift-protobuf/issues/109 to capture the metadata question.

**Comment by thomasvl** [comment]
They could be useful in the generator source where we have some hard coded field numbers when fetching comments.

And they could be useful when we do something for #130 as they would allow a developer to know have to hard code field numbers when using that sorta interface.

But for now, I vote we punt and close this as not happing for 1.0.  We can always revisit it in the future, but for now, less API seems better.

**Comment by tbkka** [comment]
It can be added later without breaking anything.  I don't think we would ever use it in the library, so it wouldn't be a constraint between library and generated code.

Post 1.0.

**Comment by thomasvl** [comment]
Closing out since we're dropping this until we decide it is needed.

**Comment by jasonphi** [comment]
Sorry to revive a 9 year old issue. I just want to call out that field numbers are useful for more than just handling binary proto data.

Field masks can be constructed using field names _or_ [field numbers](https://github.com/apple/swift-protobuf/blob/1.32.0/Sources/SwiftProtobuf/Google_Protobuf_FieldMask+Extensions.swift#L203). Providing official constants for field numbers would make field masks much less finicky in Swift.

**Comment by allevato** [comment]
One thing that we could consider would be to generate the field number constants as computed variables that are `@_alwaysEmitIntoClient`. Then, there should be no code-size cost within the module containing the protos to produce these, and your clients would only pay for the field numbers that they actually use.

This seems like something we should revisit as part of the table-driven effort, since the constants would also be useful for simple reflection.
