### ISSUE TITLE
Option for access control?

### ISSUE THREAD

**Issue by soffes** [apple/swift-protobuf#107]
Currently the generated Swift structs are marked with `public`. I would really love an option to remove this.

I'm using protobufs in a framework that handles the networking to a web service. I only use the protobufs as transport and convert these to other types of models that are publicly accessible from my framework. It would be better if the protobuf structs could be internal to the framework since I don't want to expose that to the consumer of my framework.

**Comment by allevato** [comment]
Yes, this is definitely something we should support.

It should be a command-line option so that it's controlled by the generator invocation, not by options in the proto files themselves. Something to the effect of `--swift_out=Visibility=[public|internal]:...` would work; `public` and `internal` are the only two options that make sense.

I would even go so far as to say `internal` should be the default, not `public` as we have today. When you consider these three use cases:

1. A user generates protos to include in an app so internal visibility suffices (and opens the door for optimizations)
2. A user generates protos to include in as an internal component of a framework (your use case)
3. A user generates protos and wants to expose them in the public API of a framework

1 and 2 probably occupy much more of the problem space than 3 does.

**Comment by soffes** [comment]
Totally agree. I'd prefer `internal` by default as well.

**Comment by thomasvl** [comment]
So the standard catch with changing what is generated is say the protos are all internal to your framework, so you want them internal.  But if someone other framework uses the same protos, the final application that uses both frameworks could end up having two copies of the protos internal to each framework instead of being able to share them (and reduce binary size).

(But atleast this isn't like ObjC where you'd end up with errors from duplicate classes at runtime)

**Comment by soffes** [comment]
@thomasvl right, but if you wanted that, you could just make them public. Better yet, I'd say make a framework with just the protos and share it to both (if it were me).

**Comment by thomasvl** [comment]
Sorry, the catch you writing your framework (and generating your protos) don't know which of your consumers will need them public and which won't.  So just like you mentioned here, it makes perfect sense for you to make the internal based on your frameworks needs.  It could become a problem for someone downstream of you.

**Comment by soffes** [comment]
I've heard (unfortunately I don't have a good source for this) the recommended use of protobufs as transport and derive models from them. That's what I've been doing and it's working really well. I'm not sure if this is common.

In my case, I do have models that are public from my framework that other targets consume. None of them are aware of the protos (other than the runtime framework being required) since they just interact with my models. Some on my models are backed by a persistence framework (Realm or Core Data) and some are just plain structs.

Anyway, more to the point of the original discussion, I'd love an option. If you feel strongly about the default, I'm super passionate about either. Public may be easier for those not particular about which it is. If there's a way to change to internal, I'm happy.

Totally hear your points for making public the default.

**Comment by allevato** [comment]
IMO, having the default be `internal` best fits the Swift language philosophies of (1) `internal` being the default access level if none is provided, and (2) exposing a public API surface should be a conscious explicit decision due to the promises and maintenance responsibilities that come with that decision.

**Comment by thomasvl** [comment]
Sorry, I'm not opposed to the option. History has just taught me any options that change the generator code lead to unexpected problems/complications; most of which has to do with dependency chains.  So I just wanted folks to be sure they thought about the potential issues as we go look at providing this.

**Comment by soffes** [comment]
@thomasvl we all appreciate you defending the simplicity of the generator! :heart: Whatever you decide is fine with me.

I fully agree with @allevato that it is more with the Swift philosophies since not specifying an access control modifier in code is implicitly internal. I think the generator should do the same. If you don't specify one, it doesn't specify one in code. If you do, that one is used. (Totally agree that you shouldn't be able to specify private since that isn't useful.)

**Comment by calebd** [comment]
I completely agree with @allevato. Generated types meant for consumption should be `internal` by default with an option to specify `public`.

**Comment by tbkka** [comment]
The current default of 'public' is just an artifact of having the first client be the SwiftProtobuf framework itself (which requires 'public').  Having an option to control this is a good idea (though I do wish protoc had a better command-line syntax for generator options; overloading the directory name is rather cumbersome).

**Comment by thomasvl** [comment]
@tbkka yea, there is a slightly better syntax if the generator is built into protoc; but yea, I'm not a fan of what they provide either.

**Comment by thomasvl** [comment]
I'll look at doing this this week.

**Comment by soffes** [comment]
@thomasvl ❤️ thank you!

**Comment by thomasvl** [comment]
FYI - Started sent an email to some of the protobuf team about adding better support for generator parameters for plugins.

**Comment by soffes** [comment]
@thomasvl thank you! :heart:
