### ISSUE TITLE
Proto3 Optional fields should be Swift optionals

### ISSUE THREAD

**Issue by wilg** [apple/swift-protobuf#1114]
I see that there is support for Proto3 optionals (https://github.com/apple/swift-protobuf/issues/1096) however as far as I can tell the generated code does not actually expose these as Swift optionals:

```swift
    public var email: String {
      get {return _email ?? String()}
      set {_email = newValue}
    }
    /// Returns true if `email` has been explicitly set.
    public var hasEmail: Bool {return self._email != nil}
    /// Clears the value of `email`. Subsequent reads from it will return its default value.
    public mutating func clearEmail() {self._email = nil}
```

This seems to defeat a lot of the ergonomics that would be possible if these came through directly as Swift optionals. If there's some backwards compatibility issues, I'm happy to enable some flag for it.

**Comment by wilg** [comment]
I should add that this was prompted by Proto3 optionals recently being promoted from Experimental: v

**Comment by tbkka** [comment]
See https://github.com/apple/swift-protobuf/blob/main/Documentation/INTERNALS.md for some explanation of this.

The same issues apply to proto3 optionals as proto2 optionals.  In short, Swift's `Optional<>` type is fundamentally a different concept from proto optionals.  It's a somewhat subtle distinction (not least because of the identical names) and one that we argued for a long time before we decided on the current approach.

**Comment by wilg** [comment]
Sorry, I'm not understanding the issue with this, even after reading that and https://github.com/protocolbuffers/protobuf/blob/master/docs/field_presence.md and https://github.com/protocolbuffers/protobuf/blob/master/docs/implementing_proto3_presence.md

I am specifically talking about proto3 only, so it's a bit hard to understand if the situation is exactly the same since the internals doc references proto2.

Can you give an example of a situation where the mapping to a Swift optional would not behave as expected?

This is a _huge_ ergonomics trade-off and clearly this is an oft-requested feature, so I would love to help figure out if there is some way to make working with optional fields better to use.

**Comment by tbkka** [comment]
The second link you mention has this statement:
> ... make sure that proto3 optional fields have exactly the same API and behave in exactly the same way as proto2 optional fields.

The key difference between proto optional (proto2 and proto3) and Swift `Optional` is that a missing proto field still has a value (the default value), whereas a Swift `nil` `Optional` does not have any value at all.  (You can see this in the generated code example you quoted.). This is more obvious in proto2 where the default value can be overridden by the schema, but it's still true in proto3.

We probably should update the internals doc to refer to proto3 as well.  Thanks for pointing that out.

**Comment by wilg** [comment]
I guess where I'm confused is why the value that a "missing" proto field "has" is anything but an implementation detail? Does that have any semantic meaning or difference in behavior? Why not just ignore it?

**Comment by wilg** [comment]
And also, since the internal storage (as shown in the code above) _is actually using Swift optionals_ I don't understand the purpose of having 3 properties when it can be expressed with one optional one.

(The only difference is the `?? String()` default value in the case where `has` is `false`, which is undesirable for my use case I think.)

**Comment by wilg** [comment]
For reference, here is a complete diff of the proto3 codegen output when changing `email` to be `optional`:

```diff
-  string email = 3;
+  optional string email = 3;
```

⬇️ 

```diff
@@ -105,7 +105,14 @@ public struct UserEditableProfile {
 
   public var name: String = String()
 
-  public var email: String = String()
+  public var email: String {
+    get {return _email ?? String()}
+    set {_email = newValue}
+  }
+  /// Returns true if `email` has been explicitly set.
+  public var hasEmail: Bool {return self._email != nil}
+  /// Clears the value of `email`. Subsequent reads from it will return its default value.
+  public mutating func clearEmail() {self._email = nil}
 
   public var avatar: Image {
     get {return _avatar ?? Image()}
@@ -165,6 +172,7 @@ public struct UserEditableProfile {
 
   public init() {}
 
+  fileprivate var _email: String? = nil
   fileprivate var _avatar: Image? = nil
 }
 
@@ -4283,7 +4291,7 @@ extension UserEditableProfile: SwiftProtobuf.Message, SwiftProtobuf._MessageImpl
       switch fieldNumber {
       case 1: try { try decoder.decodeSingularInt64Field(value: &self.id) }()
       case 2: try { try decoder.decodeSingularStringField(value: &self.name) }()
-      case 3: try { try decoder.decodeSingularStringField(value: &self.email) }()
+      case 3: try { try decoder.decodeSingularStringField(value: &self._email) }()
       case 4: try { try decoder.decodeSingularMessageField(value: &self._avatar) }()
       case 5: try { try decoder.decodeSingularStringField(value: &self.bio) }()
       case 6: try { try decoder.decodeSingularBoolField(value: &self.privateBio) }()
@@ -4300,8 +4308,8 @@ extension UserEditableProfile: SwiftProtobuf.Message, SwiftProtobuf._MessageImpl
     if !self.name.isEmpty {
       try visitor.visitSingularStringField(value: self.name, fieldNumber: 2)
     }
-    if !self.email.isEmpty {
-      try visitor.visitSingularStringField(value: self.email, fieldNumber: 3)
+    if let v = self._email {
+      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
     }
     if let v = self._avatar {
       try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
@@ -4321,7 +4329,7 @@ extension UserEditableProfile: SwiftProtobuf.Message, SwiftProtobuf._MessageImpl
   public static func ==(lhs: UserEditableProfile, rhs: UserEditableProfile) -> Bool {
     if lhs.id != rhs.id {return false}
     if lhs.name != rhs.name {return false}
-    if lhs.email != rhs.email {return false}
+    if lhs._email != rhs._email {return false}
     if lhs._avatar != rhs._avatar {return false}
     if lhs.bio != rhs.bio {return false}
     if lhs.privateBio != rhs.privateBio {return false}
```

**Comment by wilg** [comment]
Thinking about it more:

> This is more obvious in proto2 where the default value can be overridden by the schema, but it's still true in proto3.

This could be the important distinction – since proto3 has no way to change the default value, and it's purely type-based, it is more compatible with Swift's optionals than proto2 – you'll never really need to fetch the default value from a field. Or if you want to, simply do not mark it `optional`.

**Comment by wilg** [comment]
Sorry for all the comments, kinda thinking out loud, but I want to re emphasize that I'm not asking to change the standard behavior necessarily, an optional compile mode would be fantastic, and I think useful for many use cases where you just don't really care about getting the default value for optional fields.

**Comment by thomasvl** [comment]
One other thing to keep in mind is a proto syntax 2 message and be a field of a proto syntax 3 message (and the reverse), so that's where consistent api also comes into play.

> …an optional compile mode would be fantastic…

https://github.com/apple/swift-protobuf/blob/main/Documentation/FAQ.md#can-you-add-an-option-for

**Comment by wilg** [comment]
Sigh... I guess we're hitting a wall here. It seems like a lot of these design decisions are only for backwards compatibility – I don't have any proto2 code, and it's likely that going forward other people are going to start with proto3 like I did.

It seems totally reasonable to me to have an option to not be constrained by proto2 backwards compatibility and in exchange get a _much, much_ nicer API. Optionals are very useful for protocol definitions and for having the code work like idiomatic Swift.

Are we absolutely certain that the "no options" guideline should be applied here? Are we certain that these design decisions have considered a fully proto3 workflow? Or is the only option to fork this project?

**Comment by thomasvl** [comment]
Is there a reason you decided to go with proto3 syntax?  Despite the names, _3_ doesn't replace _2_, they are just different with different behaviors, pick the one that has the behaviors/features you need.

Long term, I believe the protobuf folks want to merge the two syntaxes/remove the differences.  As those docs mention, when proto3 syntax was designed [wrappers.proto](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/wrappers.proto) with its custom JSON encoding was thought to cover this case.  Some languages (C#?) even custom code generated those fields into something to use their "null" concept.  But the downside in the other encodings eventually lead to adding _optional_ to proto3 syntax.  If you go back to old specs, you'll also find that using proto3 syntax used to mean for binary format you lost all unknown fields (explicitly said to drop them), but that also proved to be a problem with time; so the design was revised.

There is always the potential to revisit things when this library is ready to take on API breaks, but proto3 syntax optional was added to the existing system with mentioned api decisions/guidelines.  I understand your comments, other languages also have the concepts of "null", but have modeled it in similar ways for similar reasons (C++, ...).

There's also some interesting meta questions if one starts down the Swift `Optional` path. Message fields; currently you get a default one, Swift's optional chaining could be used to allow fetching things, but default values can get a little messy.  Getting a default also means you can do `foo.bar.baz = 1` and that implicitly sets `bar` on `foo` after setting its`baz` to `1`. If message fields were `Optional` that code wouldn't work as is, and you'd need to either double the api surface (and anything `public` in Swift doesn't dead strip yet) to have an accessor that gets or creates it or every caller needing that pattern would have to manually check then maybe set the intermediate message field.  There are also similar questions for the repeated and map fields; but with them, the binary format (and TextFormat) can't capture the existence of an empty array/map, so do you allow the memory object to have a state that doesn't exist in some of the formats?

In isolation, with limited use cases one is interested in, it can be easier to argue one way vs another, but in a system where one needs to support both of the syntaxes, with folks having to use message they didn't always define so they are a mix of syntaxes, throw in the specs evolving since first releasing; it becomes that much harder and there are always tradeoffs.  If you check the open issues you'll also see things like we're starting to have concerns with having used `Data` for `bytes` fields - minimal cost for Apple platforms, but on Linux, it does pull in Foundation, and there are advantages there to maybe having a different type for these.  So, yea, things can always change in the future.  :)

**Comment by wilg** [comment]
Thanks for the response! I'm totally sympathetic to the complex needs of an infrastructural library like this. 

In general, I think the trade off with message fields would be okay for me – explicitness of what's present feels better than things being implicitly created/defaulted, but maybe it would have issues in practice. Will try to think about some of the the issues you raise with repeated/map fields, not sure about that one.

For me, the great advantage of protobuf is not having to define model objects in my client code, or do any custom parsing, and letting the server/api definition control that. This means I'm perhaps more sensitive to the feel of the Swift code than perhaps other use cases are, because I interact with them directly a lot everywhere in my app.

Perhaps I will try a strategy of post-processing the generated code. Or maybe I could somehow use decorators or some other feature like that.

**Comment by thomasvl** [comment]
While I think of it - the protobuf guides don't seem to mention this, but one other thing to consider is the adding/removing `optional` to a field.  For the wire formats, I believe it should be fine, but if one were to generate `Optional` it would be an api break when the .proto file was tweaked.  Again, just something to consider.

**Comment by cburrows** [comment]
> Perhaps I will try a strategy of post-processing the generated code. Or maybe I could somehow use decorators or some other feature like that.

I would recommend against post-processing the generated code, that seems like a nightmare.

It sounds like your particular build tools are flexible enough that you might be interested in building your own protoc extension to run alongside this one. It would be pretty straightforward to generate extensions of the `Message` types, in their own file, that give you some kind of `Optional` properties (or something else?) when suitable. This would be a great way to experiment with your ideas about how to do this, and might give some good feedback re: how usable `SwiftProtobufPluginLibrary` is.

**Comment by wilg** [comment]
> I would recommend against post-processing the generated code, that seems like a nightmare.

Haha, yes it probably is. I already have a little bit of tooling to do this (such as to be able to annotate fields as deprecated in Swift), but I might just do that to play around.

> It sounds like your particular build tools are flexible enough that you might be interested in building your own protoc extension to run alongside this one.

I'll check that out, thanks!

**Comment by acecilia** [comment]
Reading in [here](https://github.com/apple/swift-protobuf/blob/main/Documentation/INTERNALS.md#field-storage):

> Usually, the current form seems to noticeably simplify the usage: Most of the time, you just want to use whatever value is there, relying on the default when no value was set explicitly. Sometimes, you may need to verify that the other side explicitly provided the values you expect. **In these cases, it is generally easier to assert that the received object has the expected fields in just one place, then use the current values throughout, than to test and unwrap Swift Optionals at every access.**

I would say I fully disagree with this statement 🤔 The type system is in fact designed to support optionals. The fact that something is `nil/true/false` is very valuable information that should stay present when using the type, and must not be reduced to `true/false`. Example:
* If a schema contains a message, and the message has a mandatory (non-optional, expected to always be present) boolean property
* The generated code should use the Swift type system, and not allow frontend to create the message without providing the boolean property

Having this in mind:
* Making a distinction between `proto3` and `proto3+optional support`
* If somebody uses `proto3+optional support`, and does not need to keep backwards compatibility with `proto3` or `proto2`

Would it make sense to add an option, so the generated Swift code relies on the Swift type system, and uses `Swift.Optional` to represent protobuf `optional` fields?

**Comment by acecilia** [comment]
@thomasvl would appreciate your feedback on above last question 🙏: if we were to use `proto3+OptionalSupport` and forget for a second about backwards compatibility, would the correct approach be to use Swift optionals?
If yes, would it make sense to add an option to support this?
