### ISSUE TITLE
Ubuntu 14.04 cannot compile 0.9.24 with dynamic library creation in Package.swift

### ISSUE THREAD

**Issue by ShaneQi** [apple/swift-protobuf#113]
When I compiled 0.9.24 on an Ubuntu 14.04, I experienced this error:

``` bash
$ swift build
Linking ./.build/debug/libSwiftProtobuf.so
/usr/bin/ld: /home/Shadow/test/swift-protobuf/.build/debug/SwiftProtobuf.build/ProtobufBinaryEncoding.swift.o: relocation R_X86_64_PC32 against protected symbol `_TMaV13SwiftProtobuf29ProtobufBinaryEncodingVisitor' can not be used when making a shared object
/usr/bin/ld: final link failed: Bad value
clang: error: linker command failed with exit code 1 (use -v to see invocation)
<unknown>:0: error: link command failed with exit code 1 (use -v to see invocation)
<unknown>:0: error: build had 1 command failures
error: exit(1): /home/Shadow/.swiftenv/versions/3.0/usr/bin/swift-build-tool -f /home/Shadow/test/swift-protobuf/.build/debug.yaml
```

Since compiling 0.9.23 doesn't have this problem, I checked diff between 0.9.23 and 0.9.24.

It turned out that if I delete [dynamic library creation code](https://github.com/apple/swift-protobuf/blob/master/Package.swift#L11-L14) from Package.swift, it can be compiled successfully.

**Comment by allevato** [comment]
This looks similar to https://bugs.swift.org/browse/SR-1023 (Swift not respecting the gold linker on Ubuntu), but it was supposed to have been fixed in May by the PR linked in that issue. So that's definitely puzzling, assuming you're using an up-to-date version of Swift (I can't imagine that this library would build with a pre-May release of the language anyway).

**Comment by ShaneQi** [comment]
I'm using Swift 3.0. And I even tried 3.0.1-PREVIEW-3 on two machine(both 14.04), the issued didn't go away.

This issue might not be exactly caused by the bug you mentioned, but it's not swift-protobuf project's issue for sure.

How about making it only execute in not-Linux-OS?

```swift
#if os(Linux)                  
  
#else
// Ensure that the dynamic library is created for the performance test harness.
products.append(
    Product(name: "SwiftProtobuf", type: .Library(.Dynamic), modules: "SwiftProtobuf")
) 
#endif
```

**Comment by allevato** [comment]
AFAIK that will make the performance harness fail to build on Linux because the shared library won't necessarily be built.

I don't have a Linux setup handy to try it out, unfortunately—can you give performance harness a try with your change and report what happens? I suspect it won't generate the library and the linker step will fail.

It would be nice to figure out what's going on here without just killing the shared library on Linux, but if the whole thing doesn't build on Ubuntu **anyway**, then it might be a wash.

**Comment by ShaneQi** [comment]
Under the change I made, and I assumed `./perf_runner.sh -s2 5 string` is how to do the performance harness (not quite sure). 

Result:

```bash
$ ./perf_runner.sh -s2 5 string
Generating test proto with 5 fields...
Generating test harness...
protoc-gen-swift: Generating Swift for _generated/message.proto
Building test harness...
<unknown>:0: error: unable to load standard library for target 'x86_64-apple-macosx10.10'
```

**Comment by allevato** [comment]
Ah, of course, I've hardcoded the macOS platform into the harness, so that would also need to change. 😄 

In that case, yeah, maybe we should go ahead and conditionally keep that out of Linux for now since I need to fix the perf harness anyway.

**Comment by thomasvl** [comment]
I think https://github.com/apple/swift-protobuf/commit/2bc0ff270243766c9e083a0533564992feaad3f6 fixed the original problem here (once a new release is cut), so I'm going to go ahead and close this out.  For any other linux issues, lets open up new issues.
