### ISSUE TITLE
How to add swift_prefix option in protoc CLI  tool?

### ISSUE THREAD

**Issue by ZeroJian** [apple/swift-protobuf#1227]
Hey guys 👋

I want to set `swift_prefix `option to some protos, but I don't want to change the proto file

so, how to add  option globally?

**Comment by thomasvl** [comment]
Currently there is no way to do it.

Rather than using the prefix options, you might want to consider using `typealias` within your module to provide non `public` shorter names for the code within the module.  That gets you the benefits of shorter names, but still avoids the potential naming collisions in the future if you add more protos and other packages, but tried to shorten them accidentally to things that collide.

**Comment by ZeroJian** [comment]
> 

thanks @thomasvl thank you for your reply
