### ISSUE TITLE
Rework the setFromXyz methods in ProtobufBinaryTypes.swift for unknown fields

### ISSUE THREAD

**Issue by thomasvl** [apple/swift-protobuf#128]
From @tbkka 

> Rework all the setFromXyz methods in [ProtobufBinaryTypes] to explicitly call
> `decoder.markFieldUnknown()` to archive an unknown field which in turn means we can drop the
> `Bool` return. This would be a much clearer way to handle unknown fields, I think.  It does ripple
> through the entire decode stack, though.

This would remove the need for the return true/false.  The one other thing to remember is for proto2 syntax, they data goes in unknowns as suggested, but for proto3 syntax, the data would be dropped.

**Comment by tbkka** [comment]
Addressed in #134:  Instead of explicitly telling the decoder that a field is unknown, it turned out to be more straightforward for the decoder to track whether the field value is actually requested.  This still removes the return true/false through much of this path and isolates unknown field handling in the protobuf binary decoder, which is the only place that actually needs this support.
