### ISSUE TITLE
Protobuf response not received on iOS 16 Official release version

### ISSUE THREAD

**Issue by SalvikarRahul** [apple/swift-protobuf#1301]
Hi All, Before iOS 16 official release (iOS 16 Beta, 15, 14, 13 12) protobuf response getting properly. I am facing an issue only on iOS 16 below iOS its working fine. Please check.

**Comment by FranzBusch** [comment]
Could you get a little more specific here please. Where are the protobuf messages coming from? What kind of transport are you using? Are you seeing any error or could you provide some logs?

**Comment by SalvikarRahul** [comment]
Hi, I am not getting any error kind of thing from protobuf but in iOS 16 release version, some protobuf **requests are working** and **some requests not working**. My concern is that, how below iOS 16 version it's working fine?

My project is based on can2ble protocol where the application communicates with the BLE module using protobuf. I send some requests and receive the message via protobuf. It's working fine below the iOS 16 official release. I can't get any error from protobuf that's why I can't share any log. 

Also, I update pod lib from the main branch (Installing SwiftProtobuf (2.0.0)) after that I am getting the below errors 

-> Type '_GeneratedWithProtocGenSwiftVersion' does not conform to protocol 'ProtobufAPIVersionCheck'

-> No type named 'ProtobufAPIVersion_2' in module 'SwiftProtobuf'

**Comment by FranzBusch** [comment]
We don't recommend using the main branch since there are a lot of changing going on (even breaking changes). You would need to regenerate your Swift code to avoid. the compiler errors.

Back to your problem though that doesn't necessarily sound like a protobuf problem, it might be that something in your BLE stack changed and serlization fails now. We can't say much more from this description, if you could provide more infos what exactly fails that would help.

If deserialising a type from some `Data` fails it should throw an appropriate error of what went wrong.

**Comment by SalvikarRahul** [comment]
Due to getting low MTU size that why this issue is causing. Thanks team for support.
