### ISSUE TITLE
Add option for generating individual files for messages/enums

### ISSUE THREAD

**Issue by KaneCheshire** [apple/swift-protobuf#1305]
Hello! 

## Context

We have a fairly large Proto file which, when generated into Swift code, Xcode struggles to open. We had the same issue with our objc generator but we were able to mitigate this by creating individual header files, but one huge implementation file. That way Xcode only needs to open a small header file.

Naturally, since Swift doesn't have header files in the same sense, when using SwiftProtobuf we only have the option for creating one huge Swift file, and Xcode can often hang for minutes at a time to open it, which is a poor experience for our developer team. We still want to use SwiftProtobuf because of the benefits we get from Swift, but we need some way to improve this experience.

## Suggestion

During our initial investigation with a fork of the repo we found it was not too difficult to tweak the implementation to generate individual Swift files for each message and enum, and so I was wondering if you'd consider adding official support for this, enabled via an option passed when running the plugin?

I wouldn't mind taking a look at this and opening a PR, but I wanted to discuss via an issue first to avoid wasted effort.

Another nice bonus of doing this that we found is that the plugin runs _significantly_ faster when creating individual files, because a new CodePrinter is created for each file, which really slows down a lot when using a single CodePrinter with a huge Proto file. We're talking down from over 10 minutes to just 14 seconds. This could maybe be improved for all cases, but it's a nice side effect of creating individual output files.

**Comment by thomasvl** [comment]
For the sake of all developers - if you've got any reasonable sorta repo, please file a Feedback on Xcode. Anything one can do to help improve Xcode is a win for all developers!  😄 

I'm also sorta curious why the protos can't be split up. It sorta sounds like a less than idea .proto file if it causes issues in multiple languages.

The comment about `CodePrinter` also has me very curious. Since the multiple files should actually end up being _more_ bytes (since it's the same code plus the imports repeated in each file).  Do you have a repo you can share and/or can you profile the generation to try to understand what's causing the bad behavior there?  Sounds like there could be general improvements done.

As to the main request, a few thoughts:
-  From a road map pov it would complicate things like #18; as there's a good chance that means double the number of files. 
-  One down side of this sorta option is it doesn't integrate well with build systems that require knowing the outputs based on the inputs (make, bazel, etc.).
- When you say one file per message/enum' how does nesting of messages/enums play into that? Are they still each different files, or are you just talking about a file per top level item?
-  A .proto file can also have a lot of extensions, would you do one file for all extensions?  A file for each _scope_ extensions are declared at? A file per extension field? There's also the registry we create for the file that has to end up some place.

Having said all that, I'll say personally, I'm not completely opposed to it, just want to make sure we understand where it will/won't help and what it means for the project going forward as it will have to be supported.

@tbkka @Lukasa @FranzBusch - any thoughts?

**Comment by FranzBusch** [comment]
I agree with the points @thomasvl brought up here. Especially, the idea of splitting up the proto file. That seems like the first act to tackle this problem.

I am also not fully opposed to the idea; however, as Thomas stated build systems will get problems and the SPM plugin can't support this since they all need deterministic output files.

**Comment by KaneCheshire** [comment]
All good points!

> if you've got any reasonable sorta repo, please file a Feedback on Xcode

I can't share our mega Proto file but I might be able to run a script to obfuscate names and remove comments etc and then see if the same thing happens (it should, it's just about file size the strain on Xcode so names shouldn't make any difference). I'll try and find some time to do this soon.

> I'm also sorta curious why the protos can't be split up. It sorta sounds like a less than idea .proto file if it causes issues in multiple languages.

It's an ongoing discussion internally but the current architecture of how we use the files across specialisms makes it tricky

> The comment about CodePrinter also has me very curious

When I find the time for the Xcode radar I should be able to use the same project to share here for the CodePrinter issue. I believe it's just due to the way memory allocation is increased but haven't confirmed. Since creating separate CodePrinter instances per-message/enum is so fast I can't think of what else it could be, CodePrinter itself isn't super complicated!

> When you say one file per message/enum' how does nesting of messages/enums play into that? Are they still each different files, or are you just talking about a file per top level item?

I think for simplicity it would be one file per root message or enum, nested types could stay in the same file, at least as a first iteration.

> A .proto file can also have a lot of extensions, would you do one file for all extensions? A file for each scope extensions are declared at? A file per extension field? There's also the registry we create for the file that has to end up some place.

This is a good point I hadn't totally considered, there would definitely need to be some way of the code knowing to generate the registry just once somewhere (either in its own file, or the first file that gets generated). I think where the extensions get generated would be up for discussion, I have no strong feelings either way. I guess it makes sense to either keep them with the thing being extended, or have a naming convention like SomeMessage+Extensions.pb.swift (as an example).

> One down side of this sorta option is it doesn't integrate well with build systems that require knowing the outputs based on the inputs (make, bazel, etc.).

This is the real sticker for me that I hadn't considered because it doesn't affect us. I'm not sure of the best solution here, the only thing I can think off the top of my head is that you know all files in a certain folder would be generated by SwiftProtobuf so you could do some directory magic to find out what was generated consistently that way (especially if you combined known file extensions like pb.swift)

**Comment by FranzBusch** [comment]
> This is the real sticker for me that I hadn't considered because it doesn't affect us. I'm not sure of the best solution here, the only thing I can think off the top of my head is that you know all files in a certain folder would be generated by SwiftProtobuf so you could do some directory magic to find out what was generated consistently that way (especially if you combined known file extensions like pb.swift)

Sadly, that doesn't work for most build systems since you need to know ahead of time what files are being generated and not after you ran the generation. This is necessary since build systems need to be able to build a graph of actions including what files are involved and generated.

**Comment by thomasvl** [comment]
Slight aside – How heavily commented is your .proto file? An option to skip bring over comments to the generated code could also help in cases like this. The downside being then Xcode can't extract/index the comments to provide them in its UX.

**Comment by tbkka** [comment]
We should certainly address the performance issue.  (I doubt it's the CodePrinter; I suspect we have some linear descriptor scans that could be sped up.)

You should definitely file an issue with Apple about the Xcode performance issue.

I would encourage your team to consider splitting up your .proto files.   Google's own proto files in the protocolbuffers repository can be used as a model for how to do this well.

But, I am personally not comfortable with the idea of breaking up the output in the code generator.  As Franz and Thomas pointed out, there are many build systems that need to know every generated file in advance, and therefore cannot be used properly with systems that generate different output files depending on the contents of the input.  (In fact, the design of SwiftProtobuf in this respect is partly a reaction to my own problems with an earlier implementation that did break up the output in just the way you describe.)

**Comment by thomasvl** [comment]
Closing given the comments.

**Comment by adriantabirta** [comment]
Hi, 

I have the same problem:

I would like to have some `common.proto`,  `request.proto`,  `response.proto` cus services are big enough.
I have tried to extract `common.proto`  and then `import "common.proto" but plugin gives me error that cannot find.

Solution:
I know that using comand line tool it is possible to specify full path to the files and it work. Maybe plugin could be configured for that?

**Comment by FranzBusch** [comment]
Hi @adriantabirta,

You can split this into multiple `.proto` files and import them. You just need to use the relative path. @glbrntt just answered a similar question in the gRPC repo which also applies here: https://github.com/grpc/grpc-swift/issues/1525#issuecomment-1337031297
