### ISSUE TITLE
OneOf enum None case name

### ISSUE THREAD

**Issue by soffes** [apple/swift-protobuf#133]
Should this be renamed to `none` (from `None`) for consistency with the rest of the generated cases and Swift 3's convention of lowercase enum cases?

Also, should another name be considered to avoid confusion with `Optional.none`?

**Comment by tbkka** [comment]
It was spelled in uppercase to ensure that it could not conflict with a generated case.  Otherwise, we would need special checks in case someone had a oneof field called 'none'.

We could use some other convention, of course.   I have no opposition to changing the name if someone could suggest something better.

**Comment by soffes** [comment]
Ah. That makes sense. Could you just omit the `None` case and make the enum optional instead? I think that feels better. I'll think about it some more.

By the way, totally love that `oneof` get generated this way! So amazing! :heart:

**Comment by allevato** [comment]
Vacation drive-by comment: Generating `oneof` cases as optionals is an interesting idea. It does make pattern matching a little trickier, because you'd have to do this:

```
switch msg.someOneOf {
case .foo(let value)?:  // or case .some(.foo(let value))
  ...
case .none:  // or case nil; in either case, note the lack of question mark
  ...
}
```

(I've encountered a few experienced Swift programmers who weren't aware of the `case .foo?` shorthand. I was once one of them. So one could argue that the patterns needed to use the field would be slightly as discoverable.)

But setting that parenthetical aside, maybe that's not a bad thing because it enforces the fact that either one of the fields has "some" value or "none" of them do.

I pushed for non-optionals everywhere earlier in our generated properties because we needed to handle default values correctly, but unlike non-`oneof` fields, there isn't a default value here to worry about. The case being "none" means that none of its fields are set, and the default values of those individual fields are still accessible using those fields' properties instead of the case, if need be.

I'll have to sleep on it to see if I can come up with any situations where this would break expectations. But it sounds promising.

**Comment by thomasvl** [comment]
I guess one upside is also clearing the `oneof` becomes setting it to `nil` (instead of setting it to `.None`).

I wonder how likely folks would be to nest the whole switch/case under a `if let`, because they don't know the `?` part?

**Comment by tbkka** [comment]
Added labels "API change" (since this would affect the API seen by users) and "generator API" (since it affects the API between the generated code and the library).

**Comment by thomasvl** [comment]
@allevato - Assigning to you given the last major comment seemed to be you'd figure out if there could be issues with it.

No matter what we decide, I likely should tweak my isInitialized code since I'm currently blindly adding the .None case, and I think I can shrink the codegen with whatever we decide.
