### ISSUE TITLE
hashValue is the same on any two instances of Google_Proto_Any as long as the packed message type is the same

### ISSUE THREAD

**Issue by aodhol** [apple/swift-protobuf#1349]
iOS: 16.x
Swift: 5.7
protoc: 3.21.9
SwiftProtobuf: 1.17.0

Should this unit test pass?

```swift
func testHashValuesAreNotEqualBetweenDifferentUnderlyingValues() {

    let myComponent1 = MyComponent.with { component in
        component.titles = ["Hello", "World"]
    }

    let myComponent2 = MyComponent.with { component in
        component.titles = ["Ipsum", " Lorem"]
    }

    let any1 = try! Google_Protobuf_Any(message: myComponent1)
    let any2 = try! Google_Protobuf_Any(message: myComponent2)

    XCTAssertNotEqual(any1.hashValue, any2.hashValue)
}
```

**Comment by thomasvl** [comment]
A hash is just that, a _hash_; nothing says two different message will always have a unique _hash value_.  But on top of that `Google_Protobuf_Any` is sorta unique. Since it has to deal with messages where the wrapped type might not be known at runtime (to reflect it back out, etc.), it special cases hash and only factors the `typeURL` in because otherwise there might be cases where the hash comes out different when the messages are actually equal. You can read about this in [the implementation](https://github.com/apple/swift-protobuf/blob/1.17.0/Sources/SwiftProtobuf/AnyMessageStorage.swift#L304-L340) (that's the 1.17.0 release, since that's what you said you were using).

**Comment by tbkka** [comment]
> Should this unit test pass?

As Thomas pointed out, the only hard requirement for a hash implementation is that _equal_ values must have _equal_ hashes.  You cannot in general assume anything about the hash value of _unequal_ values.  In addition, `Any` does not know anything useful about the value it contains.  For example, if an intermediate system is decoding and re-encoding some message, it may not actually have an implementation of the type stored in the `Any`, just the name of the type and the raw encoded data.  And it cannot compute a hash from the raw encoded data without understanding the meaning of that data (e.g., two messages may have the same integer value stored in different formats).

Do you have a reason why you believe those two messages _should_ have different hashes?

**Comment by aodhol** [comment]
> A hash is just that, a _hash_; nothing says two different message will always have a unique _hash value_. 
My expectation was that if I know the two values are the same, then they'd have the same hash value. I understand that there can be collisions and that it shouldn't be taken to mean things are the same or different generally. Thanks for the explanation both! 

The Java equivalent seems to pass mind you...
