### ISSUE TITLE
Errors thrown and performance degradation when reading binary delimited data directly from a file

### ISSUE THREAD

**Issue by willtemperley** [apple/swift-protobuf#1410]
When reading a 26MB binary delimited file with an InputStream created directly from a file (i.e. ```let inputStream = InputStream(url: fileUrl)```, the following test always throws a ```SwiftProtobuf.BinaryDelimited.Error.truncated``` error with a measured [Time, seconds] average: 1.893

```
    func testReadArchiveError() throws {
        measure {
            var nMessages = 0
            let inputStream = InputStream(url: fileUrl)
            if let inputStream = inputStream {
                inputStream.open()
                while (inputStream.hasBytesAvailable) {
                    do {
                        _ = try BinaryDelimited.parse(messageType: Io_Temperley_Archive_BaseMessage.self, from: inputStream)
                        nMessages += 1
                    } catch {
                        print(String(reflecting: error))
                    }
                }
                
            }
            print("n messages: \(nMessages)")
        }
    }
```

however, reading the same file into memory first never throws, with a measured [Time, seconds] average: 1.236

```
    func testReadArchive_No_Error() throws {
        measure {
            var nMessages = 0
            let data = try? Data(contentsOf: fileUrl)
            if let data = data {
                let inputStream = InputStream(data: data)
                inputStream.open()
                while (inputStream.hasBytesAvailable) {
                    do {
                        _ = try BinaryDelimited.parse(messageType: Io_Temperley_Archive_BaseMessage.self, from: inputStream)
                        nMessages += 1
                    } catch {
                        print(String(reflecting: error))
                    }
                }
            }
            print("n messages: \(nMessages)")
        }
    }
```

This feels like a bug - performance is significantly worse when reading directly from the file, plus it's clear that the stream isn't truncated. Maybe InputStream.hasBytesAvailable is just unreliable, but it seems surprising. The Java version doesn't have this issue. (I'm porting a Java app to Swift - the input file was created in Java). The following runs in ~1.18 seconds.

```
    @Test
    public void messageCount() throws IOException {
        FileInputStream inputStream = new FileInputStream(fileName);

        int nMessages = 0;
        while (inputStream.available() > 0) {
            ArchiveSchema.BaseMessage baseMessage = ArchiveSchema.BaseMessage.parseDelimitedFrom(inputStream);
            if (baseMessage != null) {
                nMessages++;
            }
        }

        System.out.println("i = " + nMessages);
    }
```

* what OS you are developing on (Linux or macOS, including the version)
**MacOS 13.4.1 (Ventura)**

* for macOS, what version of Xcode you are using (`xcodebuild -version`),
Xcode 14.3.1
**Build version 14E300c**

* what version of Swift is your code set to compile with (i.e. from project
  settings, etc.)
**Swift 5**

* what branch/tag of SwiftProtobuf you are using (1.0.0, etc.)
**1.22.0**

**Comment by thomasvl** [comment]
Can you put together a test case someone here can run to ensure they are looking at your same failures or do some tracing to figure out if Foundation is returning unexpected results.

Since we're depend on Foundation, for NSInputStream, their likely won't be a lot we can do performance wise there.

Depending on what's failing, it might make sense to prune some of the `hasBytesAvailable` checks, but it does mean things could become blocking on the stream, so the behavior change would have to be evaluated.

**Comment by willtemperley** [comment]
I put together a self-contained test which writes 1000 protobuf messages to a temporary file, and reads them again. The same behaviour is observed.

https://gist.github.com/willtemperley/ed780f3977b70064f6f878e4a9353c4d

There's a limitation of NSInputStream that `hasBytesAvailable` is unreliable - it is stated in the docs it may return true if a read is required to determine availability of bytes.

However none of the workarounds I can think of feel very good:
1. Catch the error as a normal part of control flow - not great practice.
2. Provide metadata defining the number of messages in a file. This just isn't necessary on other platforms.
3. Read the file into memory, which is OK until files get large.

**Comment by thomasvl** [comment]
Thanks, I hacked up something quickly some what similar to your test: https://gist.github.com/thomasvl/9f83f00b9b32a1227adc3a9d194f303f

You can see the commented out parts that don't pass, but otherwise it passes for me.  I'm on the same OS and Xcode versions.  I am on an Intel Mac and not an Arm one if that matters.  I get the same results on both the 1.x branch and the _main_ branch.  It does confirm `hasBytesAvailable` likes to lie. ☹️

So while we can change things to avoid the library itself calling `hasBytesAvailable`, to write something that generically parses things, you might have to try the delegate and the StreamEvents to see if that gives you a better signal for when the end of the stream has been reached.  Again, this isn't an issue with the api for delimited messages, it's more a problem with Foundations NSInputStream and it not having a good way for you to tell if there is data available.

**Comment by tbkka** [comment]
Hmmm.... with the code above, `BinaryDelimited.parse()` has to either return a valid parsed message or throw an error.  If `hasBytesAvailable` returns `true` and there are in fact no bytes available, then our only choice is to throw an error.  I suppose we could return a different error for the case where there are truly no bytes on input, maybe `BinaryDelimited.Error.empty` instead of `BinaryDelimited.Error.truncated`?

**Comment by tbkka** [comment]
I wonder if there's a better way to use `InputStream` and/or a good alternative that we should be using instead?

**Comment by thomasvl** [comment]
So when I first looked at this, I was on my phone trying to look at the sources, and I remembered/got things wrong.  We don't use `hasBytesAvailable` at all, we simply attempt to read when told to and throw `truncated` when the reads come back with zero bytes.  So it really comes down to the code calling the delimited api can't safely rely on `hasBytesAvailable`.

One tweak I can see is we could change things so if the _first_ read of a byte for the length comes back with no data, that we throw a specific error that there was no data. That would let caller work around this odd behavior with `NSInputStream` reading from a file because they could know there was no corruption, and just no data to read.

Outside of that, we could do our own custom protocol that developers can provide custom streams to read from (like we did for the binary serialization apis), but the most useful thing would be for it to align with the Stream apis, which puts us right back in the same problem.

The next choice I can see to do would be to do what the Protobuf C++ and Java apis do, and have full input/output stream classes of our own that completely replace the Foundation concepts and folks just have to use our versions. 😦

**Comment by thomasvl** [comment]
ps - I really starting to think one has to use the delegate/StreamEvents to attempt to deal with data as it arrives.

But we might also need more error codes, because I can see cases where there is data, but maybe not a full varint for the length, or maybe not the full payload, so we might need better signals that that that isn't corrupt, just the next conception message can't be completely read.  I've seen other library (for C++), where they do everything still on something effectively like Data, and the interaction with streams is left to the callers so they can buffer/scroll things along (i.e. - reading delimited both reads a message and returns the number of bytes consumed, so the caller knows have much to advance in the payload that was attempting to be parsed from)

**Comment by FranzBusch** [comment]
> Outside of that, we could do our own custom protocol that developers can provide custom streams to read from (like we did for the binary serialization apis), but the most useful thing would be for it to align with the Stream apis, which puts us right back in the same problem.

I don't think we need to invent our own API here. Swift offers `AsyncSequence` for streaming data and we could in theory provide an async API that tries to decode from an `AsyncSequence` which carries a `Collection<UInt8>`. We should be able to make this relatively performant as well.

**Comment by tbkka** [comment]
Would you consider contributing this to SwiftProtobuf?   I have a few stylistic nits, but the approach (and performance) seems really promising.

P.S.  yeah, we still have some optimization work to do.  😁

**Comment by willtemperley** [comment]
Yes I'd be happy to contribute it - also criticism would be gladly accepted - it's early days with Swift for me. 

I could put together a pull request if you tell me where you'd like it in the codebase and if there are any naming conventions etc.

Things I'd already like to change:
1. I'd probably move the InputStream extension code into the Iterator 
2. I'd try and make the initializer not throw
3. I think there's a bug lurking in the read() method when buffers align with message sizes

**Comment by tbkka** [comment]
I'm kind of tempted to fold your MessageIterator in as a static method on Message.  Maybe something like:

```
extension Message {
   struct StreamDecodingIterator: IteratorProtocol { ... }

   static func streamDecodingIterator(inputStream: InputStream, bufferLength: Int = 32768) -> StreamDecodingIterator {
        return StreamDecodingIterator<Self>(inputStream: inputStream, bufferLength: bufferLength)
   }
}
```

Then you could use it like:
```
for m in MyProtoMessage.streamDecodingIterator(inputStream: s) {
   ...
}
```

That would start with renaming your current source file to `Message+StreamDecodingIterator.swift` and then we can debate the implementation details over a PR.

One interesting bit of trivia:  We're actually debating techniques for largely eliminating `Data` from our API.  The above design does exactly that -- it still uses `Data` internally as an implementation detail, but that can be adjusted in the future as we explore other options.

**Comment by thomasvl** [comment]
I guess #1434 could be considered to cover the performance side of things, but the errors because of what availableBytes does probably should still be looked at to make that api a little more usable.

**Comment by willtemperley** [comment]
I think it's not an error at all when zero bytes are read in `merge<M: Message>` - it's just the end of the stream.

https://github.com/apple/swift-protobuf/blob/fdbc3aac01988b77bf1cdca514296523da7c360b/Sources/SwiftProtobuf/BinaryDelimited.swift#L199

The only options that spring to mind are a bit messy:
1. make `merge` return the number of bytes read, and` parse<M: Message>` return nil on zero-byte read.
2. keep `merge` intact, duplicate some of the logic in `parse` and return nil like in 1.

**Comment by thomasvl** [comment]
The problem is `parse` doesn't return an `Optional`.  So short of changing the signature, the best bet might be to simple add a new error that's not really an error so callers to handle that and realize it isn't corruption, but simple the _clean_ end of the stream.

**Comment by willtemperley** [comment]
Ah I see. So just throw `BinaryDelimited.Error.endOfStream` or something when zero bytes are read which the caller can ignore.

**Comment by willtemperley** [comment]
From my point of view that fixes the main issue - i.e. it was impossible to tell the difference between a real truncated stream (which does happen) and `InputStream` being unwilling to find out if it has data left.
