### ISSUE TITLE
No type named 'ProtobufAPIVersion_3' in module 'SwiftProtobuf'

### ISSUE THREAD

**Issue by tuannm2** [apple/swift-protobuf#1479]
I'm using SwiftProtobuf version 1.24.0
I generated swift file contain v3
```
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _3: SwiftProtobuf.ProtobufAPIVersion_3 {}
  typealias Version = _3
}
``` 

And got the error 'No type named 'ProtobufAPIVersion_3' in module 'SwiftProtobuf''. How can I resolve the problem

**Comment by tbkka** [comment]
This means you have somehow managed to get a different version of the `SwiftProtobuf` module that has a different (incompatible) API.   `ProtobufAPIVersion_3` is the current version, so that means the `SwiftProtobuf` module you're using must be quite old.

**Comment by thomasvl** [comment]
_3 is 'main' (so unreleased 2.0) vs an labeled release.

You need to build the plug-in with the same version you are trying to integrate into your project.

**Comment by thomasvl** [comment]
Closing this as it sounds like it is a problem using a non matching plugin and library version.

**Comment by tbkka** [comment]
`ProtobufAPIVersion_2` or `ProtobufAPIVersion_3` does _not_ indicating the syntax used in the proto file.  It is the version of the library API that is being used.  Completely different thing.

If you have a mismatch here, it means you're using a different version of the SwiftProtobuf package than the version of SwiftProtobuf you used to compile the protos.  Those should generally match.   I suspect you need to specify the `1_x_release_branch` in your Package.swift file when incorporating the SwiftProtobuf package.  (Because `main` can contain untested and/or experimental changes, it's marked with a different API version from the stable 1.x branch.)

**Comment by thomasvl** [comment]
Even though main use 2 again, that doesn't mean something generated with main will work with an old release.  Swift doesn't have a good way to model the min/max version, so all we can do is say that the current supports old, not the other way around.
