### ISSUE TITLE
The "thread" sanitizer testing is failing

### ISSUE THREAD

**Issue by thomasvl** [apple/swift-protobuf#1571]
Attempting to run with 5.10 on the github CI fails for both debug and release with:

```
FATAL: ThreadSanitizer: unexpected memory mapping 0x644ed6848000-0x644ed7cbe000
```

**Comment by thomasvl** [comment]
From #1574, this is looking more like a base image issue and not specific to 5.10.

**Comment by thomasvl** [comment]
Google Search for _ThreadSanitizer: unexpected memory mapping_ in the last week turned up: https://www.mail-archive.com/kernel-packages@lists.launchpad.net/msg522188.html

**Comment by Lukasa** [comment]
That seems highly likely to be relevant.

**Comment by thomasvl** [comment]
https://github.com/google/sanitizers/issues/1716 has a bunch of reference that might be useful to work around things.

**Comment by thomasvl** [comment]
https://github.com/actions/runner-images/issues/9491 also might be useful to track.

**Comment by mkruskal-google** [comment]
FWIW, I've traced Protobuf's similar issue back to github's 20240310.1.0 release of ubuntu-22. Downgrading to ubuntu-20 seems to workaround it. Historically, there have been a handful of linux kernel updates that broke sanitizers in this way, so it seems like a likely culprit since they did upgrade to 6.5.0-1016-azure

**Comment by Lukasa** [comment]
That seems like a likely diagnosis.
