### ISSUE TITLE
SwiftProtobufPluginLibrary.FileDescriptor.proto is deprecated

### ISSUE THREAD

**Issue by glbrntt** [apple/swift-protobuf#1678]
The `proto` property on `SwiftProtobufPluginLibrary.FileDescriptor` is deprecated. In grpc-swift we currently use this property to generate data for the grpc [reflection service](https://github.com/grpc/grpc/blob/master/doc/server-reflection.md) (which effectively serves serialized file descriptor protos).

Would you be open to either un-deprecating or providing new API to support this use case? I'd be more than happy with a `fileDescriptor.serializedFileDescriptorProto()` or something similar.

**Comment by thomasvl** [comment]
I've been worried about this one since I noticed grpc doing this.  Depending on what exactly folks want to do with the descriptor, the Editions information would have to be correctly handled, and since we don't expose `Descriptor`s, there isn't any way to do this, someone would have to completely re-implement all the work if they wanted to inspect something related to it.

And exposing it, just document it isn't really safe to use feels a bit like a dodge, since it isn't setting anyone up to correctly do things.  Scanning that reflection doc, if the intent is just to provide that, maybe it makes to just expose the original `Data` blob so there isn't any implication that the information is in a parsed/usable form?

**Comment by thomasvl** [comment]
PS - there's [Option Retention](also https://protobuf.dev/programming-guides/proto2/#option-retention), which likely should be considered in this space. Can't say I've looked at it before.

**Comment by thomasvl** [comment]
I've reached out to the protobuf team about the option retentions for more information.

**Comment by thomasvl** [comment]
Retention handling is handled in C++ via [src/google/protobuf/compiler/retention.h](https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/compiler/retention.h). There's also a flag to control removing the source code info to cut down on the size of things, which I'm guessing the reflection stuff would also want.

So odds are the _right_ thing to do would be to add some apis like this to give generators the control to capture the correct things.

**Comment by thomasvl** [comment]
Actually, the plugin interface already includes the filtered info: https://github.com/protocolbuffers/protobuf/blob/cba41100fb1e998660ef4fb12aeef2871a15427c/src/google/protobuf/compiler/plugin.proto#L73-L76

So I guess the question is do we want to expose it as the raw `FileDescriptorProto` or should we wrapper it up and expose it in the serialized form as a `Data` blob.

**Comment by glbrntt** [comment]
Thanks for looking into this Thomas, I wasn't aware of the retention options before.

> Actually, the plugin interface already includes the filtered info: https://github.com/protocolbuffers/protobuf/blob/cba41100fb1e998660ef4fb12aeef2871a15427c/src/google/protobuf/compiler/plugin.proto#L73-L76

IIUC `source_file_descriptors` won't necessarily contain all transitive dependencies of the files to generate? The reflection services relies on having transitive dependencies so this doesn't seem sufficient.

**Comment by thomasvl** [comment]
> > Actually, the plugin interface already includes the filtered info: https://github.com/protocolbuffers/protobuf/blob/cba41100fb1e998660ef4fb12aeef2871a15427c/src/google/protobuf/compiler/plugin.proto#L73-L76
> 
> IIUC `source_file_descriptors` won't necessarily contain all transitive dependencies of the files to generate? The reflection services relies on having transitive dependencies so this doesn't seem sufficient.

So you have to vend a the proto for the file and the entire closure of transitive imports?

**Comment by thomasvl** [comment]
> > > Actually, the plugin interface already includes the filtered info: https://github.com/protocolbuffers/protobuf/blob/cba41100fb1e998660ef4fb12aeef2871a15427c/src/google/protobuf/compiler/plugin.proto#L73-L76
> > 
> > 
> > IIUC `source_file_descriptors` won't necessarily contain all transitive dependencies of the files to generate? The reflection services relies on having transitive dependencies so this doesn't seem sufficient.
> 
> So you have to vend a the proto for the file and the entire closure of transitive imports?

Is https://github.com/grpc/grpc-swift/blob/main/Sources/protoc-gen-grpc-swift/main.swift#L158C13-L162 the relevant code?  It doesn't seem to worry about the imports.

**Comment by glbrntt** [comment]
> > > Actually, the plugin interface already includes the filtered info: https://github.com/protocolbuffers/protobuf/blob/cba41100fb1e998660ef4fb12aeef2871a15427c/src/google/protobuf/compiler/plugin.proto#L73-L76
> > 
> > 
> > IIUC `source_file_descriptors` won't necessarily contain all transitive dependencies of the files to generate? The reflection services relies on having transitive dependencies so this doesn't seem sufficient.
> 
> So you have to vend a the proto for the file and the entire closure of transitive imports?

Yes, the file descriptors for all transitive imports (servers are allowed to not re-send a given file descriptor if it's already sent it to a given client.)

> > > > Actually, the plugin interface already includes the filtered info: https://github.com/protocolbuffers/protobuf/blob/cba41100fb1e998660ef4fb12aeef2871a15427c/src/google/protobuf/compiler/plugin.proto#L73-L76
> > > 
> > > 
> > > IIUC `source_file_descriptors` won't necessarily contain all transitive dependencies of the files to generate? The reflection services relies on having transitive dependencies so this doesn't seem sufficient.
> > 
> > 
> > So you have to vend a the proto for the file and the entire closure of transitive imports?
> 
> Is https://github.com/grpc/grpc-swift/blob/main/Sources/protoc-gen-grpc-swift/main.swift#L158C13-L162 the relevant code? It doesn't seem to worry about the imports.

Certainly looks that way! I suspect the rationale was to generate all transitive dependencies separately.

**Comment by thomasvl** [comment]
> Certainly looks that way! I suspect the rationale was to generate all transitive dependencies separately.

Can you double check how this ends up working for grpc now?  It certainly would be easy to model it with the existing plugin payload if something else it taking care of ensure all the transitive data is there.  Otherwise, we'd will have to look at doing the full filtering if we're supposed to offer it for everything. 😞

**Comment by glbrntt** [comment]
The intention was that transitive dependencies should have their reflection data generated separately, so this:

> So I guess the question is do we want to expose it as the raw `FileDescriptorProto` or should we wrapper it up and expose it in the serialized form as a `Data` blob.

should work just fine.

**Comment by thomasvl** [comment]
Quick update here - I was able to poke at this at little more, and the C++ interface (which I modeled) lacks a way to relay this from the request to the `CodeGenerator` also. I've sent in some questions to the protobuf team since it seems odd that they provide the info but don't expose it to the generators.

My guess would be to model it in out `ProtoCompilerContext` object (as that's how I think C++ would have to expose it also), but I'm waiting for a reply since it seems like keeping the apis aligned might be a good thing.

**Comment by thomasvl** [comment]
Ok, I was thinking about things backwards `source_file_descriptors` have the options _not_ stripped, the `proto_file` repeated field has them stripped (not sure how a plugin would get access to the values that don't have source retention enabled, but the C++ api has the same issue).

But exposing the raw proto does mean any `SourceCodeInfo` is likely being serialized also, and I'm guessing folks really shouldn't be doing that because of the bloat.  `protoc` passes that info along (there might be an option to disable it), but we need that because its what generators use to pull over the comments.
