### ISSUE TITLE
Can we reduce the number of protocols?

### ISSUE THREAD

**Issue by allevato** [apple/swift-protobuf#17]
A single generated message currently conforms to a large number of protocols: `ProtobufGeneratedMessage`, `ProtobufAbstractMessage`, `ProtobufMessage`, `ProtobufMessageBase`, `ProtobufBinaryMessageBase`, `ProtobufJSONMessageBase`, `ProtobufTraversable`, and a handful of standard library protocols.

For the first four in particular, it's not immediately clear from the names alone what the different responsibilities of each one are. (Some of them relate to the differences between the hand-written well-known types and other generated messages, so if we can get rid of the hand-written ones in #13, we can get an easy reduction there.)

Similarly, is there value in keeping `ProtobufBinaryMessageBase` separate? All messages should be binary codeable, since that's defined by the protocol buffer spec. Since it's unlikely that you'd want a non-proto-message type to implement `ProtobufBinaryMessageBase`, its members can be folded into one of the other message protocols.

Likewise, `ProtobufTraversable` doesn't need to stand alone—it provides only one method, and is only implemented by the message types (once #16 is fixed, removing the message/group distinction). That method can be moved into one of the other message protocols.

Reducing this API service will improve the size footprint of the runtime library and make it easier to maintain/understand.

**Comment by tbkka** [comment]
Few notes on the current status quo as I work through some of this:

I don't think there's a technical obstacle to collapsing `ProtobufMessage`, `Protobuf*MessageBase`, and `ProtobufTraversable`.  I'm going to see what that looks like.

I also don't think there's a technical reason preventing `ProtobufAbstractMessage` (the general implementation base) and `ProtobufGeneratedMessage` (the implementation base for generated messages) from being combined.  I'll play with that as well.

However, `ProtobufMessage` and `ProtobufAbstractMessage` cannot be combined.  `ProtobufMessage` is used as a protocol type so cannot have `isEqualTo` (which has a `Self` constraint).  But right now all messages (generated or otherwise) must have `isEqualTo` in order to handle type-erased equality (needed by extensions).  Essentially, `ProtobufAbstractMessage` is the implementation base for all messages, while `ProtobufMessage` is the protocol type.  Maybe there's a better name for `ProtobufAbstractMessage`?

Another interesting constraint:  I've talked to a few people who tried to figure out the base message types by examining the generated code.  So I really want the messages to directly specify `ProtobufMessage` as their first conformance.  As pointed out above, that's insufficient; there must be others, but I think it's important that one appear first.

**Comment by tbkka** [comment]
I feel that #139 addressed the major concern here, so I'll close this.
