### ISSUE TITLE
SwiftProtobufPluginLibrary's WellKnownType type doesn't know about all the well known types

### ISSUE THREAD

**Issue by glbrntt** [apple/swift-protobuf#1735]
The set of well-known types as defined by `SwiftProtobufPluginLibrary` is different to those provided by `SwiftProtobuf`. 

In gRPC, if a service uses well known types which are provided by `SwiftProtobuf` we need to generate an import for them. If we generate them unconditionally and also generate access levels on imports then an unused import will result in an error (because the level the module is imported at differs from how it's used, i.e. not at all).

At the moment we're checking for the presence of [`wellKnownType`](https://github.com/apple/swift-protobuf/blob/952160b58bcd97dd6dac66356d60a71dffeb081b/Sources/SwiftProtobufPluginLibrary/Descriptor.swift#L555) but the [list of well known types that represents](https://github.com/apple/swift-protobuf/blob/952160b58bcd97dd6dac66356d60a71dffeb081b/Sources/SwiftProtobufPluginLibrary/Descriptor.swift#L444-L478) is narrower than the list of well known types that `SwiftProtobuf` vends.

Here's a comparison of the Well Known Types from [here](https://protobuf.dev/reference/protobuf/google.protobuf/) with the types generated by `SwiftProtobuf` and the types which `SwiftProtobufPluginLibrary` considers to be well known:

Name | SwiftProtobuf | SwiftProtobufPluginLibrary
-----|---------------|----------------------------
Any | ✓ | ✓
Api | ✓ | ✓
BoolValue | ✓ | ✓
BytesValue | ✓ | ✓
DoubleValue | ✓ | ✓
Duration | ✓ | ✓
Empty | ✓ | x
Enum | ✓ | x
EnumValue | ✓ | x
Field | ✓ | x
Field.Cardinality | ✓ | x
Field.Kind | ✓ | x
FieldMask | ✓ | ✓
FloatValue | ✓ | ✓
Int32Value | ✓ | ✓
Int64Value | ✓ | ✓
ListValue | ✓ | ✓
Method | ✓ | ✓
Mixin | ✓ | x
NullValue | ✓ | x
Option | ✓ | x
SourceContext | ✓ | x
StringValue | ✓ | ✓
Struct | ✓ | ✓
Syntax | ✓ | ✓
Timestamp | ✓ | ✓
Type | ✓ | x
UInt32Value | ✓ | ✓
UInt64Value | ✓ | ✓
Value | ✓ | ✓

Is this difference intentional / can it be updated?

**Comment by thomasvl** [comment]
The Plugin Library [`Descriptor` vended one](https://github.com/apple/swift-protobuf/blob/952160b58bcd97dd6dac66356d60a71dffeb081b/Sources/SwiftProtobufPluginLibrary/Descriptor.swift#L444-L478) models what the [C++ library does](https://github.com/protocolbuffers/protobuf/blob/7519359b4ba915daf1999ae219e23e1899552633/src/google/protobuf/descriptor.h#L375-L403)

My guess would be the C++ api is falling short because it only lists the ones that that runtime had to special case (for JSON or something like that).  At the moment, we try to keep the descriptor apis in sync with the C++, so it probably makes sense to open an issue upstream about why their documentation and this information don't match.

As far as generating imports, can't you just do what the Swift generator does and use `SwiftProtobufInfo.isBundledProto(file:)` to see if the file would covered by the main runtime (and import that) vs. something you need to generate an import for?

**Comment by thomasvl** [comment]
ps - while looping over the `Descriptor`'s `dependencies`, check if it is _bundled_ and generate the runtime import instead of the module mapping import.  i.e. adapt [this plugin code](https://github.com/apple/swift-protobuf/blob/952160b58bcd97dd6dac66356d60a71dffeb081b/Sources/protoc-gen-swift/Descriptor%2BExtensions.swift#L89-L106)
