### ISSUE TITLE
how can i use swift-protobuf to generate a swift class, not struct

### ISSUE THREAD

**Issue by cgwangding** [apple/swift-protobuf#194]
I want to use swift class, but i don't know how can i do.

**Comment by mohpor** [comment]
Hi,
This seems to be a valid request.
In my use case, I need to make my `message` exports, conform to a protocol which of NSObjectProtocol. Unfortunately, structs cannot do that!

**Comment by thomasvl** [comment]
So that's actually a huge change because the objects would no longer be value types, so it likely changes just about everything about how the library works.

Out of curiosity, why do you want the to be reference types instead?  What are you after?

**Comment by mohpor** [comment]
I'm trying to use my messages in [IGListKit](https://github.com/Instagram/IGListKit) and for that, I need my messages to be `ListDiffable`.
Since yesterday, I have accomplished what I was trying to do by Boxing my messages inside an object, but it seems kind of interesting to me that such simple requirement could not be met by the decision that the team made and made messages Value Type. I mean, if you are going to use protocols everywhere, why not implementig it in such a way to support both types. and when in doubt, I use `Class` just to make sure it is forwad compatible. I know I'm out of depth here, but this is not the right way to do this.

**Comment by allevato** [comment]
Value types and reference types in Swift have significant enough differences that even with the protocol abstractions, it's highly unlikely that allowing users to swap out `struct` for `class` in the generation would be a simple task—it would require a lot of engineering work.

Even _if_ we wanted to support that, it would spawn a number of other issues:

* Users of Swift protos coming from other frameworks/modules would have to be aware of whether they were generated as `struct`s or `class`es, because that decision has effects on performance and on usage (mutability, for one example).
* How would generated messages across different frameworks/modules interact? If framework A and B both have protos, and A wants to depend on B, does A have to be generated with the same value/reference nature as B? If they could be different, we'd have to ensure that every message `struct` could nest a `class` and vice versa, and behave correctly in all cases.
* Similarly, the runtime library is currently implemented with the assumption that messages are value types and that copying is achieved by simple value assignment. Classes would drop that assumption and creating copies would require explicit cloning support, complicating the message API.

Essentially, supporting both models is a great deal of work for very little gain and it's in direct opposition to one of the main goals of this project, which is to generate natural Swift value types that have all the mutability and safety guarantees that the language provides. Swift in general is modeled to push users toward value types instead of classes when possible, and generating messages as classes would move us in the wrong direction.

Unfortunately, the problem you're running into is because you're trying to use an Objective-C framework which—even though it supports Swift—has limits that come with that bridging, and this problem would be a problem with *any* value types in that context, not just Swift protobufs.

As you've already mentioned, boxing is the better answer here, and [an issue on their project](https://github.com/Instagram/IGListKit/issues/35#issuecomment-277503724) shows a reüsable box class that would work for Swift protobufs and any other value type you throw at it.

**Comment by tbkka** [comment]
If you're using an Obj-C framework and need classes that work with that, have you tried using Obj-C protobuf?  (Google's main protobuf project supports Obj-C.)
