### ISSUE TITLE
Look into failing conformance tests

### ISSUE THREAD

**Issue by thomasvl** [apple/swift-protobuf#222]
PR #220 ended up needing some conformance tests to be tagged as failing, likely want all those passing for 1.0 Release.

**Comment by tbkka** [comment]
More detail:  Six tests were having issues:

`Required.ProtobufInput.ValidDataRepeated.DOUBLE.JsonOutput`:  The conformance tester is complaining that it cannot parse the following, but I don't understand why (it looks correct to me):
```
"{\"repeatedDouble\":[0.1,1.79769313486232e+308,2.2250738585072e-308]}"
```

`Required.ProtobufInput.RepeatedScalarSelectsLast.DOUBLE.JsonOutput`:  The conformance tester is complaining that 2.2250738585072e-308 (in our JSON formatted response) is not equal to the expected value 2.2250738585072014e-308.  I suspect that the conformance tester should accept this as a pass.

`Required.JsonInput.AnyNested.JsonOutput` and `Required.JsonInput.AnyNested.ProtobufOutput`:  I have fixes for these in PR #243.

`Recommended.JsonInput.BoolFieldDoubleQuotedTrue` and `Recommended.JsonInput.BoolFieldDoubleQuotedFalse`:  Our JSON parser currently accepts `"true"` and `"false"` (quoted) as synonyms for `true` and `false` in all cases.  This could be fixed by adding a flag so the boolean parser could know whether it was currently parsing a map key or not.

**Comment by thomasvl** [comment]
re - 2.2250738585072e-308 vs 2.2250738585072014e-308 - They aren't actually the same.  Are we losing precision some place?

**Comment by tbkka** [comment]
PR #243 now includes fixes for the two `Recommended` failures as well.

**Comment by thomasvl** [comment]
More failures:`Required.JsonInput.DurationMaxValue.JsonOutput` and `Required.JsonInput.DurationMinValue.JsonOutput`.  Recording them in https://github.com/apple/swift-protobuf/pull/266.

@cburrows - fyi, incase this came out of the recent changes in there.

**Comment by allevato** [comment]
AFAIK they were broken before @cburrows' change was merged.

I remember having all conformance tests pass after I did my original JSON decoder overhaul a while back, so I wonder if some of Tim's changes since then caused floating point literals to be parsed or encoded differently.

**Comment by tbkka** [comment]
I fixed the Duration breakage in PR #273.

**Comment by cburrows** [comment]
Thanks @tbkka, sorry about that. I commented there.

**Comment by cburrows** [comment]
Also I just learned about 'make test-conformance' so that's good.

**Comment by thomasvl** [comment]
@cburrows `make check` before you send out the PR, it runs all the unit tests, the conformance tests, and validates the Sources in Reference to ensure they are up to date/match.

**Comment by thomasvl** [comment]
Took a quick look, and there's a few things I noticed -

`Required.ProtobufInput.RepeatedScalarSelectsLast.DOUBLE.JsonOutput` is failing saying:

> Output was not equivalent to reference message ... 2.2250738585072014e-308 -> 2.2250738585072e-308


`JSONEncoder.putDoubleValue` has a comment about needing to do better about picking significant digits.  That actually appears to be the problem here.

While looking at `JSONEncoder.putDoubleValue`, when we go down the `Int64(safely:)` code path, we directly call `appendInt(value:)` that won't ever quote the string, so if the number was really big, that could be a problem for the receiver if they needed it as a string.

`Required.ProtobufInput.ValidDataRepeated.DOUBLE.JsonOutput` actually fails with:

> JSON output we received from test was unparseable

It isn't immediately obvious why the C++ isn't parsing our reply, but even it if was, the problem above with precision would likely still make the test fail.

**Comment by tbkka** [comment]
> ... when we go down the Int64(safely:) code path, we directly call appendInt(value:) that won't ever quote the string, so if the number was really big ...

In this case, we know it will never be too big for a double (since it started out as a double).

**Comment by thomasvl** [comment]
> In this case, we know it will never be too big for a double (since it started out as a double).

I don't think it has anything to do with being a double, the issue if JSON types on the wire.  It goes on the wire just as `###`, i.e. - the raw 64bit number.  Since the [JSON Mapping](https://developers.google.com/protocol-buffers/docs/proto3#json) says `int64`, `fixed64`, `uint64` all go out as strings; wouldn't this also run into the risk of JavaScripts 53bit of precision so it needs to be quoted if it is too big?

**Comment by tbkka** [comment]
The JSON mapping requires double for values that are 64-bit integers in memory and therefore cannot be accurately represented as Double (which is what many JSON parsers use for numbers).

This number started as a double in memory, so it should round-trip to a double.

If you think I'm wrong, we can add quotes to this path, or we can take the performance hit and write it as a Double.

**Comment by thomasvl** [comment]
Trying to trace the C++ double handling, [JsonObjectWriter::RenderDouble()](https://github.com/google/protobuf/blob/master/src/google/protobuf/util/internal/json_objectwriter.cc#L115-L123) seems like it goes down the first path (`MathLimits<double>::IsFinite(value)` would be true), so we end up in [SimpleDtoa()](https://github.com/google/protobuf/blob/master/src/google/protobuf/stubs/strutil.cc#L1215-L1218), which would be [DoubleToBuffer()](https://github.com/google/protobuf/blob/master/src/google/protobuf/stubs/strutil.cc#L1258-L1300).  So it doesn't seem to ever quote the number, but it also seems like it comes down to when `snprintf` will/won't include a decimal point to avoid the javascript issues with large integers.

@tbkka is that right same code path you were tracing?

**Comment by tbkka** [comment]
I think there are two unrelated questions in this discussion:

1. The difference between 2.2250738585072e-308 and 2.2250738585072014e-308 boils down to Swift using a different strategy for picking the number of digits to use when formatting a double than the conformance test expects.  My comment was inspired by the [lengthy comment block just before the implementation of  `SimpleDtoa`](https://github.com/google/protobuf/blob/master/src/google/protobuf/stubs/strutil.cc#L1174), which discusses strategies for printing floating-point numbers with the minimum number of digits needed to preserve accuracy.  We could implement the same strategy as `DoubleToBuffer` by calling libc's `snprintf` in the same way.

2.  As for the question of quoting when we use `appendInt64` to print out a proto `double`, the simplest solution would be to only use `appendInt64` for numbers with magnitude smaller than 2^53.  That would avoid any "javascript issues with large integers" while maintaining a fast path for small doubles that don't require a decimal point.

**Comment by thomasvl** [comment]
For 2, I'm not so sure quoting is needed now, tracing that c++ code path mentioned, I'm not so sure how often the C++ writes out integer values vs. going to exponent notation which forces them to be doubles.

**Comment by tbkka** [comment]
I think I've traced the second failure to a JSON precision difference as well:

Our JSON is generating
```
    1.79769313486232e+308
```
but the C++ conformance test is expecting
```
    1.7976931348623157e+308
```
In this case, I think it's being considered "unparseable" because the text we're emitting is rounded up and the C++ code is exceeding the maximum double value while trying to parse it.

I also dug through the C++ code for formatting doubles a little more carefully.  Stripped to essentials, the C++ code is doing this:
* Format a double with 15 digits (from the C macro `DBL_DIG`)
* Parse the result back again
* If they don't match exactly, format again with 17 digits (`DBL_DIG + 2`)
The assumption here seems to be that 17 digits is always enough.  I suspect that simply formatting to 17 digits always would work almost as well well (with the small penalty of adding a couple of characters to each double).

This also implies that our Float encoder can't just widen to Double -- it will need to use separate formatting to use either 6 (`FLT_DIG`) or 8 (`FLT_DIG + 2`) digits as necessary.

**Comment by thomasvl** [comment]
Looks like that last PR got the rest of these, so fixing it.
