### ISSUE TITLE
Decided what to do with ProtobufRawMessage

### ISSUE THREAD

**Issue by thomasvl** [apple/swift-protobuf#23]
It seems to currently have a bunch of TODOs.  So should it be completed, or should something else take it's place?

If we have a CodedInputStream type class, the same type of parsing is pretty easy to implement oneself.

Likewise, if a developer did a proto2 syntax file with a message having no fields, it would work to parse everything into the unknowns and that could be used for the same type of functionality.

Anyway, before it becomes part of a 1.0 release that has to be maintained, decide what it should be.

**Comment by tbkka** [comment]
This was motivated by a particular use case that is extremely memory-constrained and has to handle a very large number of message types.  An initial implementation with generated code was far too large, a subsequent attempt using C++ descriptor-based dynamic messages was also a disaster due to the overhead for expanding even a single descriptor at a time.  Stream-based parsing might work, but in this particular use case the message is already a block of data in memory so we might be able to do slightly better.

Deleting it for 1.0 would be entirely reasonable.

**Comment by thomasvl** [comment]
The memory comment is interesting; since it seems to still keep everything in a map in memory. I guess the difference is the submessages (if they aren't done as a group), they would be length delimited blobs, so I guess that's the memory expansion you mention.  The empty message approach should model that memory footprint.

**Comment by tbkka** [comment]
>  since it seems to still keep everything in a map in memory

That's a bug, actually.
