### ISSUE TITLE
Avoid naming conflicts

### ISSUE THREAD

**Issue by thomasvl** [apple/swift-protobuf#259]
This somewhat overlaps with #40 (validate reserved words), #12 (revisit public names), and #109 (struct for metadata).

In addition to ensuring the library uses the naming we want and don't steal too many names from the Message field, enum name, etc. namespace; there's another catch.  In cases like proto2 syntax message fields, the get/set for the variable uses the expected field name, but we use a private variable for the storage that gets a leading underscore.  That likely means atleast on message all properties that are `_[a-zA-Z0-9]+` are also usable by the generated code (exact details being specific to the generator logic).  So the generated details where we have simply put an underscore on the front are likely not safe; they all should probably have `_protobuf` or `_protoc` on the front, or we should use a trailing `_` marker instead.

**Comment by thomasvl** [comment]
Some of our functions might also be stealing from the field/enum namespace.  If the function takes no named arguments (`func foo(_ blah: String)`), doesn't that collide with a field of `foo` trying to be added to the message?

**Comment by thomasvl** [comment]
@tbkka what was the original intent for when to use `_protoc_` vs. `_protobuf_` for naming things?  We have a mix, but I'm not sure we've been consistent in the naming.

Especially as we look to move more _private but public_ things to have a leading underscore, I'm thinking some of these actually are exposed to be hooked (as we do in a few WKTs), so they already violate the leading underscore rule.

**Comment by tbkka** [comment]
I used `_protoc_generated_` for functions whose implementation was written by the code generator.  These are proxied by non-prefixed versions in protocols so that people can override them.  (For example, `traverse` is by default just a facade for `_protoc_generated_traverse`.)  In particular, people have specifically asked that it be easy to override `debugDescription`, equality, and hash.

I recently started using `_protobuf_` for _private but public_ implementation details but I'd also be happy to just use a plain underscore in this case.

One odd trivia:  field accessors need to not be prefixed in the generated struct, but I had prefixed them with `_`  in the storage class as that was the easiest way to avoid any naming conflicts there.

**Comment by thomasvl** [comment]
Ok, converging from the other PRs and comments here:

* `_*` for all type (protocol, struct, class) names that is `public` because the generated code need to reference it but we don't want to be a _public_ api folks should rely on.
* `_protobuf_*` for any property or function that is `public` because the generated code need to call it.
* `_protobuf_generated_*` for anything that should be generated.

That last one is a change from `_protoc_generated_` but it reuses the idea that `_protobuf_*` are impl details and off limits.

**Comment by tbkka** [comment]
That sounds like a good way to unify things.

FWIW, I'm happy having Decoder, Visitor, the FieldTypes and associated generics for Maps and Extensions be "supported API."  That should cover everything that people will need if they want to connect their own serialization or deserialization to our generated code.

**Comment by thomasvl** [comment]
@allevato and I were just wondering the other day if we wanted to support that.  😄   Ok, as I do the other cleanup I'll leave them and the traverse method as _public_ (no underscore) for now.

**Comment by allevato** [comment]
Supporting custom visitors as a public API kind of makes sense, because there's more that you can do with those than just serialization once you have the data already in memory. I've been less enthusiastic about the idea of supporting custom decoders—I'll go back to the point I've made before that we're designing an implementation of *protocol buffers*, not a general purpose data-transfer library that anyone should be able to hook custom formats into. Letting users write those seems like less of a value.

But, with that being said, due to the lack of proper reflection and not exposing the descriptors in our implementation, and the fact that the protocols have to be public anyway for implementation reasons, there's probably not that much harm in leaving them supported. I'm not crazy about the size of the API surface for visitors/decoders (all the various non-optional/optional/array methods for each type), but we don't really have a better solution in the short term.

So, SGTM after minor hesitation. 😄

**Comment by tbkka** [comment]
The interesting application for custom decoders is actually not decoding per se.  In its current form, the decode API is useful for querying and/or modifying individual fields programmatically by number, as opposed to the traversal API that allows you to enumerate the contents of all non-empty fields in bulk.

For example, I think the API supports all of the following, though I've not actually tried to implement any of these yet:
* FieldMask should be able to use the traversal API to discover what fields are currently set that need to be masked and the decoder API to actually clear those fields.
* If we wanted to implement equality as a generic operation (as C++ does to reduce code size), I think you can do it by traversing one of the objects, and using the decode API to query the corresponding fields in the other object.
* It might be possible to produce a Type description for a message from our current visitor and decoder methods, though it would be a little involved: The name map lists all the field numbers and names, the decoder API can use that to set values on those fields, and once those values are set, the traversal mechanism provides detailed schema information for every field.

**Comment by thomasvl** [comment]
Closing this out, as I think we've gotten all of these.
