### ISSUE TITLE
Should most uses of `ExtensionSet` change to a protocol

### ISSUE THREAD

**Issue by thomasvl** [apple/swift-protobuf#293]
This is something I've been looking at doing to for ObjC, so capturing it for discussion before our 1.0 API locks us down for a while.

The current api around decoding messages directly uses `ExtensionSet`, but should it use a protocol instead (say `ExtensionResolver`?)?  The idea being this protocol would just have the methods needed to look up `Extensions`.

The generation would still make the helper `ExtensionSet`s they do now, but it would allow a developer to write a custom resolver that could be a giant switch, cascade of if/else, etc. where they hard cold all of the extension their app needs.  There by removing the startup time for building the `ExtensionSet` and potentially having better lookup time for resolving extensions.

**Comment by tbkka** [comment]
@thomasvl: I have a working rough implementation of this idea; it was pretty simple.  Most interestingly, it did not touch the generated code, though I did have to jigger a few public APIs to accept the new protocol instead of the struct type.

I like that this opens up options for us to explore post-1.0.  In particular, the current `ExtensionSet` lookup code is a little hampered by the fact that types are not Hashable, which leads us to walk lists of types to try to find matches.   With this in place, we could explore having the code generator emit tailored implementations of the protocol instead.  That might be a big improvement.

@allevato:  Any ideas about naming?  My current code uses `ExtensionCollection` for the protocol and `ExtensionSet` for the concrete implementation.  Maybe you have a better idea?

**Comment by tbkka** [comment]
After thinking about it overnight, I'm going with `ExtensionMap` for the protocol (since the protocol just has methods for looking up extension objects given the message being extended and the field number), and `SimpleExtensionMap` for the current implementation.

**Comment by tbkka** [comment]
Closed via #406
