### ISSUE TITLE
Unknown fields include fields with wrong wire type

### ISSUE THREAD

**Issue by thomasvl** [apple/swift-protobuf#342]
Not really covered in the protobuf docs, but you can find it in the code for other languages - If a field number on the wire is the wrong wire type, it should get sent into unknown fields instead of failing the decode.

The C++ is likely easiest to spot this as the decode is done via tag (field number + wire type) -

- Decoding a field number checks the tag - https://github.com/google/protobuf/blob/master/src/google/protobuf/descriptor.pb.cc#L1006-L1008
- Ends up in the `handle_unusual` case, where `SkipField()` pushes it into unused - https://github.com/google/protobuf/blob/master/src/google/protobuf/descriptor.pb.cc#L1020-L1028

**Comment by tbkka** [comment]
> ...but you can find it in the code for other languages...

Hmmm...  Based on some comments on the protobuf mailing list, I thought that the Go version also considered mismatched wire type to be a fatal error, though I've not looked carefully.

(Personally, I prefer the error in this case, since I've been bitten a few times by overly-lenient parsers; but I will defer to the group consensus on this.)

**Comment by thomasvl** [comment]
I haven't looked at the go code, but I think the issue will be we need to be able to parse anything parsable on other languages.
