### ISSUE TITLE
Generated message members should be reördered to best expose what users are interested in

### ISSUE THREAD

**Issue by allevato** [apple/swift-protobuf#35]
Folks who use generated protos are likely going to want to open those up to see what properties are available (specifically, how the fields in their messages map to properties in Swift).

The code generator should put the stuff of highest user interest at the top—properties, which have simple enough implementations that they don't really get in the way, and then nested types—and put all the generated implementation details further down, out of the user's way.

Another interesting idea would be to move the generated implementation details into an extension deeper in the file, bubbling as much of the "interface" of the generated messages to the top as possible. Some things can't be done this way (specifically, stored properties cannot be put in extensions), but we could do a fairly good job of segregating what users care about from the things only the runtime needs to know.

**Comment by tbkka** [comment]
Great point:  Readability counts, even for generated code.

**Comment by thomasvl** [comment]
Ok, formatting question, give:

```protobuf
message Msg {
  int32 field1 = 1;
  message SubMsg {
    string name = 1;
  }
  SubMsg field2 = 2;
  enum SubEnum {
    NONE = 0;
    FOO = 1;
  }
  SubEnum field3 = 3;
}
```

How do we want the generated code to look?

_A_
```swift
struct Msg {
  enum SubEnum {
    case NONE
    case FOO
  }
  struct SubMsg {
    var name: String
  }
  var field1: Int32
  var field2: SubMsg
  var field3: SubEnum
}
```

_B_
```swift
struct Msg {
  var field1: Int32
  var field2: SubMsg
  var field3: SubEnum
  enum SubEnum {
    case NONE
    case FOO
  }
  struct SubMsg {
    var name: String
  }
}
```

_C_
```swift
struct Msg {
  var field1: Int32
  var field2: SubMsg
  var field3: SubEnum
}

extension Msg {
  enum SubEnum {
    case NONE
    case FOO
  }
  struct SubMsg {
    var name: String
  }
}
```

Or something else?

@tbkka @allevato

**Comment by allevato** [comment]
My thoughts (with no obvious winner):

* My preferred personal style in general is to put nested types at the top of their parent's scope, before any properties/initializers/methods. However, for the proto case where the code isn't being written by the user, I can see the value of pushing them to the bottom so that the first thing the user sees after the struct header is the meat of *that* type.

* The extension approach has the benefit of letting us push deeply nested things to the left, because we can do this:

```swift
extension Msg.SubMsg.SubSubMsg {
  struct SubSubSubMsg {
  }
  enum SubSubSubEnum {
  }
}
```

But, it might not be obvious to users that there's more stuff outside the *primary* body of the class.

We also need to make sure that we use `private` vs `fileprivate` correctly if we switched to extensions, because the proposal to get rid of scoped `private` and revert `fileprivate` to `private` was just rejected (grumble), so moving things into an extension means that `private` no longer spans extensions. (I don't think that's a concern here, though, because the messages and enums are public/internal anyway.)

**Comment by thomasvl** [comment]
Oh, and when there are fields in a _oneof_, where should the enum we generate for the oneof go?

**Comment by allevato** [comment]
Considering that `oneof`s are inextricably linked to the fields in the message that they represent, I think *those* at least should clearly go in the message, not in an extension (if we end up even going down that path). It feels like those should go at the bottom—they're more a detail than a "type".

**Comment by thomasvl** [comment]
re `oneof`, the only part i'm torn on is how much do we hope developers use that accessor instead of the direct fields.  i.e. - do we want to do anything to encourage that usage?

**Comment by tbkka** [comment]
I don't think we want to actively _discourage_ direct use of the oneof enum, since it is a key feature:

* People need to switch on that enum to rapidly determine which of (possibly many) fields are set.

* Direct access to the oneof enum is required to use the following proto3 idiom, which allows people to track field presence in proto3 messages:
```
    oneof optionalFoo {
      int32 foo = 17;
    }
```

**Comment by tbkka** [comment]
I think @thomasvl's recent work has addressed the bulk of this.  Any reason to leave this open?

**Comment by thomasvl** [comment]
There's an open question to you and Tony (Apr 6th) about some last ordering.  Tony made some comments, but hasn't really cast a vote/opinion.

That's likely the last thing I'd like to really nail down until something specific comes up.

**Comment by tbkka** [comment]
I haven't really weighed in because I don't have a very strong opinion on this.  But since you asked...

For code I write by hand, I tend to prefer your option `A` with the types at the top, but I think in this case, I have a mild preference for `B`.  Option `B` seems to more clearly express the structure of this type.   I'm less in favor of your option `C` since the nested structs and enums are typically required as types for the fields.  I think of Swift extensions as tools for specifying independent features (I think it makes a lot of sense for the JSON/text naming data, for instance, or for proto extensions).

**Comment by allevato** [comment]
I think I'm essentially in agreement, for the same reasons. In my own code I would put nested types at the top, but I think for protos, it feels better to have the fields front-and-center.

There's also option `D`: generate fields and nested messages in the same order they occur in the `.proto` file, without grouping/resorting them in any other way. 😨

**Comment by thomasvl** [comment]
Re: D - The descriptor objects don't actually really capture that. It might be findable via the _google.protobuf.SourceCodeInfo.Location_ info since that has file line/column references; but protoc might leave them off if there was no comments to capture.  So yea, I'm not gonna be trying to use that…  😝 

Ok, sounds like we're all sorta in the same state; and that's what we currently generate.  👍 

I keep debating if `isInitialized` should move to the extension since it is a type specific override and we provide a default.

Likewise, `decodeMessage` and `traverse` could move to the Extension just to shorten what folks read, but they really are required for conformance to `Message`, so keeping them up top when declaring the `struct` seems correct.

So…

Closing this out until we get feedback suggesting changes.
