### ISSUE TITLE
Validate ReservedWords.swift

### ISSUE THREAD

**Issue by thomasvl** [apple/swift-protobuf#40]
Taking a quick peek, it seems like some of the lists include system reserved and some include things the library itself uses.  Might make sense to document which are which, and see if we can come up with a way to harvest the ones reserved because the library uses them directly from the protocols so we ensure they stay up to date (for example, does `isEmpty` still belong in the lists?).

**Comment by tbkka** [comment]
Finding a clean way to document this list would be good.

`isEmpty` certainly does not belong.

It would also be good to find ways to reduce the number of reserved names.  For example, I've considered moving `protoPackageName` and related metadata into a sub-struct.

**Comment by thomasvl** [comment]
Capturing while I think of it: Can we use the Mirror within the plugin to avoid manually building all of the lists?  Inspect some of the proto classes the plugin, collecting their properties and then filter the list to remove the properties added by the proto definition (`protoFieldNames`). That might help remove some of the manual collection of names.

**Comment by tbkka** [comment]
There's the complication that Swift Protobuf currently overrides the standard reflection (so that the presence or absence of the storage class is invisible to clients).  We could work around that, of course, but it still wouldn't work because:

Swift 3 reflection does not (yet) enumerate methods or computed properties, only stored properties.

When/if that changes, we can certainly investigate this approach.  It's a good idea.

**Comment by thomasvl** [comment]
@tbkka I don't suppose you have any info we can add to the file on how those lists were built?  I'm guessing it comes somewhat from the [Keywords and Punctuation](Rehttps://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/LexicalStructure.html#//apple_ref/doc/uid/TP40014097-CH30-ID413) section of the language.

**Comment by tbkka** [comment]
The original lists were ad hoc copies from another protobuf implementation.  As such, they're actually a mix of C++, Obj-C, and Swift keywords.  (ugh)  They need to be compared to the Keywords and Punctuation section of the Swift spec.

**Comment by thomasvl** [comment]
Will work on this once I finish out the other name changes/visibility changes so we can collect the names the library will use/add to the Enum and Message namespaces.

**Comment by thomasvl** [comment]
Hand off this since it look @tbkka is getting to it before me.

**Comment by tbkka** [comment]
PR #410 made some progress on this.  The lists of Swift keywords and names that we avoid are now derived from lists that directly follow the Swift language spec.

Next step:  systematize the handling and testing of names that cannot be used as generated identifiers because SwiftProtobuf uses them for other purposes.

**Comment by tbkka** [comment]
Closed via #460.
