### ISSUE TITLE
Initializers are private

### ISSUE THREAD

**Issue by davidmuzi** [apple/swift-protobuf#424]
Documentation states that the generated structs will have [public initializers](https://github.com/apple/swift-protobuf/blob/master/Documentation/API.md#message-api), which would be required when attempting to instantiate messages within a module, but they are private.

**Comment by allevato** [comment]
Are you referring to the convenience initializers that take fields as arguments? Those have been removed; only the parameterless initializer remains.

Unfortunately the documentation that you linked to has become very out of date; I just filed #425 to track fixing it up.

To initialize a message you have a couple approaches:

1. Create a new one as a `var` and then set its fields:

```swift
var foo = MyGeneratedMessage()
foo.someField = 5
foo.someOtherField = "hello"
```

...but if you're picky about your mutable/immutable state, you may not want to have a `var` hanging around longer than you need it.

2. Use the static `with` factory method on all message types which captures the initialization in a block so that the finished message can be stored in a `let`:

```swift
let foo = MyGeneratedMessage.with {
  $0.someField = 5
  $0.someOtherField = "hello"
}

**Comment by Meonardo** [comment]
@davidmuzi Hi, can you find the Deserialization method? `init(protobuf: Data) throws`, I m using 0.9.901

**Comment by allevato** [comment]
`init(protobuf: Data) throws` has been renamed to `init(serializedData: Data) throws` in the recent versions.

**Comment by Bartzy** [comment]
Apologies for bringing this issue up again, but why initializers with fields as arguments were removed, and instead we have the `with` static method alternative? It seems to me that initializers are more idiomatic Swift code.

Thanks!

**Comment by thomasvl** [comment]
We remove them for a few reasons: code bloat, proto evolution (as the proto changes with time (fields added, etc.), it can break code as the order of the fields to the initializer could change, etc.

**Comment by Bartzy** [comment]
@thomasvl Thanks for the answer.

But without an initializer, I think one can just define an invalid message? Or is it always with default values and hence allowed?

**Comment by thomasvl** [comment]
There is always a [`init()`](https://github.com/apple/swift-protobuf/blob/master/Sources/SwiftProtobuf/Message.swift#L39).

Protobuf defines all message fields to have their default value unless you set them to something else.  So the message is always valid from that pov.
