### ISSUE TITLE
Very large binary size

### ISSUE THREAD

**Issue by soffes** [apple/swift-protobuf#45]
The compiled framework for the SwiftProtobuf.framework is over 30MB. Any ideas on how to reduce that? I really want to use protobufs, but spending 30MB of my App Store download budget seems like a steep cost.

**Comment by tbkka** [comment]
If you have time to experiment, it would be interesting to see what happens if you statically link that framework.  Odds are, you're only using a tiny part of that framework and static linking might pull in less than you think.

You might also ask on one of the Swift language forums what ideas they might have; I suspect a lot of people have this same problem.

Long-term, I think we can probably improve that a lot, but I don't have a great answer today.

**Comment by soffes** [comment]
Fair enough! I was mostly curious if it was on your radar.

Thanks for the advice!

**Comment by tbkka** [comment]
Hmmm....   According to @allevato's comment in Issue #65, the dylib itself is only 3MB.  I'm curious whether we're including unnecessary stuff in the framework.

**Comment by allevato** [comment]
I'd be interested to know where the 30MB is coming from as well. On my system, the macOS framework is 4.4MB and the iOS framework is 8.2MB. (Both numbers are for the fat binary with all architectures.)

We still need to trim that down by a *lot*, but 30MB sounds like something else is very wrong.

**Comment by thomasvl** [comment]
My guess would be debug and symbols haven't been stripped.  When I was working on cleaning up the project I noticed some setting like that.  I'm working on #57 again, but doing it in smaller chunks, so I'll revisit debug symbols while I'm in there.

**Comment by soffes** [comment]
Ya, this had bitcode and full debug info. Sorry about that. Thanks for the follow up!
