### ISSUE TITLE
Investigate static values for field defaults

### ISSUE THREAD

**Issue by thomasvl** [apple/swift-protobuf#457]
The getters for proto2 syntax creates `Data()`, strings, and message instances for when the value wasn't set.  It might make sense for some of these to have a static single instance that we use so the creation doesn't have to happen.

**Comment by tbkka** [comment]
A few random thoughts:

* The obvious implementation would add a `staticInstance` to messages and use that to initialize fields.  But that creates another API connection between separately-generated messages that I'd like to avoid.

* For message instances, could we somehow have the default initializer hide the optimization?
```
    public init() {
        self = Self.staticInstance
    }
```
I don't think the above literally works (the private `staticInstance` has to be built somehow), but maybe there's a way to game this.

* Of course, maybe the compiler is already smart enough to do the above for us?

* A static Data() instance could be exposed from the library somewhere?  Or as a single `fileprivate` at the top or bottom of any generated file that needed it?

* I hadn't thought about strings.  I had always assumed that `""` was very fast, but I've not actually measured it.

Obviously, any of the above would want some perf testing to see if it was actually faster.

**Comment by allevato** [comment]
So it turns out the `Data` value type overlay in Swift is... pretty dumb. And `String` has some weird edges too. (I smell some pull requests!)

In the macOS implementations of Foundation, asking for an empty `NSData` or `NSString` always returns the same singleton object; that makes sense because it's always immutable. But in Swift, I've observed the following:

* `Data` doesn't do anything special for the empty case—`let d = Data()` always ends up `malloc`ing a zero-length buffer. However, `let d2 = d` has them both share the same buffer until one is mutated, as we'd expect.

* `let s = ""` (i.e., specifically creating a string from the empty literal) always allocates a new `_StringCore` with a zero-length buffer. *However,* `String()` always creates instances that share the *same* empty storage. This is presumably because they go through different initializers, and the one that initializes from a literal doesn't handle the zero-length special case. Probably an oversight.

* Arrays and dictionaries don't have this problem: when initialized empty, they always share a common empty storage.

So, we potentially have some performance gains if we manage our own empty `Data` singleton until the language fixes that for us. Then, here's what else we can do:

* For messages without heap storage: nothing. Copying a static empty instance of the message isn't going to be any faster than creating a new one.
* For messages with heap storage: instead of creating a static *message*, we create an empty *storage instance* for each message and assign that inside `init()`. That avoids heap allocation entirely for new messages and instead makes it happen only on an as-needed basis (i.e., first mutation). Our existing `ensureUnique` will work here because there will always be at least one reference to the empty storage—the static one—so it will never be unique and thus always reällocated on mutation.

Since I've done the investigation, I can take a look at this today. I'll update the performance harness first to add a `TestAllTypes`-like message with some nested messages, and then I'll add a measurement for allocating a lot of empty messages as well, so we can get measurements now vs. with these described enhancements.

**Comment by thomasvl** [comment]
Actually, there is an interesting sub case here.  If a `string` or `bytes` field that  has a default, do we construct it every time in the field's getter?  Should that also use a static?

**Comment by tbkka** [comment]
@allevato:  Nice work tracking that down!  I'd noticed the `Data()` overhead in some of my other tests; I think I may have put in a few `Optional<Data>` at various points specifically to avoid it.  But initializing from a shared static would be even better.

I think it would be possible to do this without changing the library/generated code API.  It would just require putting new `private` statics in the library for the library to use and emitting `private` statics into the generated code for it to use.  That would allow us to change this on either side in the future without any impact.  (Though the cost of exposing a couple of public statics from the library is pretty low.  This is mostly a thought experiment to help me start thinking in terms of API stability.)

**Comment by allevato** [comment]
> Actually, there is an interesting sub case here. If a string or bytes field that has a default, do we construct it every time in the field's getter? Should that also use a static?

Yes, that would make sense as well. Constructing it in the getter would suffer the same problem we're seeing for empty defaults.

**Comment by allevato** [comment]
> I think it would be possible to do this without changing the library/generated code API.

Right, there's nothing that would have to change from a client's point of view here. I have a PR almost ready to go.

**Comment by thomasvl** [comment]
`MessageExtension` instances capture their default, so they are done at startup and live for the lifetime of the app.  They also need the default again when generating the Swift extension to access the fields.  So both of those could get the help of a static instance.  (fyi #502 is open to resolve the fact that they have the default twice)

**Comment by thomasvl** [comment]
I believe the last parts pending are:

1. Does having a static `defaultInstance` for messages make sense.
1. Does it make sense to have a static `default` for the `_StorageClass` so we don't have to do an alloc until and assignment.

There is some overlap between the two, but the second one has the potential to kick in every time someone writes `var foo = Msg()` as it would avoid the heap alloc until mutation happens, and if the developer reassigns `foo` instead, the alloc was avoided.

The first comes into play for how we generate the field getters (extension or regular), they basically boil down to `return value ?? Msg()` vs. `return value ?? Msg.defaultInstance`.  @allevato is doing some tests to see how smart the code get is to see if the `Msg()` is a construction and copy (to the the that called the getter) or if it gets optimized to a direct initialization.

**Comment by allevato** [comment]
It looks like the `init` version is going to win out vs. copying a default message instance. I imagine there are optimizations that Swift does in the first case that don't work out in the second.

I created some toy structs:

```swift
public struct Foo {
  public static let defaultInstance = Foo()
  public var f1: Int = 0x1234
  public var f2: Int = 0x5678
  public var f3: String = "abcd"
  public var f4: String = "wxyz"

  public init() {}
}

public struct BarNoDefault {
  public var foo: Foo {
    return Foo()
  }

  public init() {}
}

public struct BarWithDefault {
  public var foo: Foo {
    return Foo.defaultInstance
  }

  public init() {}
}
```

The `foo` getter for `BarNoDefault` looks like this:

```
                     __TFV9smartcopy12BarNoDefaultg3fooVS_3Foo:        // smartcopy.BarNoDefault.foo.getter : smartcopy.Foo
00000001000019c0         push       rbp                                         ; CODE XREF=__TFV9smartcopy3FooCfT_S0_+9
00000001000019c1         mov        rbp, rsp
00000001000019c4         movaps     xmm0, xmmword [0x1000046c0]
00000001000019cb         movups     xmmword [rdi], xmm0
00000001000019ce         lea        rax, qword [0x1000047d0]                    ; "abcd"
00000001000019d5         movq       xmm0, rax
00000001000019da         mov        eax, 0x4
00000001000019df         movq       xmm1, rax
00000001000019e4         punpcklqdq xmm0, xmm1
00000001000019e8         movdqu     xmmword [rdi+0x10], xmm0
00000001000019ed         lea        rax, qword [0x1000047d5]                    ; "wxyz"
00000001000019f4         movq       xmm0, rax
00000001000019f9         pslldq     xmm0, 0x8
00000001000019fe         movdqu     xmmword [rdi+0x20], xmm0
0000000100001a03         movdqu     xmmword [rdi+0x30], xmm1
0000000100001a08         mov        rax, rdi
0000000100001a0b         pop        rbp
0000000100001a0c         ret
```

That's a straightforward initialization to stored properties. But there seems to be something hidden here, if it's just pushing string literals around into registers. Shouldn't it be constructing a `String` instance somewhere?

...while the `foo` getter for `BarWithDefault` looks like this:

```
                     __TFV9smartcopy14BarWithDefaultg3fooVS_3Foo:        // smartcopy.BarWithDefault.foo.getter : smartcopy.Foo
0000000100001a20         push       rbp                                         ; CODE XREF=__TZFV9smartcopy3Foog15defaultInstanceS0_+9
0000000100001a21         mov        rbp, rsp
0000000100001a24         push       r14
0000000100001a26         push       rbx
0000000100001a27         mov        rbx, rdi
0000000100001a2a         cmp        qword [_globalinit_33_C7CCE7E54EE846E5B3481D216E4FF97E_token0], 0xffffffffffffffff
0000000100001a32         je         loc_100001a47

0000000100001a34         lea        rdi, qword [_globalinit_33_C7CCE7E54EE846E5B3481D216E4FF97E_token0]
0000000100001a3b         lea        rsi, qword [_globalinit_33_C7CCE7E54EE846E5B3481D216E4FF97E_func0]
0000000100001a42         call       imp___stubs__swift_once

                     loc_100001a47:
0000000100001a47         movaps     xmm0, xmmword [__TZvV9smartcopy3Foo15defaultInstanceS0_] ; CODE XREF=__TFV9smartcopy14BarWithDefaultg3fooVS_3Foo+18
0000000100001a4e         movaps     xmm1, xmmword [__TZvV9smartcopy3Foo15defaultInstanceS0_+16]
0000000100001a55         movaps     xmm2, xmmword [__TZvV9smartcopy3Foo15defaultInstanceS0_+32]
0000000100001a5c         movdqa     xmm3, xmmword [__TZvV9smartcopy3Foo15defaultInstanceS0_+48]
0000000100001a64         movq       rdi, xmm2                                   ; argument "instance" for method imp___stubs__swift_unknownRetain
0000000100001a69         pshufd     xmm4, xmm3, 0x4e
0000000100001a6e         movq       r14, xmm4
0000000100001a73         movups     xmmword [rbx], xmm0
0000000100001a76         movups     xmmword [rbx+0x10], xmm1
0000000100001a7a         movups     xmmword [rbx+0x20], xmm2
0000000100001a7e         movdqu     xmmword [rbx+0x30], xmm3
0000000100001a83         call       imp___stubs__swift_unknownRetain
0000000100001a88         mov        rdi, r14                                    ; argument "instance" for method imp___stubs__swift_unknownRetain
0000000100001a8b         call       imp___stubs__swift_unknownRetain
0000000100001a90         mov        rax, rbx
0000000100001a93         pop        rbx
0000000100001a94         pop        r14
0000000100001a96         pop        rbp
0000000100001a97         ret
```

The first part of that is the `dispatch_once`-style check to initialize the default on its first access, and then the rest is copying things over. Those retains make sense, because copying the two `String` properties would retain the underlying storage.

I tried measuring these and the variance is all over the place. Over multiple runs, sometimes the `defaultInstance` version wins out and sometimes the `init()` version wins out.

Without digging into this weirdness more, I think our best path forward is:

* Have messages with storage declare a default static storage instance, and the initializer for those messages just assigns that singleton to `_storage`. Then the CoW behavior does the rest when the user mutates it. This means that initializing empty messages should amount to a single retain, which should be much faster than allocating a new storage for each message.
* For messages without storage, since there's no clear winner, introducing a default *message* rather than default *storage* doesn't seem like it would provide a clear benefit.

The advantage here is that declaring a default storage is purely a generator change and not an API change.

**Comment by thomasvl** [comment]
The lack of a condition in the return seems like it could free up the compiler to figure more out

```swift
public struct BarNoDefault {
  var _foo: Foo?
  public var foo: Foo {
    return _foo ?? Foo()
  }

  public init() {}
}

public struct BarWithDefault {
  var _foo: Foo?
  public var foo: Foo {
    return _foo ?? Foo.defaultInstance
  }

  public init() {}
}```

Would be closer to what we're doing with proto fields.

**Comment by allevato** [comment]
Good point. With that change, there are some interesting optimizations in the `BarNoDefault` case (it initializes the `Foo` up-front and *then* tests the presence of `_foo`, copying its values into the new `Foo` if it was present). The `BarWithDefault` does the presence test first and looks more like what we'd "expect".

The timings across multiple runs are still all over the place though, as they were before.

**Comment by thomasvl** [comment]
So where does this leave up?  Do we say this isn't worth doing anything for defaultInstance for methods, but doing it for _StorageClass is still worth it from the POV of the heap alloc?
