### ISSUE TITLE
Exporting to json ~> All values are strings

### ISSUE THREAD

**Issue by vCrespoP** [apple/swift-protobuf#48]
Hello all.

When I export a structure to its corresponding json like:

``` 
let id: Int64 = 1
let title = "First Book"
let author = "Who knows"
let cover = Cover.paper
        
let item1 = BookInfo.init(id: id, title: title, author: author, gender: gender)
        
let json = try? item1.serializeJSON() 
````

Then when trying to fetch a value from that dictionary:
```
let idDict = item2["id"] as? Int64
```
idDict results in being nil but
```
let idDict = item2["id"] as? String
```
actually returns "1"
So if I wanted to get the value as I defined it i would always have to parse strings like:
```
let idDict = Int64(item2["id"] as? String ?? "0")
```
Which I find it quite messy, dirty and bound to fail.

All the above also applies for the enum, where I'd get: "paper", the string representation of the case inside the enum for Cover. I assume this is ok.

Options here:
- Build an extension for strings to parse whatever value from the generated dictionary (Int, Enums, ...)
- Wait to have (#46)/implement a JSON parsing method that will contain all this logic.
- Anything else?

Thanks for your time,
Vicente Crespo.

**Comment by thomasvl** [comment]
JSON mapping is a feature of the `proto3` syntax, the definition is on the protobuf docs: https://developers.google.com/protocol-buffers/docs/proto3#json

**Comment by vCrespoP** [comment]
All clear.

Thank you once again, Thomas.

**Comment by tbkka** [comment]
Could you clarify where your `item2` came from?  It sounds like you're taking the String generated by `item1.serializeJSON()` and then parsing it with some other JSON library?

@thomasvl gave you a pointer to the Google protobuf JSON coding spec.  Google defined the protobuf JSON coding to ensure that various JSON parsers would not mangle the result.  Among other things, they decided to store `Int64` as strings so that JSON parsers that don't support full 64-bit integers would not corrupt the values.

Swift Protobuf deals with this for you:  If you parse `json` with `BookInfo(json: json)`, you will see the `id` does get correctly parsed into an `Int64`.

If decoding Protobuf JSON with other JSON parsers is awkward, you should talk to the authors of those libraries about expanding their support.

**Comment by vCrespoP** [comment]
Ok, with the link Thomas provided me I understood the logic behind this.

About 'dict2' that was a mistake I inserted while writing the sample in GitHub. item2 would be json, I edit it right now.

I was trying to have a structure initialized in code, then serialize it to json, and then try to initialize another structure from that 'export' to check if they were both the same (which they should as far as I understand).

The thing is that 
```
BookInfo(json: json)
```
does not work for me (#46), not auto-completing, and if I write it, it just fails to compile, I was expecting this to work :/

**Comment by tbkka** [comment]
How are you including the `SwiftProtobuf` module in your build?

**Comment by vCrespoP** [comment]
I move to the other conversation now. Thanks tbkka

**Comment by tbkka** [comment]
Another small suggestion:

> let item1 = BookInfo.init(id: id, title: title, author: author, gender: gender)

You don't need the `.init`here:  You should be able to just write

```
   let item1 = BookInfo(id: id, title: title, author: author, gender: gender)
```
