### ISSUE TITLE
JSON parsing issues

### ISSUE THREAD

**Issue by fe9lix** [apple/swift-protobuf#481]
Hi! I've noticed a couple of issues when working with JSON decoding/encoding and existing backend services that work with JSON payloads (I'm aware that this is not the ideal setup for protobuffers). What am I missing...?

- When decoding a JSON model, a type mismatch in a single property causes the entire parsing to fail. Wouldn't it make more sense to just treat such properties as "missing" instead of throwing an error? Although a type mismatch indicates that the contract is violated, in most cases you'd still want to work with partial results and then just ignore incorrect properties or use a default value there. Same for enum cases: When your backend service sends you an enum name that is not listed in the proto file, the UNRECOGNIZED case is not trigged but instead an error is thrown and the entire parsing fails. It'd be nice if there was a less "stricter" version for decoding JSON models.

- When encoding the Swift struct back to JSON representation, the camelCased JSON names are used instead of the case that is used in the proto file. So if your backend works with snake_cased property names, you usually also want to use the snake_cased names when posting data back to the backend. jsonString(), however, can't be used then and constructing the payload properties must be manually done.

- Is there a specific reason why the native JSON parsing classes of iOS (JSONSerialization) aren't internally used for decoding/encoding?

**Comment by thomasvl** [comment]
The formatting of the field names comes from the [protobuf spec](https://developers.google.com/protocol-buffers/docs/proto3#json) for how the JSON encoding should work.  Likewise, matching the spec and other language implementations is what dictates the behaviors for type mismatches, unknown keys, etc.  For the Swift version to properly interop with other protobuf libraries we have to have the same success/failures behaviors.  The protobuf project actually includes some [conformance tests](https://github.com/google/protobuf/tree/master/conformance) to help ensure this, some of it has to be sorted out by looking at their unittests and implementation.

Using JSONSerialization would be likely be very expensive and slower.  To generate the JSON, the protobuf object would have to be converted to a `[String:Any]` (so all new objects), that would be serialized, and then thrown away.  Likewise, for parsing that intermediate object tree would get created and thrown away.

**Comment by fe9lix** [comment]
@thomasvl thanks a lot for your clarifications!

**Comment by tbkka** [comment]
> Re: JSON failure

We're reluctant to stray too far from the behavior of other protobuf implementations.  Among other constraints, it's important to us that we meet Google's "conformance test" which does require JSON decoding to fail completely in certain cases.  We might consider optional behaviors for some cases, but expect spirited discussion.  ;-)

In particular, the `UNRECOGNIZED` case carries an integer argument specifying the exact value.  For unrecognized JSON enums, we don't have any information to translate the textual JSON enum value to an integer value.  It's not infeasible to preserve this, but again, expect extended discussion when you send us your PR.  ;-)

> ...  the camelCased JSON names are used instead of the case that is used in the proto file. So if your backend works with snake_cased property names, you usually also want to use the snake_cased names ...

As @thomasvl said, this is something specified by the Google protobuf project, so we can't just change it.   You can see google/protobuf#731 for some general discussion of this.

Note that Google's specification for JSON **decoding** requires us to recognize and accept **both** forms of the name.  So the JSON decoding should actually already do what you want.

For **encoding**, we do not currently have an option that would use the `proto` names instead of the `json` names.  There is precedence for this in Google's Java implementation, as discussed in the thread mentioned above.  A pull request to add such a feature would be welcome, as long as it includes test updates.

You can already specify the names to use in JSON coding on a per-field basis.  For example, you could just repeat the `snake_case` name as follows:
```
message Foo {
   int32 field_name = 1 [json_name = "field_name"];
}
```
as an added benefit, this would ensure that any other protobuf implementation would use the same names when encoding/decoding JSON.

> Re: why we don't use `JSONSerialization`?

As @thomasvl mentioned, using JSONSerialization here would be a noticeable performance hit. This is not because JSONSerialization itself is slow (it's not), but rather because it constructs a transient intermediate form `[String:Any]` that then requires dynamic type-checking before the values can be used.  I've seen cases where a JSON decode process based on `JSONSerialization` spends 5x more time in the type-checking process than in the actual decoding.  By using schema information derived from your `proto` file to drive the decode process directly, SwiftProtobuf's JSON parser can entirely avoid both the intermediate form and the additional type-checking.

**Comment by fe9lix** [comment]
@tbkka: thanks for the details. i understand that the main goal is to stay in sync with the spec and other implementations. 
my questions just popped up when i was converting an existing model layer of a project to protobufs and initially found some behavior unexpected.

for instance, if you think of a typical mobile application that parses a JSON payload and renders a screen based on the data, causing the entire rendering to fail just because a single property is wrong seems a bit harsh in that scenario. (especially if you have to deal with existing backend services written in languages such as PHP where JSON encoding is weird to the degree that when you're expecting an object and that object is "empty", an empty array may be returned instead... – but i see that the topic of what to consider as failure is controversial ;).

thanks for your tip with defining json names in the proto file. i didn't come across this when reading the docs from Google and swift-protobuf.
