### ISSUE TITLE
IndexPath hashValue seems busted on linux

### ISSUE THREAD

**Issue by thomasvl** [apple/swift-protobuf#513]
Spun out of #508.  Comments seem to not make it into the generated sources.

**Comment by allevato** [comment]
So on Linux, [IndexPath.hashValue](https://github.com/apple/swift-corelibs-foundation/blob/d202e2e7e4deed79d88b0828f9b9dcd86e33396d/Foundation/IndexPath.swift#L144) calls `makeReference`, which creates an `NSIndexPath`. [That class](https://github.com/apple/swift-corelibs-foundation/blob/d202e2e7e4deed79d88b0828f9b9dcd86e33396d/Foundation/NSIndexPath.swift) doesn't override `isEqual` or `hash` from `NSObject`, so basically the **pointer to an arbitrary new object that's different every time you call it** gets used as the hash value.

This is mind-bogglingly dumb. 🙄 

[IndexPath.hashValue in the Swift SDK overlay](https://github.com/apple/swift/blob/ffc594bd2062bd1668a33b20941a885ceb05bd34/stdlib/public/SDK/Foundation/IndexPath.swift#L656) has some nice performance improvements that also fix this, but they haven't been copied back to corelibs-foundation yet. I'm not sure what happens when those files differ.

**Comment by thomasvl** [comment]
And that new impl of hashValue doesn't use the overflow operators, so it will choke on large values.

**Comment by tbkka** [comment]
Filed https://bugs.swift.org/browse/SR-4858
