### ISSUE TITLE
[FR] Rather than 'hasX' methods just use Swift optionals

### ISSUE THREAD

**Issue by samskiter** [apple/swift-protobuf#522]
I noticed that the Swift generated code has 'hasX' methods for fields. Could we use optionals instead to allow people to deal with the optionality safely through the compiler?

Swift developers are used to dealing with optional fields so they would be a familiar concept to have.

**Comment by allevato** [comment]
The motivation for this design choice is spelled out in more detail [here](https://github.com/apple/swift-protobuf/blob/master/Documentation/INTERNALS.md#basic-templates). Don't worry, we gave it a great deal of serious thought.

The short version of the story is (and I'm glossing over some details here), an "optional" field in protobuf is semantically different than an "optional" property in Swift—they only share a common word. In protobuf, "optional" means it doesn't have to be set to serialize/parse the message—it says nothing about its presence in memory.

Protocol buffer spec lays down the expectation that *every field has a default value* and retrieving that value when it is not set should return that value, not something that indicates whether or not it is not set. So even "optional" fields are effectively "set" to that default value until they are changed.

This distinction is especially important for proto2 syntax, where the default value can be any valid non-zero value for that field. If a field defines its default value as "42", then returning an optional `.none` would be the wrong behavior because the "value" of that field is 42 and returning `.none` makes that default inaccessible (without providing yet another method to access it).

**Comment by thomasvl** [comment]
A file that is proto3 syntax also does not create has methods for pod types, as explicit defaults are no longer allowed, and the says simply says anything set to zero does not go over the wire.

**Comment by samskiter** [comment]
> The original implementation of Swift Protobuf generated properties with Swift optional type, but that obvious approach proved problematic. In practice, testing whether a field is set is fairly uncommon and using Swift optionals directly tended to lead to abuse of the Swift ! operator in many cases where the user knew that certain fields would always be set.

Using `!` on properties is abusing but it's wrong to assume that "certain fields would always be set" and `hasX` methods just hide this from the user. Is it not also the case that Swift developers are becoming more and more sensitive to force unwrapping.

> Protocol buffer spec lays down the expectation that every field has a default value and retrieving that value when it is not set should return that value, not something that indicates whether or not it is not set. So even "optional" fields are effectively "set" to that default value until they are changed.

The protobuf spec allows *either* Nullable fields *or* `hasX` fields.

You could even provide a method to get the 'default' value for a field?

We feel quite strongly about the safety of my code and would like to rely on the Swift compiler over remembering to check a hasser. So my final beg would be to allow us to generate with optional via a flag! :)

**Comment by tbkka** [comment]
> ... it's wrong to assume that "certain fields would always be set" ...

Unfortunately, it's not always wrong, which was exactly the problem we had with the examples we looked at.  The most significant of those examples was the protoc-gen-swift code generator itself; our code became much cleaner when we moved away from using Swift Optionals.  In particular, it's common for some collection of fields to all be set or unset together, and we found it rather tedious to include lots of redundant optional checks in those cases.

Do you have particular code you could share with us where our current convention is making things awkward for you?  (It's always difficult to discuss these issues in the abstract.)

**Comment by haimwaking** [comment]
In our particular use case, we are dealing with sensitive data which we need to be careful about displaying inconsistently. If the backend has not filled a particular field, we will rather display an error and consider the whole response as invalid.

An example: let's say we are displaying a list of comments, with their authors. The author proto contains `GivenName` and `FamilyName`. We are expected to display the full name of each author and if in the proto `!hasFamilyName()` then we show an error instead. Let's suppose that the author is Cher and does not have a FamilyName, so the backend would send an empty string, which would be fine, because we can rely on `hasFamilyName()` telling as that the backend has filled this field.

**Comment by macduy** [comment]
In our particular use case, we are dealing with sensitive data which we need to be careful about displaying inconsistently. If the backend has not filled a particular field, we will rather display an error and consider the whole response as invalid.

An example: let's say we are displaying a list of comments, with their authors. The author proto contains `GivenName` and `FamilyName`. We are expected to display the full name of each author and if in the proto `!hasFamilyName()` then we show an error instead. Let's suppose that the author is Cher and does not have a FamilyName, so the backend would send an empty string, which would be fine, because we can rely on `hasFamilyName()` telling as that the backend has filled this field.

**Comment by samskiter** [comment]
Just to add to the above, protos also change over time, so you might write some code expecting a field to always be set, but in the wild you could end up talking to a newer server that doesn't fill you field. As Hai said, we are extremely sensitive to these cases and don't want to risk incorrect data being displayed.

In practice, could the 'tedious' unwrapping not easily be handled in one guard block?

**Comment by tbkka** [comment]
> ... expecting a field to always be set...

If you need to validate that a certain field is set, that's easy to do with the current structure:
```
    guard message.hasCriticalField() else { ... error handling ... }
```
or if you want to be slightly more aggressive:
```
    precondition(message.hasCriticalField())
```

I don't see how having Swift Optionals (instead of `hasXyz()` methods) would make this sort of validation any simpler.

If you have a more complex set of conditions you need to verify, you can extend this idea very simply:
```
    extension MyMessage {
        func hasCriticalFields() -> Bool {
             return hasIdField() && id.utf8.count > 10 && hasNameField() && !name.isEmpty
        }
    }

    // ... elsewhere ...
    precondition(message.hasCriticalFields())
```
This seems more straightforward for many applications than having optional unwrap/tests scattered throughout a body of code.  This organization of code lets you put all of the validation conditions in one place (instead of having separate tests for each field in different parts of your code).  It also makes it easy to validate your objects once when they are received instead of duplicating the presence tests every time you access a field.

**Comment by thomasvl** [comment]
Side comment - The specific case here seems to be because you don't trust your server.  If you are talking to it over a secure channel, shouldn't the servers development and/or release process be doing the validation?  Waiting until you get to the client (especially a mobile client), where CPU time comes at the expense of your user, seems wrong.  It also requires all your clients implement the parallel safety checks, depending on how many platforms you have, that is also not always easy.

**Comment by samskiter** [comment]
>If you need to validate that a certain field is set, that's easy to do with the current structure:

It's about it being safer rather than easier.

@thomasvl The idea is also about ensuring a client remains safe when the server might be changing. You might also have an imperfect test environment and when your server and client launch in the wild find certain data you rely on in the client is missing. This checking also helps catch bugs during development.

**Comment by allevato** [comment]
You make it sound like you don't have a way to check whether your server is sending you the information you expect, but you do—it's just in the form of `has` methods instead of optionals. Changing that would only change the syntax, but it wouldn't buy you anything.

Fundamentally, required/optional fields in protobuf are *very different* than non-optional/optional properties in Swift. This is something we gave a *great deal* of consideration to during the design. One might initially think that it's natural to map those concepts together, but it breaks down because:

* The optionality or requiredness of a field applies to *the behavior when the message is serialized and parsed*, not the behavior of the message in memory, which is what `Optional<T>` represents.
* If required fields were treated as non-optionals, you still need a way to reset it to its default value. We considered using implicitly-unwrapped optionals for this and making fields nil-resettable, but found (through experience) that it causes usability problems in several places, particularly when using the fields in switch statements (which particularly affects enum fields). So, the `clear` methods would have to remain. There's no savings there.
* If optional properties are treated as `Optional` in Swift, then you change the semantics of those properties. A protobuf user expects that when they read a field, they get back the value they set *or* the default value if it's not explicitly set to something else. Returning `nil` here is simply the wrong thing to do, and forcing a user to ask for `msg.field ?? msg.fieldDefaultValue` is making extra work for every field access where getting the default automatically is the desired behavior. The default value of a field isn't some "attribute" that you request when you don't find what you're looking for; it's the *innate* value of the field when you ask for it and it hasn't been set to something else, so making it a second-class citizen like that is wrong. Likewise, there would be no savings for the case where you *do* want to check that something is explicitly set because you'd still have to unwrap the optional first instead of calling `has`. So using optionals would be a net-loss to usability overall.
* The current behavior also supports dotting deeply into nested messages and having them auto-created, so you can say something like `msg.subMessage.someOtherMessage.value = 5` and it just works; likewise when reading a deeply nested property, you don't have to check for presence every step of the way (meaning you can still get the default value without having to dot-in twice). This is a pattern that's used across protobuf language implementations.

The current design is the best possible trade-off for balancing *the semantics that protocol buffer users expect based on its specification.* We've tried several alternatives, and they just don't work cleanly—trying use Swift optionals to represent something they don't precisely map to is forced.

**Comment by tbkka** [comment]
> In Proto3...

If you're using proto3, then you don't have "optional" fields at all.  The discussion about how to expose proto "optional" fields only applies to proto2.

Proto3 works a little differently than proto2:  In memory, primitive-valued proto3 fields always have a value.  Proto3 omits fields in the encoded data only as a form of compression (if the value is the default, then there's no point in transferring it).

**Comment by samskiter** [comment]
@tbkka Sorry, yes should have been clearer about proto3. The specs I'm referring to are proto3. There is still a choice to represent an unset message as nil/null or default values.

**Comment by ondev** [comment]
I have tested the proto3,  always have default value and translate to server side.
