### ISSUE TITLE
Revisit type names (protocols, structs, etc.)

### ISSUE THREAD

**Issue by thomasvl** [apple/swift-protobuf#60]
Spun out of @soffes comments on https://github.com/apple/swift-protobuf/commit/6b1a0b0a270f31b93c3d4255d94f8d8f2f9e1ae0

Since all the types will be scoped to the package `SwiftProtobuf`, do we really need to repeat "Protobuf" in all of the types?

`SwiftProtobuf.ProtobufGeneratedMessage` vs just  `SwiftProtobuf.GeneratedMessage`
etc.

Taking it a step further, `Generated` message are actually the common case, so we might want to just make the protocol `Message` and use qualifiers for the other types.  There by shortening the common names folks will see.

**Comment by allevato** [comment]
We can get rid of the `Generated` message when we remove the hand-generated WKTs, and just have a single protocol for messages. However, `Message` feels a bit too generic, since Swift module imports are an all-or-nothing prospect currently. Anyone using `Message` to mean anything in their own client code would be forced to explicitly disambiguate.

I don't anticipate that users would need to touch the protocol that much on its own anyway—they'll stick to using the generated types. In that case, a name like `ProtobufMessage` serves to keep the global namespace clean when this module is imported along with others.

Likewise, things like `ProtobufFloat` have to be public because they're referenced in generated code, but in that case, since they're non-generic types, we could nest them inside a caseless enum to keep them separated (and to let users know they don't need to touch them directly in their own code).

**Comment by tbkka** [comment]
The protocol people *should* be using (for generic functions that accept "any protobuf serializable message") is `ProtobufMessage`.    `ProtobufGeneratedMessage` is purely to collect some things that the generated code needs but aren't otherwise part of the "official message API".  The simplest transition might be to rename the other `*Message` protocols with an underscore prefix to mark them as private, or rename them `ProtobufPrivate*` to clarify.

Another way to clarify this:
   * Rename `ProtobufGeneratedMessage` to `_ProtobufGeneratedMessageSupport`
   * Change the plugin so that messages conform to `ProtobufMessage` and to `_ProtobufGeneratedMessageSupport` 

That might make the relative significance of `ProtobufMessage` clearer.

**Comment by tbkka** [comment]
I like the `Protobuf` prefix for several reasons:  As @allevato mentioned, it clarifies that these are not general-purpose types but are specific to protobuf.  In addition, since including a module is somewhat awkward in some environments (for example, using Xcode without CocoaPods or other support), I expect there will be a number of people just copying the runtime library into their project as a non-module.

**Comment by allevato** [comment]
People copying the runtime library into their project would cause other problems if we start using `internal` to restrict visibility of things. Essentially, it means that we can't rely on tricks like [this](https://github.com/apple/swift-protobuf/pull/43#discussion_r82003059) to work (internal conformance to an internal protocol not causing name clashes with potential symbols in user modules). Essentially it completely breaks encapsulation.

Because of that, I'd *really* like us to *not* let that be a supported way of using the library. Xcode users who don't want to use Cocoapods can pretty trivially create a workspace, add our project to it, and then refer to its framework target from their own application.

**Comment by soffes** [comment]
I'd personally love to see `Protobuf.Message`. I think this may feel "a bit too generic" but it's really what the namespaces are for, right? If you look at the new Foundation types that aren't prefixed, a lot of that seems weird at first, but you start to really like after a bit. I'd love to see this project embrace this thinking :heart:

**Comment by allevato** [comment]
Right, the generated code would just conform to `Message`.

It's one thing for Foundation to have very simple names, because it's Foundation—it, along with Swift's stdlib, decides which types are primary enough to be used without being adorned by prefixes or explicit qualification. If `Message` were a less common term I might not be opposed to it, but my fear is that it's a very loaded term and likely to collide with things other people might import.

Most people *won't* need to refer to it directly. It's *far* more common for people to use the generated types directly than it is to treat messages polymorphically, so I kind of feel like a longer name is a good way of saying "hey, you're doing something a little out of the ordinary here; that's ok, but we don't want to exhaust a really common name for it."

**Comment by tbkka** [comment]
> Right, the generated code would just conform to `Message`.

I thought the generated code would conform to `SwiftProtobuf.Message` if that code were outside of the library.  That would still provide the "longer name" you want and limit ambiguity.

My question was whether that would work for generated code _within_ the library.

I agree that the specific types get referred to most often, but I think a lot of developers do end up building wrappers that save messages to disk or a database or write them to a network, and that utility code should generally use the common `ProtobufMessage` protocol.

**Comment by thomasvl** [comment]
For other languages we've had to special case based on the package to tweak generation to handle stuff like this.

**Comment by allevato** [comment]
Sorry, that's what I meant—generated code *inside* the library would just refer to `Message`, since it can't fully-qualify against itself.

Generated code *outside* the library would import `SwiftProtobuf` and then could refer to either `Message` or `SwiftProtobuf.Message`. In fact, the latter would be safer if we used `Message`, because if someone wanted to have their own `Message` type in their app, it would get priority over the imported one.

^ That alone is probably a good enough reason to leave it `ProtobufMessage`. We have to keep in mind that when we're generating code into *other* people's modules, their type names are going to take priority over the ones we import.

**Comment by jcanizales** [comment]
For the sake of having a ballpark: [A few thousand Swift files](https://github.com/search?utf8=%E2%9C%93&q=filename%3A.swift+%22class+Message%22&type=Code&ref=searchresults) in GitHub define classes called `Message`. (GitHub search isn't great, so a good fraction are false positives I can't filter, but "thousands" looks accurate). Popular concepts for that name seem to be: chat messages, forum posts, and UI dialogs.

Also my anecdotal experience: I used to work on a Java proxy that used protos generically and also had an unrelated `Message` class that we used throughout the codebase. I remember the annoyance of having to type (and see) `com.google.protobuf.Message` in the files where we needed both classes. On the other hand, searching says we had 13 such files, vs 45 in which we *only* used Protobuf's `Message`. So for our case it looks like it being simply "Message" was actually a net win...

**Comment by jcanizales** [comment]
Also: Can one use a type in Swift without importing its module, by qualifying it like `SwiftProtobuf.Message`? If not, what would be the behavior if I imported `SwiftProtobuf` and `ChatLibrary`, both of which defined `Message`?

**Comment by allevato** [comment]
No, a module has to be imported with `import ModuleName` to use it. This also imports all of that module's names into the global namespace, so it effectively gives you *both* `ModuleName.TypeName` and `TypeName`.

If two modules import the same name, you must explicitly disambiguate them at the usage size. In your example, referring to just `Message` would be a compiler error.

The problem we're likely to face is that users may not necessarily generate their protos into a separate library/module, but rather directly into their application code. In that case, if their module has a type named `Message` and they import `SwiftProtobuf` which also has `Message`, referring to `Message` without qualifying it is *not* ambiguous and will refer to *their* message because names in the same module take priority over names imported from other modules.

**Comment by jcanizales** [comment]
Just to make sure I understand: In the generated code itself, `SwiftProtobuf.Message` could be used, to prevent other things in the same module from breaking it. Right?

**Comment by tbkka** [comment]
I'm looking at this as part of rethinking the base Message protocols.  The end result looks pretty good to me:  Basically, things like "ProtobufMessage" are becoming "SwiftProtobuf.Message" throughout the generated code.

**Comment by soffes** [comment]
@tbkka ❤️ amazing

**Comment by tbkka** [comment]
I just merged #139, which should address a lot of these concerns.  Let me know what I missed.

**Comment by tbkka** [comment]
I think #139 addressed this, so I'll close.
