### ISSUE TITLE
Add support for case iteration in SwiftProtobuf.Enum

### ISSUE THREAD

**Issue by azr** [apple/swift-protobuf#607]
Howdy ! It's all in the title. 

here are a few hints :
 * simply generating an array or a map with all possible case ?
 * add an  `iterateEnum<T: Hashable>(_: T.Type) -> AnyIterator<T> {` that works ?
 * may be by just storing the highest enumable value somewhere ?

There is also this : https://stackoverflow.com/questions/24007461/how-to-enumerate-an-enum-with-string-type.

Cheers !!

**Comment by tbkka** [comment]
Our generated `Enum` types all conform to `_ProtoNameProviding`.  As such, they have a `_protobuf_nameMap` field that lists every enum case, including the name in the proto file and the integer case value.

Warning:  This is not yet public API.  You'll have to edit a few places in the SwiftProtobuf library before you can use it outside of the library.  This code will probably change in the future, which is why it's not already public.

**Comment by allevato** [comment]
Please do not use `_ProtoNameProviding`. As the name indicates, it is not public and your code may break in the future if you rely on it.

What's your use case for wanting the list/map of cases to be automatically generated? That would help us understand the problem you're trying to solve.

This is the kind of thing that would be better suited for a reflection/descriptor-based API, but we don't generate those at this time because they would significantly bloat the generated code. See also the discussion at #326 for why we don't generate public interfaces for enums that go beyond what a traditional Swift enum would provide.

**Comment by azr** [comment]
It's for a filter form with switches.
I have a request that takes repeated values of Enum types.
I have different enum types with multiple possibilities and they are going to change a lot while we are in dev.
I just want range on all the possibilities an put them in a table view controller and then simply translate their name string.

eg: 
* case1 on
* case2 off
* etc.  on

**Comment by azr** [comment]
Right now I just have a const integer with the highest value and it's pretty damn simple.

**Comment by thomasvl** [comment]
Closing this out in favor of #729 since there is now a Swift language feature we should model vs. invent ourselves.
