### ISSUE TITLE
descriptor.pb.swift not included when installed by cocoapods

### ISSUE THREAD

**Issue by wukongzhikong** [apple/swift-protobuf#613]
In my case, i need to use google.protobuf.EnumValueOptions, which is defined in descriptor.pb.
Shouldn't we put descriptor.pb.swift into cocoapods's Source directory?

**Comment by thomasvl** [comment]
SwiftProtobuf doesn't currently use the descriptors, so we don't bundle the files.  You are free to generate and include that yourself if you'd like.

Note, we don't use the descriptors because we don't currently provide any descriptor objects for the compiled in protos (or proto style reflection).  It is something we may provide in the future, but did not want to commit to for version 1 of the library.

**Comment by tbkka** [comment]
Also note the collection of types included in the SwiftProtobuf library is not arbitrary.  The types we include today are part of the protobuf spec; they are the "well-known types" that must be directly supported by any conforming protobuf implementation.  As it happens, descriptor.proto is not one of the official "well-known types," so I don't think we should include it without a very good reason.  As @thomasvl pointed out, were we to embed descriptors into the generated source code, that would constitute such a reason.

**Comment by wukongzhikong** [comment]
Thank you guys for your convincing explanations.
I just add it to my project manually to handle my case and everything is ok.
