### ISSUE TITLE
Enums improperly stemmed and conflicting

### ISSUE THREAD

**Issue by allevato** [apple/swift-protobuf#621]
A bug I encountered while trying out a recent version of the code on some Google-internal protos. Consider the following enum:

```proto
enum FooBar {
  FOO_BAR_BAZ = 0;
  QUUX = 1;
  BAZ = 2;
}
```

Our current stemming logic produces the following Swift enum cases:

```swift
baz = 0
quux = 1
baz = 2
```

Obviously, this doesn't compile. _(Why would someone design an enum like that to begin with?_ 🤷‍♂️  _But that ship has already sailed.)_

So, our stemming logic needs to change. Some options:

* Instead of stemming each case in isolation, stem in the context of all the cases and check for conflicts.
* Always stem "all-or-nothing", the logic we had before.
* Something else.

**Comment by tbkka** [comment]
Ouch!  That's a really great find.

I've not dug deeply into how Swift handles this when translating Obj-C enums.  That might offer some ideas.

**Comment by thomasvl** [comment]
I'm going to go back to the C# generator to check out they do the stemming again.  That's what I based the last change on.

The landmines in all this are as enums evolve.  The different options can mean code _breaks_ because the cases change name.  Or worse, if the `BAZ` case got added later, it would take over the short name and all existing code would suddenly use that instead of the `FOO_BAR_BAZ` value they were using when stemming was working for this enum.

**Comment by thomasvl** [comment]
Here's how C# deals with this -

1. When generating the enum, they track the names generated, and if they get repeats (because of trimming or camel case transforms (`FooBar` & `foo_bar` would both end up as `FooBar`)), they add underscores to the end until it becomes unique.
1. C# only generates for files with proto3 syntax.  This means the only default value for a field is zero, and it allows them to never have to generate the the enum value names expect when generating the enum (as they never need to generate the name, they can hard code the default to zero).

The second isn't a big deal, it just means we need collision detection outside of the enum generation so we always have the short names correct.

I'm not a big fan of the first (appending underscores), as it is order dependent.  If the proto file has:

```protobuf
enum BLAH {
  UNSET = 0;
  FOO = 1
  BLAH_FOO = 2;
}
```

and for whatever ever reason, they go and reorder it:

```protobuf
enum BLAH {
  UNSET = 0;
  BLAH_FOO = 2;
  FOO = 1
}
```

The next generation would swap what is `.foo` and `.foo_`.  Which seems rather risky due to the impact on code using things.

So, first, do we care about the camel case transform collisions at all?  `FOO_BAR` and `FooBar`?

Then for prefix handling, the options seem to be:

1. Only prefix strip if the result of the strip isn't another value.
1. Only do prefix stripping when _all_ the values (including aliases?) have the prefix.

The footnote on both of the above is we might be able to special case things around aliases.  In the `FOO_BAR_BAZ` and `BAZ` case, if they both have the same value, we might be able to just expose `baz`, and only worry about the duplicate names in our text parsing support.  The second enum value isn't really needed in the Swift enum.  Hopefully that wouldn't confuse any developers.

There is one other potential in all of this as developer evolve proto files (and remember just because they are using SwiftProtobuf, they might not control the proto file, it might come for a service they want to talk too, and hence don't control the choices for the enum values) – Any form of stripping can result in the `case` we generate changing because of new addition.  i.e. - If the enum used to have `FOO_BAR_BAZ` and now gets `BAZ`, what is `.baz` will change; any code written using that will suddenly be using the new value and there is nothing we can do about it.

**Comment by thomasvl** [comment]
Looks like protoc is working to nail things down around this:

https://github.com/google/protobuf/blob/master/src/google/protobuf/descriptor.cc#L4862-L4884

So a proto3 syntax file, this can't happen, so the issue is only within proto2 syntax files.  Sync both syntaxes are valid and support, this doesn't mean the problem space will go away; the proto2 syntax support for it just means they didn't want to break existing files 😦 , but that the fact that it triggers a warning may mean we are more ok with some crappier choices for dealing with this.

**Comment by allevato** [comment]
> I'm not a big fan of the first (appending underscores), as it is order dependent.

What if we just always pre-sort the cases in numerical order for the purposes of underscoring?

**Comment by thomasvl** [comment]
> What if we just always pre-sort the cases in numerical order for the purposes of underscoring?

The catch is aliasing; the "first" one is real one, and the later ones are the "aliases".  So sorting might work if we also special case aliases.

**Comment by allevato** [comment]
Right, of course.

What about just appending the numeric value itself?

```proto
enum BLAH {
  UNSET = 0;
  FOO = 1
  BLAH_FOO = 2;
}
```

becomes

```swift
enum Blah {
  case unset = 0
  case foo_1 = 1
  case foo_2 = 2
}
```

Sure, it's ugly, but it'll survive reördering and doesn't seem *worse* than arbitrarily adding underscores.

**Comment by tbkka** [comment]
> What about just appending the numeric value itself?

That's the best idea so far.

**Comment by thomasvl** [comment]
And special case aliases to only provide one value when they would collide after stemming?

**Comment by allevato** [comment]
> And special case aliases to only provide one value when they would collide after stemming?

That sounds like it would work, since they'd still end up with the same name + number.

**Comment by tbkka** [comment]
If we want to distinguish "real" vs. "alias" values, then it seems we have to do this in phases:
* First, consider only the "real" values.  If any of those collide with each other, suffix both colliding values with the numeric value.  (We know this will make them unique.)
* Second, add the alias values.  Suffix any colliding aliases with a number.

Hmm...  the second step here isn't guaranteed to make them unique; what's the next step?

**Comment by tbkka** [comment]
Ah.  Of course.  Any colliding aliases would have same name + number and can be simply dropped.

**Comment by thomasvl** [comment]
Right, if the alias and master map to the same thing, don't generate anything in Swift and just support it in the text formats.

**Comment by thomasvl** [comment]
Two wrinkles -

Enums are `Int32` (not `UInt32`), what should we do if the value we need to append to the name in negative?  Extra underscore?  `BLAH_FOO = 1; FOO = -1;` –» `.foo_1` and `.foo__1` or something else?

When the alias would shorten to the same thing in Swift, we were saying we could drop it, what if that alias had comments in the proto file?  Do we just not generate anything (and lose those comments), or should we still generate something?  Comments and some canned comment about why there is no symbol for it?  Put this into the appended underscore case, and generate a name for it with the comments?

**Comment by allevato** [comment]
`-1` -> `_1` or `n1` or `neg1` all seem reasonable. (I'm kind of at the point where I don't care how ugly they are because anyone who designed a proto that would cause this behavior should have to suffer a little bit; but I guess downstream dependents have to suffer too 😞.)

Re: comments, I'd recommend dropping them. If the comments were specifically tied to an alias that we're not generating, it seems potentially misleading to attach those comments somewhere else.
