### ISSUE TITLE
Add prebuilt framework archives in releases for faster Carthage installations

### ISSUE THREAD

**Issue by bryant1410** [apple/swift-protobuf#637]
Maybe you can set up [automatic archiving of the prebuilt framework in GitHub releases so Carthage installations are faster](https://github.com/Carthage/Carthage#archive-prebuilt-frameworks-into-one-zip-file).

**Comment by tbkka** [comment]
Unfortunately, this is not really possible with Swift libraries such as ours, due to the fact that Swift does not yet have a stable ABI.  (So frameworks compiled with one version of Swift may not be usable with code compiled with a different version of Swift.)

**Comment by thomasvl** [comment]
I'm going to go ahead and close this out, even thought Swift 5 should have a stable api, I believe it won't have it for module maps yet either, so we still won't be able to provide something pre built as it would have to be a different prebuilt binary for every version of Xcode we tried to support.

**Comment by NachoSoto** [comment]
>  (So frameworks compiled with one version of Swift may not be usable with code compiled with a different version of Swift.)

That's a known fact, so what library maintainers usually do is specify which version a release framework is built for. Carthage automatically detects this (for example, if the library is compatible with Swift 3.1, 3.2, and 4.0, but built with Xcode 9's compiler) and does builds the framework instead of using the precompiled framework.

For that reason, it would still be useful to have binaries in each release, even if there's a chance it won't be used if one tries to use the dependency with an incompatible version.

**Comment by eoger** [comment]
Could we revisit this issue? As @NachoSoto said Carthage will fallback to a local build for incompatible versions anyway.
