### ISSUE TITLE
"import public" not handled correctly when generating import statements

### ISSUE THREAD

**Issue by allevato** [apple/swift-protobuf#639]
The way we currently generate import statements (for the .proto file -> module map) doesn't take into account messages used transitively through `import public`.

For example,

```protobuf
// File: a.proto
message A {}

// File: imports_a_publicly.proto
import public "a.proto";

message ImportsAPublicly {
  A a = 1;
}

// File: uses_a_transitively.proto
import "imports_a_publicly.proto";

message UsesATransitively {
  A a = 1;
}
```

Imagine we produce a separate module for each of the generated Swift files and use the following mapping when generating `uses_a_transitively.proto`:

```
mapping {
  module_name: "ImportsAPublicly"
  proto_file_path: "imports_a_publicly.proto"
}
mapping {
  module_name: "A"
  proto_file_path: "a.proto"
}
```

Because [`ProtoFileToModuleMappings`](https://github.com/apple/swift-protobuf/blob/master/Sources/PluginLibrary/ProtoFileToModuleMappings.swift#L93-L97) only looks at the `import` statements literally present in the `.proto` file, and because Swift module imports aren't transitive, `uses_a_transitively.pb.swift` does not get the `import A` line that it needs to successfully compile.

**Comment by thomasvl** [comment]
There are two ways to solve this:
- At the dependency level, just do imports for all public deps (recursively)
- Hack it, and never use the dependencies, and instead keep track of what modules we used for type references and just import those.

The first could end up importing things the file doesn't need (because it doesn't actually use one of those public imports of its dependency), but it is likely the cleaner thing to do.
