### ISSUE TITLE
API docs have wrong signature for isEqualTo()

### ISSUE THREAD

**Issue by tengyifei** [apple/swift-protobuf#676]
In the API docs it says: https://github.com/apple/swift-protobuf/blob/9501879a79221a355daf87e52475c3bf7c3ed333/Documentation/API.md#overridable-message-methods

Such that there is a computed variable `public var isEqual(other: Example) -> Bool` that can be overridden in an extension to `Example`, but I can't see how to do that.

I've attempted to write a function with the signature `public func isEqual(other: Example) -> Bool`, but it doesn't get called. There is also no apparent reference to `isEqual` in the code base.

**Comment by thomasvl** [comment]
@tbkka is this just a docs error?  Should it be `isEqualTo(other:) -> Bool` ?

**Comment by tengyifei** [comment]
@tbkka @thomasvl Looks like directly overriding `==` is the way to go in `1.0.0`?

**Comment by tbkka** [comment]
@tengyifei You should override `func isEqualTo(message:) -> Bool`

It might work to override `==` but I'm not certain that will always do the right thing.  In particular, there are a few places that need polymorphic equality of messages and call `isEqualTo` and I suspect that the base implementation of `isEqualTo` will always call the `==` defined in the protocol (instead of your custom version).

**Comment by tbkka** [comment]
I've retitled this to clarify the documentation bug here.

**Comment by tengyifei** [comment]
Thanks!

**Comment by tengyifei** [comment]
https://github.com/apple/swift-protobuf/pull/677
