### ISSUE TITLE
Is there a support for proto Services

### ISSUE THREAD

**Issue by Saurman** [apple/swift-protobuf#682]
Hello, i have proto3 file with messages and services but generated swift code only contains structs and mappers for messages but not service methods. It is not implemented yet?

**Comment by thomasvl** [comment]
Services aren't part of the basic data format which is what SwiftProtobuf wants.  For services, you likely want to look at something that layers on top of Protobufs like gRPC.

**Comment by thomasvl** [comment]
PS - The [protobuf spec for services](https://developers.google.com/protocol-buffers/docs/proto3#services) mentions that the core libraries don't generate full impls, some languages generate stubs where you have to provide something for the concrete impl to provide the details.  We haven't bothered with the basic stubs at this point.  Once Swift finishing figuring out some of its async proposals (see swift-evolution for those), it might make sense to make some pure protocols for these things, but it will still just be that, the stub interfaces and concrete RPC impls would be needed to provide the networking code since that there could be any number of them.

**Comment by tbkka** [comment]
You should also look at 

   https://github.com/grpc/grpc-swift

Basically, grpc-swift generates only the service methods; those service methods rely on message implementations built by swift-protobuf.

**Comment by tbkka** [comment]
Closing, since we have no plans to support Services directly.

You should either look at Swift gRPC (which uses SwiftProtobuf to create the data model and then generates the Service stubs) or you could consider using SwiftProtobufPluginLibrary as a building block to construct your own code generator to build Service stubs.
