### ISSUE TITLE
Types define in Sources/PluginLibrary/ are not included in .podspec file...

### ISSUE THREAD

**Issue by cameronehrlich** [apple/swift-protobuf#688]
iOS 10, Swift 4, Xcode 9, SwiftProtobuf (1.0.0)

We have `.proto` files that are being autogenerated for multiple platforms (Go, Ruby, Python, and Swift).  In our `.pb.swift` files, the `Google_Protobuf_FieldOptions` and `Google_Protobuf_MessageOptions` types are being extended:

```swift
extension Google_Protobuf_FieldOptions {
  /// Field number was just grabbed from the example in the docs, it has no special meaning
  /// https://developers.google.com/protocol-buffers/docs/proto#customoptions
  var Fairapis_Type_Encrypted_path: String {
    get {return getExtensionValue(ext: Fairapis_Type_Encrypted_Extensions_path) ?? String()}
    set {setExtensionValue(ext: Fairapis_Type_Encrypted_Extensions_path, value: newValue)}
  }
  /// Returns true if extension `Fairapis_Type_Encrypted_Extensions_path`
  /// has been explicitly set.
  var hasFairapis_Type_Encrypted_path: Bool {
    return hasExtensionValue(ext: Fairapis_Type_Encrypted_Extensions_path)
  }
  /// Clears the value of extension `Fairapis_Type_Encrypted_Extensions_path`.
  /// Subsequent reads from it will return its default value.
  mutating func clearFairapis_Type_Encrypted_path() {
    clearExtensionValue(ext: Fairapis_Type_Encrypted_Extensions_path)
  }
}

extension Google_Protobuf_MessageOptions {
  /// Another arbitrary field number
  var Fairapis_Type_Encrypted_messagePath: String {
    get {return getExtensionValue(ext: Fairapis_Type_Encrypted_Extensions_message_path) ?? String()}
    set {setExtensionValue(ext: Fairapis_Type_Encrypted_Extensions_message_path, value: newValue)}
  }
  /// Returns true if extension `Fairapis_Type_Encrypted_Extensions_message_path`
  /// has been explicitly set.
  var hasFairapis_Type_Encrypted_messagePath: Bool {
    return hasExtensionValue(ext: Fairapis_Type_Encrypted_Extensions_message_path)
  }
  /// Clears the value of extension `Fairapis_Type_Encrypted_Extensions_message_path`.
  /// Subsequent reads from it will return its default value.
  mutating func clearFairapis_Type_Encrypted_messagePath() {
    clearExtensionValue(ext: Fairapis_Type_Encrypted_Extensions_message_path)
  }
}
```

The problem is that these types are defined in the `Sources/PluginLibrary/` directory path, however `SwiftProtobuf.podspec` only includes files within the `Sources/SwiftProtobuf` directory so those types that are being extended are considered undeclared/unresolved:
```bash
    - ERROR | [iOS] xcodebuild:  FairApiGeniOS/swift/fairapis/type/encrypted.pb.swift:561:11: error: use of undeclared type 'Google_Protobuf_FieldOptions'
    - ERROR | [iOS] xcodebuild:  FairApiGeniOS/swift/fairapis/type/encrypted.pb.swift:580:11: error: use of undeclared type 'Google_Protobuf_MessageOptions'
    - ERROR | [iOS] xcodebuild:  FairApiGeniOS/swift/fairapis/type/encrypted.pb.swift:609:146: error: use of undeclared type 'Google_Protobuf_FieldOptions'
    - ERROR | [iOS] xcodebuild:  FairApiGeniOS/swift/fairapis/type/encrypted.pb.swift:615:154: error: use of undeclared type 'Google_Protobuf_MessageOptions'
    - ERROR | [iOS] xcodebuild:  FairApiGeniOS/swift/fairapis/type/encrypted.pb.swift:566:10: error: use of unresolved identifier 'setExtensionValue'
    - ERROR | [iOS] xcodebuild:  FairApiGeniOS/swift/fairapis/type/encrypted.pb.swift:584:10: error: use of unresolved identifier 'setExtensionValue'
    - ERROR | [iOS] xcodebuild:  FairApiGeniOS/swift/fairapis/type/encrypted.pb.swift:576:5: error: use of unresolved identifier 'clearExtensionValue'
    - ERROR | [iOS] xcodebuild:  FairApiGeniOS/swift/fairapis/type/encrypted.pb.swift:594:5: error: use of unresolved identifier 'clearExtensionValue'
```

Am I missing something? Or might it be possible to include those "Google" types in the `podspec`? The `Package.swift` file does include these types via the `PluginLibrary` target:

```swift
let package = Package(
  name: "SwiftProtobuf",
  targets: [
    Target(name: "PluginLibrary",
           dependencies: ["SwiftProtobuf"]),
    Target(name: "protoc-gen-swift",
           dependencies: ["PluginLibrary", "SwiftProtobuf"]),
    Target(name: "Conformance",
           dependencies: ["SwiftProtobuf"]),
  ]
)
```

Thanks!

**Comment by cameronehrlich** [comment]
It looks like the `Sources/PluginLibrary` was recently excluded in this PR:
https://github.com/apple/swift-protobuf/pull/31

**Comment by cameronehrlich** [comment]
Here is a proposed fix to the problem: https://github.com/apple/swift-protobuf/pull/689

**Comment by thomasvl** [comment]
The plugin library code should not be linked into end user code.  It is just for the plugin.

SwiftProtobuf doesn't currently support anything like the descriptor objects that exist for other languages, so there wouldn't be any way to get at this data anyway since it just exists at generation time.  If the extensions are defined in their own .proto files, just leave them out of what you generate/compile in.

Can you point us at an example of what your doing with your extensions so we can understand and try to help out?

**Comment by thomasvl** [comment]
PS - Where ever you are getting `protoc` it will include `descriptor.proto`, you can always generate it and compile that in with your sources.  We don't provide it because the runtime because as mentioned the runtime doesn't current use/expose this info, so it would normally be bloat.

**Comment by tbkka** [comment]
The compiled `descriptor.proto` was dropped from the `SwiftProtobuf` package because it is not actually part of the protobuf spec.

What are you using it for?  We could add it back if we had a convincing reason to do so.  (Since it is very hard to remove functionality in later versions, we've deliberately tried to err on the side of leaving stuff out unless we knew it was necessary.)

**Comment by marshallbrekka** [comment]
Hopefully I can provide some context on this.

## Use Case
We have created some custom field and message options that some of our runtime libraries reflect on in order to alter behavior.

## Custom Options
According to the documentation on [Custom Options](https://developers.google.com/protocol-buffers/docs/proto#customoptions), you implement them by extending the core message types in `descriptor.proto`.

These options are then made accessible via runtime API calls.

## The Issue
Omitting the compiled `descriptor.proto` is inconsistent with the behavior of some of the other language targets.

We currently compile our protos to Go and Python, both of which provide the compiled `descriptor.proto` messages with their runtime libraries ([Go](https://godoc.org/github.com/golang/protobuf/protoc-gen-go/descriptor), [python 1](https://developers.google.com/protocol-buffers/docs/reference/python/google.protobuf.descriptor-module), [python 2](https://developers.google.com/protocol-buffers/docs/reference/python/google.protobuf.descriptor_pb2-module)).

While minor (and solvable as suggested above by compiling it ourselves), it adds inconsistencies into the build requirements between the language targets.

## Possible Resolutions
Ideally from our perspective, the `descriptor.proto` messages would be included by default, however we understand there might be other reasons not to go that route.

Because this behavior differs from the other compilers/runtimes, at the very least it would be nice to call out this difference in the documentation somewhere. That way its obvious this is a design decision, and not a bug in our usage of the compiler, or the way we included the runtime as a dependency.

Hope that helps explain the situation, thanks!

**Comment by thomasvl** [comment]
So because Swift doesn't expose descriptors (like a few of the other languages), anything you set in those options isn't going to be available at runtime.  So you'll need to find another way to get that data from Swift.

For a little background, the descriptors can be a non trivial amount of code and static data; the majority of the protobuf consumers don't need that data, so it ends up just being bloat in their binaries.

**Comment by thomasvl** [comment]
#690 up for documenting that descriptors are not supported.

@cameronehrlich @marshallbrekka - Just to make sure it is clear, even if descriptor.pb.swift was included in SwiftProtobuf, that would just let your declared extensions get compiled.  It would not actually expose all the descriptor "objects" from the messages, enums, etc.  Also, it would not get the values for your options captured into the binary.  To really get all that functionality, it would take building out a whole descriptor system to capture the data during generation as well as the runtime support to then expose it.

**Comment by tbkka** [comment]
@cameronehrlich, @marshallbrekka:  Are you relying on being able to obtain descriptor data from the generated code?

As @thomasvl pointed out, we do not currently embed descriptors in the generated code.  (Most people don't need them and some people cannot afford the extra size.)  When we do implement them, I expect we would generate separate source files containing the descriptor data as extensions of the base structs, so that people who don't need descriptors can simply omit those source files.

**Comment by marshallbrekka** [comment]
@thomasvl @tbkka Thanks for the replies, in this particular case we don't need the ability to access the descriptors from swift (it's only relevant on our backend), we're just trying to get the compiled code to work well without having to modify our proto structures.

Adding the documentation and punting the responsibility of compiling `descriptors.proto` to the user is an acceptable tradeoff, given the concerns above.

**Comment by cameronehrlich** [comment]
Thank you, @thomasvl and @tbkka, for clearing this up for us.

**Comment by thomasvl** [comment]
np.  From a .proto file structure pov, if you are using types in field/message options that you also need in your binary (but don't actually need descriptors), I'd suggest putting the extensions for the options in a separate .proto file so you don't have to include that in your binaries (since you say you don't need access to the options).
