### ISSUE TITLE
Build to swift not import SwiftProtobuf

### ISSUE THREAD

**Issue by HieuLsw** [apple/swift-protobuf#693]
Thank you!
I use mac os x 10.12.6. Xcode 9.1 , swift 4.0.2, SwiftProtobuf (1.0.0) . swift compliler (swift 4)
Hi, why each one run command to gen swift file from file .proc . In swift file import ProtocolBuffers instead of SwiftProtobuf???. i mean why not SwiftProtobuf but ProtocolBuffers
<img width="370" alt="screen shot 2017-11-02 at 11 06 44 pm" src="https://user-images.githubusercontent.com/1675478/32336715-9a02493a-c022-11e7-9301-0ba12bdc4230.png">

**Comment by thomasvl** [comment]
It sounds like you have a `protoc-gen-swift` from a different project and aren't using the one from this project.

**Comment by HieuLsw** [comment]
This is my .proc file
[TilePr.proto.zip](https://github.com/apple/swift-protobuf/files/1438488/TilePr.proto.zip)

**Comment by HieuLsw** [comment]
how i can do to fix it ?

**Comment by thomasvl** [comment]
> how i can do to fix it ? @thomasvl

Since I'm not really sure how/what you installed, it is sorta hard to say.  `which proto-gen-swift` should tell you where the binary is being found, try removing that and make sure you are installing a the binary built from this project.  See the [build and install](https://github.com/apple/swift-protobuf/blob/master/Documentation/PLUGIN.md#build-and-install) step.

**Comment by tbkka** [comment]
@HieuLsw:  How did you install?

You need to install swift-protobuf (and may need to uninstall protobuf-swift, which is what you're using now).

**Comment by HieuLsw** [comment]
i done this. thank you. i wanna gen swift file with 
  let geometry: [Any]
    let type: String
    let tags: Tags
with type [Any] What should I design .proc file?

**Comment by tbkka** [comment]
You can't use `Any` directly because there's no way to serialize it.

If you can, you should define a single geometry type and use that type directly.  This is safer,  faster, and easier to work with:
```
message MyType {
   repeated Geometry = 1;
   string type = 2;
   Tags tags = 3;
}

message Geometry {
   ...
}

message Tags {
  ...
}
```

If you have more than one, you could use protobuf's `oneof` feature:
```
message MyType {
   repeated Geometry = 1;
   ...
}

message Geometry {
   oneof {
      Geometry1 type1 = 1;
      Geometry2 type2 = 2;
   }
}

message Geometry1 {
   ...
}

message Geometry2 {
  ...
}
```

The closest to what you asked for is to use a `google.protobuf.Any` wrapper object.  That has additional overhead, so it's not recommended except for rare cases where you have highly dynamic schema:
```
import "google/protobuf/Any.proto";
message MyType {
   repeated Any geometry = 1;
   string type = 2;
   Tags tags = 3;
}
```

In this last case, the generated Swift will look like this:
```
struct MyType {
   var geometry: [Google_Protobuf_Any]
   var type: String
   var tags: [Tags]
}
```

You'll still have to define each geometry type as a protobuf message in order to store it in a `Google_Protobuf_Any` wrapper.

Note:  There is an active protobuf mailing list on groups.google.com that can help with general protobuf data modeling questions.

**Comment by HieuLsw** [comment]
thank your. i got it. 👍

**Comment by HieuLsw** [comment]
@tbkka : How i can creat .proc file with output as : 
class ProjectedGeometryContainer: ProjectedGeometry {

    var members = [ProjectedGeometry]()
    var area: Double = 0
    var dist: Double = 0

    init(members: [ProjectedGeometry] = []) {
        self.members = members
    }

}
with   ProjectedGeometry is protocol or abstract as:
protocol ProjectedGeometry {
  
}
class ProjectedGeometry {
    // abstract
}

**Comment by HieuLsw** [comment]
Beacause i also have a class : 
class ProjectedPoint: ProjectedGeometry {

    var x: Double = -1
    var y: Double = -1
    var z: Double = -1
}

**Comment by tbkka** [comment]
We do not support user-defined protocol or abstract types.  (There are good reasons for this.)

We do not currently support generating reference types (classes), only value types (structs).  If you must have classes, then you could consider using Google's Obj-C generator, which always generates classes that you can then use from Swift.

**Comment by thomasvl** [comment]
Note also that all proto implementations will generate their own types for messages.  Protos aren't meant to generate out to your own custom classes your custom classes might not follow the protobuf wire format rules.

**Comment by talksik** [comment]
I am hitting a similar issue here. I have generated swift protobuf files and installed via SPM. It's likely some sort of bug in the protocol plugin.

This is the typical timestamp proto definition from Google. This is the only one that doesn't import SwiftProtobuf:
<img width="1610" alt="image" src="https://github.com/apple/swift-protobuf/assets/19339529/5e2773da-a5d0-4697-ad37-e19401ba70c1">

As you can see, it imports Foundation, but it doesn't import SwiftProtobuf.

However, my other files import SwiftProtobuf just fine:
<img width="735" alt="image" src="https://github.com/apple/swift-protobuf/assets/19339529/14fdfa8c-595d-4773-b588-cc3471b73a97">


For now, I am going to manually insert the line to import SwiftProtobuf. Would be great if someone else knows what's going on.

This is what I am running to generate the swift files: 
```
  swift-genproto:
    cmds:
      - rm -rf ./apple/apple/genproto
      - mkdir -p ./apple/apple/genproto
      - |
        find ./protobuf -name "*.proto" | xargs protoc --proto_path=./protobuf --swift_out=./apple/apple/genproto

```

**Comment by tbkka** [comment]
@talksik  `Google_Protobuf_Timestamp` is already included in the SwiftProtobuf library.  You should not need to generate Swift code for that particular type.

**Comment by talksik** [comment]
Thank you @tbkka ! I just got rid of it as per your suggestion. It is slightly odd that the generator is not managing conflicts, but I understand why.

I just had a script to convert all of my `.proto` files and `timestamp.proto` was just one of them because of our other clients in other languages needed it.

**Comment by thomasvl** [comment]
> It is slightly odd that the generator is not managing conflicts, but I understand why.

You mean have it error if you try to generate a bundle one?

We have to generate those files to ship them, but I guess we add an option to override the block so folks don't do this by accident.  Out of curiosity what languages do you deal with that don't bundle it?

**Comment by talksik** [comment]
Yeah @thomasvl , or at least warn about this? Maybe warn and don't generate the timestamp.pb.swift because it doesn't compile if it does generate it.

We happen to generate them for golang merely because we want full control over the proto. I guess we could change the name of the package as a workaround, but in golang and dart, we are able to generate just fine.

**Comment by thomasvl** [comment]
I know nothing about Go, but https://github.com/golang/protobuf seems to say they include the support, and a quick skim implies they have helpers, so I do wonder if generating it with a different name might run against any of the library built in support (especially for special JSON handling, etc.).

As @tbkka mentions, saying you want "full control" gets a little grey quickly, as there are contracts around these types and JSON encoding/decoding, so the library does have to know about them.  Also, just because you generate with a different name, might only mean you can have limited control of a type when it is the single type, but if a `google.protobuf.Timestamp` were nest need in an object graph or wrapped within an `google.protobuf.Any`, then you might end up getting the _bundled_ version instead.

Popping back to the original issue, we could make it an error if someone tries to generate one of the WKTs to help prevent any of these problems, but I also worry it might draw attention to someone trying to think it is overridable in some way. I don't think we've had any other reports since 1.0.0 (2017) of folks running into problems like this because they tried to generate the WKTs.

**Comment by tbkka** [comment]
Yeah, Thomas has a good point there:  the Well-Known Types (WKTs) are magic in any protobuf implementation in any language.  Re-generating them could break any number of special accommodations:   In the case of SwiftProtobuf, [`Any` has special knowledge of all the WKTs](https://github.com/apple/swift-protobuf/blob/4ac8a2e399f10c6f2bba93fbbb87f4b801bff4f9/Sources/SwiftProtobuf/AnyMessageStorage.swift#L26); the [JSON encoder and decoder have special affordances](https://github.com/apple/swift-protobuf/blob/4ac8a2e399f10c6f2bba93fbbb87f4b801bff4f9/Sources/SwiftProtobuf/Google_Protobuf_Timestamp%2BExtensions.swift#L216C1-L217C1); and [each WKT has additional extensions providing convenience methods](https://github.com/apple/swift-protobuf/blob/4ac8a2e399f10c6f2bba93fbbb87f4b801bff4f9/Sources/SwiftProtobuf/Google_Protobuf_Timestamp%2BExtensions.swift#L231C1-L232C1).  All of that machinery only works for the WKT that is part of the SwiftProtobuf library.  Your re-generated version would not have any of that.

**Comment by talksik** [comment]
@thomasvl  thank you for the detailed thought experiment. I agree that 99% of the time, this would be fine. There might be unique use cases, but in those situations, it makes more sense to have own custom Timestamp proto with a different package name. For example, our app may want to have a Timestamp proto like below:

```protobuf
message Timestamp {
  string relative_time = 1; // like "2 hours ago"
  int seconds = 2;
  int milliseconds = 3;
}
```

**Comment by tbkka** [comment]
Hmmmm....   Perhaps instead of merely suppressing the `import SwiftProtobuf` line when compiling the WKTs, we could replace that line with a comment?   Maybe:
```
// "import SwiftProtobuf" is suppressed for Well-Known Types that are included in the SwiftProtobuf library
```
That would avoid the need for a special option to support recompiling these, and perhaps clarify things for anyone else who might run into this issue.

**Comment by thomasvl** [comment]
So you aren't really replacing Timestamp, you are defining you own for your own usages, but hooking that in to all other places that want the WKT Timestamp is likely risky as it would mean extra fields that other clients you try to talk to won't support, etc. So yea, renaming it is starting to make a lot more sense to me.
