### ISSUE TITLE
Prebuilt binaries in release

### ISSUE THREAD

**Issue by soffes** [apple/swift-protobuf#7]
It would be fantastic if you would attach prebuilt binaries for Carthage users to the GitHub release. (You can convert a regular git tag into a release on the [releases](https://github.com/apple/swift-protobuf-runtime/releases) page.)

Once you have [Carthage installed](https://github.com/carthage/carthage#installing-carthage), you can simply run the following to generate a release:

```
$ carthage build --no-skip--current && carthage archive SwiftProtobuf
```

Then you can add `SwiftProtobuf.zip` to the release.

Note, #6 needs to be merged before you can build with Carthage since that uses the Xcode project.

**Comment by tbkka** [comment]
There are still some pretty disruptive changes in the works.  After things have settled a bit, we can consider what a "release" will mean.

**Comment by jcanizales** [comment]
When the time comes for an early release, publishing also the pre-compiled plugin would let Cocoapods do the code generation.

**Comment by thomasvl** [comment]
Since this was opened, we've shuffled things around a bit and the plugin is within the repo, so there are less moving parts.  We're a little hesitant to do binaries for protoc since google/protobuf does their own release process; so that just leaves the SwiftProtobuf plugin, and hopefully that is pretty easy to use now that things are all in one repo.
