### ISSUE TITLE
Use swift-protobuf on ObjC+Swift project

### ISSUE THREAD

**Issue by paktree** [apple/swift-protobuf#703]
Hi,

We are planning to use Protobuf on our project. Half of the code in the project are written in ObjC and one of our core data model was written in ObjC. I'm currently deciding whether we should use the ObjC Protobuf library or swift-protobuf. From what I can see, the generated code from swift-protobuf are structs and they don't seem very compatible to be used on Objective C. In that case, we will have to write Swift class wrapper around those generated structs in order to use them in our ObjC code.

Does anyone have any recommendation on this subject? We don't want to write wrapper for all the protobuf structs, will I be better off using ObjC version of the library?

**Comment by thomasvl** [comment]
You can always use the ObjC protos from Swift code (they just won't be value types).  So if you need to support that sort of a mixed world, it might make sense to just use the ObjC ones instead.

If you are going to migrate the ObjC code that needs protos to Swift at some point, then it _might_ make sense to do wrappers to expose the Swift ones back to ObjC for the time being.

**Comment by paktree** [comment]
That makes sense. One thing that makes me hesitate to use the ObjC protobuf is the support of JSON. In some cases, we will pass back protobuf object in JSON format from the server, from I read so far on ObjC protobuf, it doesn't support JSON serialization currently (https://github.com/google/protobuf/issues/1675), does it mean the objc protobuf library does not support deserializing JSON format protobuf?

Let me know if I should post this question on the objc protobuf library instead. Thanks!

**Comment by thomasvl** [comment]
Correct, ObjC does not support JSON.  Since ObjC is mainly used for mobile, size of things really matters; so not having to the code or strings for JSON can be a savings.

The size concerns are also valid for Swift, but we're hoping the fact that Swift can do some dead stripping will help and we have #18 to look at making the strings needed optional so developers can decide to include/exclude the support.  It just wasn't something we went after for the 1.0 release.

**Comment by paktree** [comment]
Got it, another use case I'm thinking is for the ability of serializing/deserializing JSON is for persisting protobuf objects on disk. Do you have any recommendation on that? I have raised the question on the ObjC protobuf (https://github.com/google/protobuf/issues/3935)

Thanks for your help!

**Comment by thomasvl** [comment]
Replied over there.

**Comment by thomasvl** [comment]
I didn't a reply over there (or here), why do you feel JSON is the right path for persisting data?  The binary format is the one that actually handles unknown fields, so it much better suited to dealing with the message/enums/etc. evolving over time.

**Comment by paktree** [comment]
We agree that binary format is better for persistency, it's good to know that NSCoding is being supported in the ObjC Library. I believe Swift one also support NSCoding?

**Comment by thomasvl** [comment]
> I believe Swift one also support NSCoding?

No, `NSCoding` these days slides into the whole [`Codable`](https://developer.apple.com/documentation/swift/codable) discussion; and since that includes its own definitions of a JSON encoding (and a binary one (via plists)), it can get really confusing quickly.  See some of the other issues (open and closed) that have asked about this.  It _might_ make sense to support something like ObjC does (for `NSSecureCoding` and hence `NSCoding`), but given the potential confusion, the library does not do it at this time.

**Comment by paktree** [comment]
Interesting. I can see it can get complicated. 

In that case, what would be the best way to persist a protobuf swift object?

**Comment by thomasvl** [comment]
Until the library provides something, you can always add your own extension to provide whatever helpers you need, I'd just use the binary serialization in the library for the actual format.

**Comment by tbkka** [comment]
The result of serializing a protobuf type is a `Data` object, so you can just write that to a file:
```
try myObject.serializedData().write(to: ..., options: ...)
```

**Comment by zakyg** [comment]
A good reason for supporting JSON, Text or any human readable format is debugging or mocking. Being able to persist protobuf objects on disk and modifying them by hand for testing, sniffing network traffic, these are very useful tools. Any updates on Text or JSON support for obj-c since the last discussion here?

**Comment by thomasvl** [comment]
The reasoning still stands (code size, etc.), for not supporting it in ObjC where no real dead stripping ever happens.  As far as persisting on disk, the textual formats really aren't as good for when the messages/enums may evolve with time, only the binary form is able to ensure old/new code can read old/new messages without losing anything.

fyi - this is the issue tracker for Swift, not ObjC.

**Comment by thomasvl** [comment]
Closing this out since the original question seems answered, and the one follow up since original opened was for ObjC, not SwiftProtobuf.
