### ISSUE TITLE
Checking empty nested data

### ISSUE THREAD

**Issue by paktree** [apple/swift-protobuf#707]
Hi,

We have some nested data in our protobuf format, we want to figure out a way to check if that piece of nested data structure is empty, when I print that piece of data in Xcode:

(lldb) po myData?.nestedData
▿ Optional<My_Proto_MyData>
  ▿ some : My_Proto_MyData:
nested_data_key_A {
}

    ▿ unknownFields : UnknownStorage
      ▿ data : 0 bytes
        - count : 0
        ▿ pointer : 0x0000608000016910
          - pointerValue : 106102872172816
        - bytes : 0 elements
    ▿ _storage : <(_StorageClass in _00F2710D1E923E01D33F28DADFC99B1C): 0x60c00187c5c0>

On Android, the way we check it is to compare that message with `getDefaultInstanceForType` to see if it's equal to that. However, I can't seem to find a default instance method in the swift library and I tried to create an empty `My_Proto_MyData()` object; however, it doesn't contain nested_data_key_A so it's not equal.

What's the best to check an empty nested data?

**Comment by tbkka** [comment]
Could you share the proto definition?  Are you using proto2 or proto3?

**Comment by paktree** [comment]
Sure, we are using proto 3. Here is a sample proto file that is based on the one we use:

```syntax = "proto3";
...
message rootData {
    MyData my_data = 1;
}

message MyData {
    google.protobuf.Timestamp nested_data_key_A = 1;
    int32 nested_data_int_A = 2;
}```

Thanks!

**Comment by thomasvl** [comment]
I'm not completely clear what you are after, are you trying to tell if `my_data` in a `rootData` was set (that should be doable via the generated `hasMyData`).  Or are you try to tell if your `MyData` has _any_ of its fields set?

**Comment by paktree** [comment]
Currently, our server side code always set a default value for My Data and MyData's nested_data_key_A. On Android client, we check if My Data is set to default value in order to tell it's empty data or not, that's why we rely on `getDefaultInstanceForType` method. The reason we always set a default value for MyData because we notice that the `hasX` function returns `true` after we call `rootData.getMyDataBuilder()` on the server even though we weren't actually setting any fields and so we were a little worried about the robustness of the `hasX` checks.

**Comment by thomasvl** [comment]
If you are setting a value server side, then odds are it is going out (even it it has not sub field set) when it is serialized.  So client side will always see the the field as "set" because the server did send one.  Looking at your proto and a binary encoding of an instance would confirm that.

As noted in the [Java docs](https://developers.google.com/protocol-buffers/docs/reference/java-generated#sub-builders), asking for a builder for a field adds the message.  Remember the sub message is there even it no value within it are set; all those fields will have their default values.  If you don't want to force the field to be set, you don't want to blindly fetch a Builder for it, just access the builder when setting a sub field.

Rather then setting the default instance into the field (which as mentioned likely still set it), you probably want to use the clear* method in Java to clear the field to ensure it doesn't go out.

Anyway, none of this seems to be Swift specific as much as issues on the Java side.  On the Swift side, the has* methods will tell you if the field has been set, and remember in protobuf setting a message field doesn't require the message have any sub fields also set.

**Comment by thomasvl** [comment]
Closing this out as there doesn't seem to be a issue in the library and hasn't been followup in a long while.
