### ISSUE TITLE
Avoid generating files for .protos with no messages

### ISSUE THREAD

**Issue by timburks** [apple/swift-protobuf#710]
_SwiftProtobuf 1.0.2, all platforms_

The protocol buffer language allows packages to be represented in multiple `.proto` files. With gRPC, this can result in some `.proto` files that contain no message definitions. These are likely to be mixed together with `.proto` files that do contain messages, making it inconvenient to sort them out of `protoc` invocations that call both `protoc-gen-swift` and `protoc-gen-swiftgrpc`. 

Currently `protoc-gen-swift` generates essentially-empty `.swift` files for `.proto` files with no messages. These files are harmless, but it would be useful to suppress them to reduce clutter.

```
// echo_messages.proto

syntax = "proto3";

package echo;

message EchoRequest {
  // The text of a message to be echoed.
  string text = 1;
}

message EchoResponse {
  // The text of an echo response.
  string text = 1;
}
```

```
// echo.proto
syntax = "proto3";

package echo;

import "echo_messages.proto";

service Echo {
  // Immediately returns an echo of a request.
  rpc Get(EchoRequest) returns (EchoResponse) {}
  
  // Splits a request into words and returns each word in a stream of messages.
  rpc Expand(EchoRequest) returns (stream EchoResponse) {}  
  
  // Collects a stream of messages and returns them concatenated when the caller closes.
  rpc Collect(stream EchoRequest) returns (EchoResponse) {}
  
  // Streams back messages as they are received in an input stream.
  rpc Update(stream EchoRequest) returns (stream EchoResponse) {}
}
```

```
// generated echo.pb.swift (with license header removed)
import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that your are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}
```

**Comment by thomasvl** [comment]
So not generating a file will make it really hard to for someone to hook into a build system, as just about every build system expects an output (or multiple) for every input.

I also wonder if we didn't generate something, would this be confusing to someone new to protos, they keep trying to generate off a set of files and one output just keeps not showing up?

**Comment by thomasvl** [comment]
@timburks since you mentioned `service` directives here, how would this get used for something like grpc?  i.e. - how would you make your build system/rules know when files will or won't be created?

**Comment by timburks** [comment]
@thomasvl This is a more glaring issue for the gRPC plugin than swift-protobuf. For example, to call the Google Natural Language API, I might run the language_service proto through protoc along with its dependencies: api/annotations.proto, api/http.proto, and protobuf/descriptor.proto. That would generate all the needed .pb.swift files, but the grpc code generator would produce three empty files. Generating empty files is probably indeed better for build systems, but I don't think that it's better for humans (especially new users, which I think would be confused or annoyed by empty output files).

We could get both behaviors by adding an option, but I'm generally opposed to options and would prefer that we not do that.

Since filing this, I've realized that we could also resolve this by merging the grpc and protobuf plugins into one.  That would probably be too inflexible for both projects, but we could get the same effect by having one of the plugins call the other and merge their output. If you want to do that in swift-protobuf, keep this issue open, or if not, feel free to close this and we'll add that to the grpc-swift plugin.

**Comment by thomasvl** [comment]
I can't say I've used it, but there is some support for running two plugins and combining the results.

[`GeneratorContext:OpenForAppend()`](https://github.com/google/protobuf/blob/master/src/google/protobuf/compiler/code_generator.h#L133-L134) could be used by the grpc plugin to just add things to the end of the files that have services.

[`GeneratorContext:OpenForInsert()`](https://github.com/google/protobuf/blob/master/src/google/protobuf/compiler/code_generator.h#L136-L143) is more experimental, but we could add insertion points to the Swift code and then you could inject into different areas of the files to provide better structure.  There is a little more details about how this works under the hood in [plugin.proto](https://github.com/google/protobuf/blob/master/src/google/protobuf/compiler/plugin.proto#L124-L161).

If you do some code searching, you'll find some tests around insertions, and I think maybe java ensure it supports it, so maybe something like grpc is using this approach already for that language.  C++ certainly includes a bunch of insertion points in the files they generate.

I'll go ahead and close this because from a build system pov even it it were an option, it quickly gets hard to automate anything around sometimes making files.  If insertion points end up being something interesting, open a new issue and we can add some logical ones.

**Comment by timburks** [comment]
SGTM. I did a quick test and found that the Swift compiler would build concatenated pb+grpc files, so as long as there are no import conflicts (and there shouldn't be), insertion points probably won't be necessary.

**Comment by tbkka** [comment]
A few comments related to this:

I looked at including insertion point markers in SwiftProtobuf output, but didn't have a driving use case to inform that effort.  If someone has such a use case, it would be easy to do.

Part of the reason we exposed SwiftProtobufPluginLibrary was to make it easy for tools like gRPC to just re-use our logic for generating output file names, class names, method names, etc.  We can further expand that if it simplifies interoperation among tools.  For example, if gRPC wants to know if a particular SwiftProtobuf output file is essentially empty, we could probably expose something to allow it to query that.

We've discussed having SwiftProtobuf generate more than one output file for each input file.  The idea would be to make it easy for users to trim their binaries by simply discarding files with functionality they don't need (e.g., the additional field and type names needed by JSON or TextFormat support).  We could also do this by having an option &lt;sigh&gt; to suppress these capabilities, but I'm not a fan of options.

Mostly-empty output files should not add a lot of compile time.  I'm reluctant to complicate build system integration for such a modest benefit.  If it helped, we could of course optimize this case so such files were really entirely empty instead of just mostly empty.
