### ISSUE TITLE
Error --swift_out: protoc-gen-swift: Plugin killed by signal 6.

### ISSUE THREAD

**Issue by Tawfikk** [apple/swift-protobuf#725]
❌ When i try to convert .proto file via `protoc --swift_out= DriveAuth.proto`, i get the follow error

> --swift_out: protoc-gen-swift: Plugin killed by signal 6.

 ![screen shot 2018-02-27 at 22 53 35](https://user-images.githubusercontent.com/28268405/36751377-16499332-1c11-11e8-88fc-108e862846a3.png)

How fix this error ?  Thanks 🙏

**Comment by thomasvl** [comment]
How did you install the Swift plugin?  Sounds like maybe it is linked with a different runtime version?  Maybe revisit https://github.com/apple/swift-protobuf#building-and-installing-the-code-generator-plugin ?

**Comment by Tawfikk** [comment]
@thomasvl thanks for answer. I solve this problem by reinstall protobuf via homebrew  ✅

**Comment by tbkka** [comment]
For anyone else who stumbles across this:  This is currently expected behavior whenever you upgrade Xcode.  Swift does not have a stable library ABI today, so upgrading Xcode will change the Swift libraries, which currently requires recompiling any Swift code.

Swift 5 is supposed to stabilize the library ABI which will stop this kind of breakage.
