### ISSUE TITLE
Proposal:  Move `descriptor` to SwiftProtobuf library for general use

### ISSUE THREAD

**Issue by basalphenaar** [apple/swift-protobuf#727]
OS: macOS 10.13.3
Xcode version: 9.3 beta 4
Swift version: 4.1
SwiftProtobuf version: 1.0.3

I previously posted this issue in the grpc-swift project ([here](https://github.com/grpc/grpc-swift/issues/179)) but MrMage referred me to the swift-protobuf project since I mistakenly assumed it was a problem with grpc-swift.

In a *.proto file we are defining a custom method option in the following way:
```
extend google.protobuf.MethodOptions {
    bool requiresAuthentication = 50001;
}
```
When generating the Swift code an import for `SwiftProtobufPluginLibrary` is missing in the generated *.pb.swift file. `Google_Protobuf_MethodOptions` is being extended in the generated code but it is being marked as an undeclared type until I manually import `SwiftProtobufPluginLibrary` in addition to the already imported `SwiftProtobuf`. This is fixing the issue but since ideally the generated code is never modified manually this is not a great solution.

Is this a known issue and/or has somebody encountered this issue before?

**Comment by MrMage** [comment]
Maybe you'd need to instead compile the proto file that contains `google.protobuf.MethodOptions` yourself, so that the generated code for that message is part of the same compilation unit as the extension? (Not sure about that, though.)

**Comment by basalphenaar** [comment]
@MrMage I think I know what you mean, I'll try that!

I successfully replicated this issue with the [Echo](https://github.com/grpc/grpc-swift/tree/master/Examples/Echo) example of the grpc-swift project (on commit `cacc80d`). The project compiles fine until I add the following to the `echo.proto` file and regenerate it with `protoc echo.proto --swift_out=Generated --swiftgrpc_out=Generated`:
```
import "google/protobuf/descriptor.proto";

extend google.protobuf.MethodOptions {
    bool myMethodOption = 50001;
}
```
After this Xcode starts complaining with the message `Use of undeclared type 'Google_Protobuf_MethodOptions'`. This is because the generated `echo.pb.swift` file now contains the following:
```
extension Google_Protobuf_MethodOptions {

  var myMethodOption: Bool {
    get {return getExtensionValue(ext: Extensions_myMethodOption) ?? false}
    set {setExtensionValue(ext: Extensions_myMethodOption, value: newValue)}
  }
  /// Returns true if extension `Extensions_myMethodOption`
  /// has been explicitly set.
  var hasmyMethodOption: Bool {
    return hasExtensionValue(ext: Extensions_myMethodOption)
  }
  /// Clears the value of extension `Extensions_myMethodOption`.
  /// Subsequent reads from it will return its default value.
  mutating func clearmyMethodOption() {
    clearExtensionValue(ext: Extensions_myMethodOption)
  }
}
```

**Comment by MrMage** [comment]
Yes, but if you include `google/protobuf/descriptor.proto` in the files that you ask `protoc` to compile for you, the issue should go away. Again, not sure if this is good practice, someone from the swift-protobuf team might be able to chime in on that.

**Comment by basalphenaar** [comment]
@MrMage It looks like I'm doing that by adding `import "google/protobuf/descriptor.proto";` to `echo.proto`, please correct me if I'm wrong about that though.

**Comment by MrMage** [comment]
AFAIK, that only makes the proto compiler find the dependencies (like a header file), but does not generate code for that file. Don't ask me how to best generate code for that proto file apart from copying the file into your directory, though.

**Comment by tbkka** [comment]
You'll need to also compile `google/protobuf/descriptor.proto` itself and add it to your project.

Since `descriptor.proto` is not part of the protobuf spec per se, we decided to omit it from the core SwiftProtobuf library.  For now, users who need it can simply compile it themselves and add it to their projects.

**Comment by pasdam** [comment]
Maybe I'm missing something, but if manually including `SwiftProtobufPluginLibrary` in the generated code makes the project compile correctly, doesn't that mean that the swift code of `descriptor.proto` is already in the library? Why should I generate its code again?
Also, with other languages (i.e. java or go) it's not necessary to do so.

Anyway, I can confirm that manually compiling `descriptor.proto` and adding `descriptor.pb.swift` to the project works.

**Comment by tbkka** [comment]
> ... that the swift code of `descriptor.proto` is already in the library?

Not in the `SwiftProtobuf` library, which is the only one intended for general use.

`SwiftProtobufPluginLibrary` is very specialized and should only be used by people who need to generate code that uses the same conventions as the `protoc-gen-swift` tool.

**Comment by pasdam** [comment]
Well, I'm not using it extensively, but it compiles without any problems. Although I have to say that I'm referencing to that option only in the Java code, and not from Go.

**Comment by tbkka** [comment]
I've renamed this since the real issue seems to be whether the `descriptor` types should be generally available in the SwiftProtobuf library.

In particular, I'm not sure this is really tied to the question of whether we should embed descriptors in the generated types.  There seem to be a few people using the `descriptor` types for other purposes.

**Comment by thomasvl** [comment]
Folks that have run into needed the generated code from `descriptor.proto`, can you chime in on #751 with a pointer to what your proto files looked like that needed the descriptor object?  I'm wondering if rather then blinding shipping it we should be doing something to help drop the need for it instead since SwiftProtobuf doesn't currently vend descriptor data at runtime, so I'm not sure that folks actually need the extensions they are generating via the descriptors.

**Comment by rls-vault** [comment]
Good afternoon,
I am looking for a bit of insight into working with KeyNote files (~2017  ver 8.x) .  My objective is fairly basic.   I just want to extract the text and images from about 3000 KeyNote files.  I am working in Python 2.7 due to the age of many of the tools, but I would like to upgrade to 3.x or 4.x eventually.
Despite a lot of reading and experimenting I seen to have hit a wall extracting messages from the IWA objects.

I have been experimenting with various approaches and have gone as far as trying to manually deconstruct the IWA files by hand using the protobuf encoding infromationan something just does not add up.  This was 100% for a generic Protobuf constructed message, but failed for the .IWA files.

What I **think** I know.
1/ The .key files are a grouping of objects that are zipped and can be unzipped using Snappy or a generic module like zipfile. 
Once unzipped, the key file can be separated giving access to the/index branch and constituant IWA objects. 
2/  The IWA files have a 4 byte little endian header, and the rest should follow the [google protobuf encoding](https://developers.google.com/protocol-buffers/docs/encoding).  
3/  The protobuf encoding does hold for some aspects of the IWA files.  e.g recognized blocks of text have the correct tags.  However other parts of the IWA does not seem to follow the rules either resulting in invalid wire-type codes (e.g. wire-type=6 ) or,  field numbers are zero or are reused.  
 
What I would appreciate is if : 
A/ Someone could confirm that the KeyNote encoding does comply with the Google protobuf encoding, or point me at a valid encoding schedule or scheme that I can use.

B/ Someone could clarify if the IAW objects are or are not individually compressed in addition to the compressing applied to the whole .key file.  The documentation is unclear and my attempts to further decompress the IWA objects were not successful.

C/ Someone could direct me to a functional Python library that can extract data from KeyNote files. 
{_As much as I am having fun playing with file deconstruction at the byte and bit level, I still have an objective to achieve :-)_   }

Thank you.
Russell
Any direction gratefully accepted

**Comment by MrMage** [comment]
@rls-vault I would recommend posting that in a separate issue (or posting it in the SwiftProtobuf section of forums.swift.org, or even StackOverflow), as it's probably not related to this issued .

**Comment by ddunbar** [comment]
@thomasvl A good example of a proto that cause this problem is in use of Google's own long running operation type: https://github.com/googleapis/googleapis/blob/master/google/longrunning/operations.proto

What do you think the right answer is here -- is clients duplicating the compilation of these protos really the right answer?

**Comment by thomasvl** [comment]
@ddunbar that's part of what this and things like #751 were asking.  Since the common need is just for options, and options aren't captured in the library's current support, if we could find a way to filter those away, it wouldn't be needed and folks wouldn't have to generate it.

Just shipping it also dodges the issue, but at the cost of the library size.  The catch being shipping it might count as a breaking changes since folks also generating it themselves would need to stop doing that also.

@tbkka thoughts?  I can likely do a reasonable small change to lump this into the library and move things along, we'd just need to decide what we want to do version wise to cover this change.

**Comment by tbkka** [comment]
Yes, I think we should move `descriptor` into the main SwiftProtobuf library (and out of SwiftProtobufPluginLibrary).  I'm less certain about _generating_ embedded descriptors, but that's a different issue with different trade-offs.

Versioning is a tricky question.  Our promise so far has been that within any major version we would preserve backwards compatibility at the source level and would preserve both backwards and forwards compatibility between the generated code and library.  Adding `descriptor` to the library does not technically violate those promises.  So while I do have some slight misgivings, I think it's okay for a minor version update.

**Comment by thomasvl** [comment]
Ok, will work on the changes today/tomorrow.

**Comment by ddunbar** [comment]
@thomasvl verified this resolves the issue, thanks!
