### ISSUE TITLE
Add helpers for length delimited binary format

### ISSUE THREAD

**Issue by HaijunWei** [apple/swift-protobuf#754]
Hello. I use `.serializedData()` and `init(serializedData:)` can convert to each other. but I can't deserialization data from the server. An `truncated` error occurred here.

I use objective-c library `Protobuf`(https://github.com/google/protobuf). It works.
In `Protobuf`. I user `.delimitedData()` and `.parseDelimited(from: , extensionRegistry:)`.

Is there a similar method in this library?  Please help me.  thanks.

**Comment by thomasvl** [comment]
We currently don't have an API for parsing length delimited messages as it isn't really part of the "spec" and more something that a few languages have added.

**Comment by thomasvl** [comment]
btw - is there a reason you need delimited?  Since it isn't common, we haven't bothered with it.

**Comment by HaijunWei** [comment]
Because I'm interacting with the IM server. The data packet sent by the server I need to get the length to resolve. So, I use `Protobuf` library now. thanks.

**Comment by thomasvl** [comment]
Reopening since we should still add the helper.

**Comment by thomasvl** [comment]
Ugh.  So took a quick look at doing this today; and it actually doesn't seem to lead be to an obvious api solution.  Adding an api to create the delimited data is pretty easy/reasonable.  But the parsing side is where I'm stumbling.

All of our parsing interfaces right now are built around `Data`.  But having a delimited parse that takes `Data` seems odd.  The most natural form of parsing delimited data would be a from some form of input stream, that way we can parse off the varint and then the data, and leave the stream ready for the next message (or whatever else the developer needs).

But with only `Data` interfaces, how does this work?  Do we expect the length prefix to be all the remainder of the `Data`?  Or do we show how process the subset, and also return how many bytes we did consume?  That sorta model puts the developer into a mode where they have to keep reading from their source completely, then extracting the subset not yet consumed and decide how to then process that.

Do we just hold off on this until we have general parsing interfaces that work with some form of input stream since that's where delimited makes more sense?

**Comment by allevato** [comment]
`Data` is its own slice type, so we could have an API that either returns the remaining slice of `Data` as one of its results, or use an `inout Data` argument that would be overwritten after the message is parsed.

So, something like this (very rough sketch):

```swift
func parseLengthDelimited(from data: inout Data) -> Message {
    let length = /* get the length from data */
    let message = /* parse the message */
    let nextMessageIndex = data.index(data.startIndex, offsetBy: length)
    data = data[nextMessageIndex...]
    return message
}
```

**Comment by thomasvl** [comment]
Oh, good idea, that could help.  I'm drawing a blank, are there any other apis that use `inout` params like that?

I guess the one potential down side is memory costs, and if the impl retains the parent for the new slice, then as you extract messages message, you could end up with a final slice that has a lot of _parent_ data references so the whole blob is still in memory.

Oh, and the caller is still likely in a loop of something like:

```
var current = Data()
while (/*not end of input*/) {
  current = current + /* read_all_available_data */
  let msg = MyMessage. parseLengthDelimited(from: &current)
}
```

So still looping gluing together chunks of data along the way.

**Comment by tbkka** [comment]
GCD's `dispatch_data` or Swift NIO's `ByteBuffer` type might be more appropriate here.

Internally, the binary parser works with pointers and lengths directly, so it should be easy to interface to any of these as long as they can provide a contiguous view of their contents.

**Comment by thomasvl** [comment]
How quickly I forget what I've done in the past…

We added a `BinaryDelimited` enum to namespace some helpers:

serialize: https://github.com/apple/swift-protobuf/blob/master/Sources/SwiftProtobuf/BinaryDelimited.swift#L32-L53
parse: https://github.com/apple/swift-protobuf/blob/master/Sources/SwiftProtobuf/BinaryDelimited.swift#L79-L101
merge: https://github.com/apple/swift-protobuf/blob/master/Sources/SwiftProtobuf/BinaryDelimited.swift#L117-L148
