### ISSUE TITLE
A Bug or Capitalization Rules

### ISSUE THREAD

**Issue by perlmunger** [apple/swift-protobuf#795]
My proto file has the property "CustomerPO". The PO is only init capped after the compiler finishes which means it ends up as "customerPo". What are the rules behind this? Is there a setting or option I can use to force it to result in "customerPO" or is this by design?

Thanks.

**Comment by thomasvl** [comment]
The generator tries to convert proto files written to the [protobuf style guide](https://developers.google.com/protocol-buffers/docs/style) into more "swifty" objects.  According to the style guide; Message and Enum names are supposed to be CamelCase, so left are left as is.  Field names are supposed to be underscore_separated_names and enum cases are CAPITALS_WITH_UNDERSCORES.

So the generator attempts to transform the last two by removing underscores and modifying the capitalization to hopefully end up something that feels right when writing Swift code.  The generator does try to use cases where it sees repeated uppercase letters to help figure out where "segments" are, but it does still downcase things after the first character of each segment (with one exception around a some special things (URL, HTTP, HTTPS, ID), trying to match Apple's naming guidelines there.

There are no compiler options for field/field options around the behavior.  For the most part we try to avoid options because it can lead to one project setting an option one way and another project setting it another way and when they both need the same protos, the need suddenly can't be resolved.

**Comment by perlmunger** [comment]
Ok. Thanks for the feedback @thomasvl. That's helpful. I have a workflow where I have a parser of my own that uses the .proto file as a spec to create Realm.io objects and I'm attempting use the same conventions in my parser so that I don't have to edit the output it generates. The developer who generated the .proto and who works on the server side is using different conventions as he is using a C# protocol buffer library. I'll talk with him and see if we can use a convention that will get translated directly so that I don't have to correct for slight capitalization differences every time my parser runs.

Thanks again.
