### ISSUE TITLE
Allow to use UNKNOWN case instead of unrecognizedEnumValue

### ISSUE THREAD

**Issue by geor-kasapidi** [apple/swift-protobuf#799]
Now in JSONScanner error will be return if enum case in unknown.

Propose - add setting to JSONDecodingOptions (ex. ignoreUnknownEnumCases) to return .UNKNOWN case instead of error.

Xcode 10, Swift 4.2, SwiftProtobuf - 1.1.2

**Comment by thomasvl** [comment]
I don't think any other languages provide an option for that, and I'm not immediately sure it would be a good thing since changing the enum value like that could put the message in an odd state (depending on how the enum field relates to other fields).  Since proto3 syntax enums support unknown values, it seems like if you need to deal with unknowns, binary might be a better format to use than json?

**Comment by geor-kasapidi** [comment]
It turns out that the behavior is different: in case of json representation of model we have an error, with binary representation - it's ok.

For example, our testers use json transport to validate server data. And we use different inits on SwiftProtobuf.Message for that:

```
extension SwiftProtobuf.Message {
    public init(data: Data, useJSON: Bool) throws {
        if useJSON {
            try self.init(jsonUTF8Data: data)
        } else {
            try self.init(serializedData: data)
        }
    }
}
```

**Comment by thomasvl** [comment]
> It turns out that the behavior is different: in case of json representation of model we have an error, with binary representation - it's ok.

Right, in binary form, we have the raw value and so it can still be modeled.  If you decided to use JSON it can't handing unknown fields or enum values.  That's one of the major limitation of JSON.  If you want to better support your protos evolving with time, binary is the format to use.

**Comment by thomasvl** [comment]
Looks like C++ has picked up an option to use the raw values instead of the names when generating JSON (https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/util/json_util.h#L67-L69), so it might make sense to add that to allow the data to better flow thru JSON.  That seems safer that an option to ignore unknown json enum names (which I still can't find anything else supporting).

**Comment by tbkka** [comment]
I remember implementing support for numeric enums in the decode side -- it's required by the conformance test.   Looks like it even supports unknown values:
   https://github.com/apple/swift-protobuf/blob/a1b3a3a7d458f0a0ac0afb7e61baaac5675c8d63/Sources/SwiftProtobuf/JSONScanner.swift#L1284

So it should only require a little work on the encoder to expose this there.

**Comment by tbkka** [comment]
I don't think we can implement the original request here since we don't have an `.UNKNOWN` case  for enums and I'm reluctant to add one.

It might be reasonable to have an option to ignore unknown string-encoded enums (that is, to simply drop them entirely) rather than throw an error.  I'm concerned about the implications for repeated enum fields, though.

Mostly, I think this raises a question about our error reporting.  A long time ago, I considered trying to implement detailed error codes so that failures would detail the field where the problem occurred:  E.g., `.unknownEnumValue("msg.submsg.field1")`

**Comment by thomasvl** [comment]
Got to go ahead and close this off with #800 added a way to do JSON generation that should handling new enum values slightly better if folks really want to try to use JSON (over binary) when this is a concern.  We can always revisit if other languages also consider an option on the parsing side, but for now we'll stick with it being an error since it isn't clear how well things would work and it would be silent to callers when things are dropped.
