### ISSUE TITLE
Incorrect has property set to true, while it must crash or set to false

### ISSUE THREAD

**Issue by Jasperav** [apple/swift-protobuf#814]
Developing on the most recent swift-protobuf version and toolchain snapshot of xCode of 30 november, I am scratching my head of the proces of encoding/decoding messages. I asked it on SO also: https://stackoverflow.com/questions/53585206/protobuf-incorrectly-returns-true-for-a-property-that-hasnt-been-decoded. This is the content of the question:

This are my protofiles:

    message ChatJoinReq {
        string other_user_identifier = 1;
        int32 message_request_count = 2;
    }

    message ConversationListReq {
        Location location = 1;
        uint32 conversation_request_count = 2;
    }

    message Location {
        double latitude = 1;
        double longitude = 2;
    }

This is how I create a request for a `ChatJoinReq` object

    var chatJoinReq = Benji_Client_ChatJoinReq()

    chatJoinReq.otherUserIdentifier = "ullam"
    chatJoinReq.messageRequestCount = 1

    let data = try! chatJoinReq.serializedData()

I am very surprised that this evaluates to true:

    let message = try! ConversationListReq(serializedData: data)
    print(message.hasLocation) // true

How? It happens for some names (including 'ullam'). When I change the name to 'test', it crashes because it can't encode the message (which is good! Or, hasLocation should evaluate to false).

Why does 'ullam' can be encoded and the message has the property `location` explicitly setted?

**Comment by cburrows** [comment]
Jasperav, you're encoding from one message type and decoding to another. You should know that binary protobuf encodings are not self-describing: they don't contain information about their message types except insofar as is necessary to pack/unpack some very basic data types.

In your case, field 2 in one message is a string, and an the other is an embedded message. Turns out, both of them have an encoding which is simply length-delimited. If you pick the right string in message 1 you can make it look like a message, or not. As you've observed, different strings contents produce different results.

If I were you, I would refer to https://developers.google.com/protocol-buffers/docs/encoding and see what you think the bytes from "ullam" and "test" would map to in terms of protobuf binary.

There is no guarantee that doing what you're doing should or should not crash. The binary can coincide by accident, or not, intentionally, or not, depending on your data. In your case, it looks like "by accident" and I would stop doing what you're doing.
