### ISSUE TITLE
Warning 'Hashable.hashValue' is deprecated on Swift 4.0

### ISSUE THREAD

**Issue by pffan91** [apple/swift-protobuf#871]
* macOS 10.14.4
* Xcode 10.2.1 Build version 10E1001
* Swift 4.0
* 1.1.2 (but looks like the same issue will be reproducible on the latest 1.5.0 version too)
* 'Hashable.hashValue' is deprecated as a protocol requirement; conform type 'My_Object' to 'Hashable' by implementing 'hash(into:)' instead

When compiling my project I receive many warnings:

```
'Hashable.hashValue' is deprecated as a protocol requirement; conform type 'My_Object' to 'Hashable' by implementing 'hash(into:)' instead
```

So my question - is there are any reasons to use the old `hashValue` function on Swift 4.0? Because I've changed `#if swift(>=4.2)` to `#if swift(>=4.0)` for example in the `Message.swift` class (and some other classes) and all works correctly and Xcode warnings was gone. So why not to fix it in future versions? If you agree with that - I will send PR. Thank you for your response!

**Comment by thomasvl** [comment]
Os there a reason you are using Swift 4 instead of 4.2 or 5?  If you move your Swift language version up the issue should go away.

That warning also sound like it might be mistake/bug on the compiler side.  https://github.com/apple/swift-evolution/blob/master/proposals/0206-hashable-enhancements.md says the changes went into Swift 4.2.  It may that since your are using the 5.0 toolchain in 4.0 mode, it is providing a false signal; but if you used a real 4.0 toolchain, it wouldn't know about the hashing changes.

**Comment by pffan91** [comment]
Great, @thomasvl thank you for explanation!

P.S. There are many local dependencies that was written on Swift 4 so we are still using it..

**Comment by thomasvl** [comment]
> P.S. There are many local dependencies that was written on Swift 4 so we are still using it..

Since the 4.x range, you should be able to mix language versions, i.e. - one dependency can be compiled with 4, but you can compile with 4.2 or 5 just fine.  https://docs.swift.org/swift-book/GuidedTour/Compatibility.html

**Comment by pffan91** [comment]
Yep, we should check this
Thank you!
