### ISSUE TITLE
Message field count

### ISSUE THREAD

**Issue by GiacomoLeopizzi** [apple/swift-protobuf#874]
Hello there!

I was wondering if would be complex to add a static variable that contains the number of fields in the proto message. 

For example in the message:

message Example {
bytes data = 1;
string string = 4;
}

In swift Example.fieldsCount would be 2.

I think that could be useful to implement unit test to enforce some safety checks (custom user validation for every field, cause maybe you added a field but you forget to add the proper code to validate the content).

Kind regards,
Giacomo

**Comment by thomasvl** [comment]
Most of the proto libraries capture this sorta info in a _descriptor_ object that allows more dynamic/reflective operations on messages at runtime.  We've held off on adding this as Swift hasn't fully decided on what reflective abilities it will provide itself.  But it still likely makes sense to avoid adding something like this until those decisions are made since once something is added to the library, it can't be removed without breaking things.

**Comment by GiacomoLeopizzi** [comment]
Oh I get it!

**Comment by GiacomoLeopizzi** [comment]
Oh I get it!
But the information that this variable would carry has a static nature so a dynamic/reflective object would add a lot overhead for a simple operation. The same should be for the `protoMessageName` variable. And in the worst case scenario the @available(*, deprecated) could be used.

**Comment by thomasvl** [comment]
The api doesn't have to be reflective, but the objects used for those sorta things is where this data should be exposed.  Everything that gets directly exposes from the message types eats away at the namespace available for the fields, so there has to be really good reason to add them.

Also, without reflective apis, what would one actually do with this value?  Sure you could tell it had 2 fields, but you can't tell what they are, what their types are, so what is the value of it?

**Comment by tbkka** [comment]
I think the real issue with descriptors is simply code size.  I recently noticed the `optimize_for` option -- I think we could implement that pretty simply:
```
   option optimize_for = SPEED;  // Default, include JSON, Text, and Descriptors
   option optimize_for = CODE_SIZE;  // Swift: Omit JSON, Text support and Descriptors
   option optimize_for = LITE_RUNTIME; // Swift: Omit JSON, Text support and Descriptors
```
Obviously, we don't have a "Lite" runtime library today, but our current code architecture would make it easy to create one that omitted the JSON and Text support bits.  We could then add the `descriptor` proto to the regular full library only.

**Comment by thomasvl** [comment]
@tbkka google's protobuf teams are moving away from those options, because they fail to deal with someone having two dependencies on protos and those two things having picked different options for those values (especially if they result in slightly different feature sets).

Adding _descriptors_ here isn't just capturing the binary blob, that would likely be needed, but it also the whole `Descriptor` object types from C++ (not the ones generated from `descriptor.proto`), but all the code to support inspecting field types, acting on message fields generically, etc.  Without the Swift reflection story finalized, we'd likely be rebuilding a lot of the same sorta plumbing (if it is even possible with the current public information expose for structure layout, etc.).

**Comment by GiacomoLeopizzi** [comment]
@thomasvl The idea of use I had for it was I could use it to decrease a counter of validations that if not zero at the end could assert (cause would mean a field has been added in the .proto but it's not validated in swift). But I totally get your point about the logical collocation for it!
