### ISSUE TITLE
Add Support for Google Speech "StreamingRecognizeRequest" delimiter format

### ISSUE THREAD

**Issue by lassejansen** [apple/swift-protobuf#885]
The Google Speech-to-Text API uses a fixed length delimiter for sending streaming audio snippets instead of the VarInt encoding that is used in BinaryEncoded#serialize.

I didn't find any documentation for the delimiter format, but it seems to be a leading zero with a big endian UInt32. I added it manually in my project but it may be an idea to provide this as an option to BinaryEncoded#serialize.

Documentation:
https://cloud.google.com/speech-to-text/docs/reference/rpc/google.cloud.speech.v1#google.cloud.speech.v1.StreamingRecognizeRequest

Example code for serializing:

 ```swift
 func delimitedMessage( _ message: SwiftProtobuf.Message) throws -> Data {
    let serialized = try message.serializedData()
    return Data([0x0]) + bigEndianEncoded( UInt32( serialized.count)) + serialized
  }
  
  func bigEndianEncoded( _ value: UInt32) -> Data {
    var v = value.bigEndian
    let n = MemoryLayout<UInt32>.size
    var data = Data(repeating: 0, count: n)
    data.withUnsafeMutableBytes { bufferPointer in
      let baseAddress = bufferPointer.baseAddress!
      baseAddress.copyMemory(from: &v, byteCount: n)
    }
    return data
  }
```

**Comment by thomasvl** [comment]
So I'm not seeing what part you are talking about in the linked docs.

Normally, in a protocol buffers context, delimited messages refers to encoding a length as a varint, followed by the message.  This provides the framing so as long as you know the types, you can parse a sequence of them.  The library does provide helpers for write/read/merge - https://github.com/apple/swift-protobuf/blob/master/Sources/SwiftProtobuf/BinaryDelimited.swift#L18

**Comment by lassejansen** [comment]
It doesn't seem to be documented. I found out by analyzing the traffic from the ruby grpc implementation:
https://github.com/grpc/grpc/tree/master/src/ruby

The Google Speech API with gRPC does not use a varint, but a fixed length int instead. I tried to use the BinaryDelimited methods, but they didn't work. I had to use the method from my previous post.

**Comment by thomasvl** [comment]
Does the swift grpc library support this?  I'm wondering if this is something grpc specific layered on top of protobuf, so it might make sense for any standard support to live there instead.  The delimited support we have does exist in other language implementation of protobuf (it is why we added it), but I'd a little hesitant to add something that is a one off since it could confuse things given the overlap with the other _delimited_.

**Comment by allevato** [comment]
What you're describing is the gRPC wire format (search for "Length-Prefixed-Message" [here](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md)). The leading zero you mention is a compression flag, followed by a big-endian 32-bit integer for the length of the message, then the message itself.

So, you probably want to be using [grpc-swift](https://github.com/grpc/grpc-swift) to process this stream, rather than reading bare protos from the wire yourself.

**Comment by lassejansen** [comment]
I tried to use grpc-swift, but didn't get it to work. There were no error messages, just no response and I could not get it to use my network proxy for debugging.

I use URLSession at the moment and it works pretty well. Regarding the compression flag, is it possible to force the server to send responses uncompressed? Maybe with an Accept-Encoding header?

**Comment by allevato** [comment]
I'd recommend asking on a grpc-swift forum or issue tracker why your code wasn't working, rather than trying to hack it together with just SwiftProtobuf. Since the API in question is using gRPC, even if you're able to disable something like compression (I'm not sure if this is possible or not), any attempts to roll your own "lite" version of that protocol will be fragile and might break later if the server (rightfully) assumes that it can send you anything that's valid gRPC wire format that you don't handle.
