### ISSUE TITLE
Split strings off visitor pattern

### ISSUE THREAD

**Issue by thomasvl** [apple/swift-protobuf#9]
Look at moving the string args off the visitor method (just field number and values).  Then update the things that need the strings can use the maps between strings:field numbers to do the lookup instead.

The string based things will end up a little slower, but it should help shrink the generated code sizes as well as speed up the binary format (since it won't have to pass unused arguments all the time).

**Comment by thomasvl** [comment]
Can likely prototype this with something like:

```swift
extension ProtobufVisitor {
   func visitXyz(… protoFieldNumber: Int) {
       visitXyz(… protoFieldNumber: protoFieldNumber, protoFieldName: “”, jsonFieldName: “”, …)
   }
}
```

To keep the non binary stuff going while seeing how it it affects perf numbers.

**Comment by allevato** [comment]
I locally modified the runtime to add the extensions above and the generator to stop emitting the strings in the visitation methods (and to also unconditionally emit `jsonFieldNames` and `protoFieldNames` as empty dictionaries).

Quick analysis—for a message with 100 fields, the sizes before/after stripping were 415960/153264 bytes with the strings included. With the strings excluded, the sizes before/after stripping were 399936/137080 bytes. So, a difference of 16024/16184 bytes, resulting in a savings of ~160 bytes per field. (Each of the fields in this case would have had names 5–7 characters long.)

16KB for 100 fields is nothing to sneeze at, since that will only get larger if a binary has a large number of messages/fields compiled into it. This is roughly the savings someone would see if we segregated the text/JSON support into separate extensions and they excluded it from their build, so it looks like this is worth pursuing.

**Comment by thomasvl** [comment]
Did you happen to run any performance numbers?  I would hope not pushing the extra args would also speed things up.

**Comment by tbkka** [comment]
Obvious Question:  Can we easily reduce that overhead?

For example, I've long wondered if it would help to declare a single property with lists of the raw data:
```
   static let fieldNames: (Int, String, String, String) = [(1, "protoName", "jsonName", "swiftName"), ...]
```
and then build the lookup tables from that in a protocol extension:
```
   static let jsonFieldNames: [Int:String] = { ... compute dict from fieldNames ...}()
```

There's some work to make sure the computed properties here have lazy compute-once semantics, but it seems this might reduce the duplicated strings, consolidate the code to build the dictionaries, and therefore reduce the overhead quite a bit.

**Comment by allevato** [comment]
There's a negligible difference between the two, execution-time-wise. In fact, the one without the extra args was slightly slower—I doubt the extra hop from the string-less function to the one taking the empty strings was enough to have a significant effect, so it may have just been noise that falls within normal variation.

I wouldn't expect not passing the strings to speed things up *that* much, since it's just pushing pointers to static strings onto the stack; a small number of instructions. But the win here is shaving off space for people who only need binary support by separating JSON/text into extensions.

**Comment by allevato** [comment]
If we keep the text and JSON names together and inseparable like that, then there's no way to separate them out for clients who only need one or the other. Instead, my thought was that each serialization format would have its own map from field numbers to names, for example:

```swift
protocol ProtobufJSONSerializable {
    static var jsonFieldNames: [Int: String] { get }
}
protocol ProtobufTextSerializable {
    static var textFieldNames: [Int: String] { get }
}
```

Then the generated extensions would populate those as necessary. If the JSON visitor/decoder is constrained to a message type `M: ProtobufMessage & ProtobufJSONSerializable`, then it can access the names via `M.jsonFieldNames`.

Although, as I write it, I realize we'll need a bidirectional mapping because encoding will go in one direction and decoding in another. But that's a finer detail—the important thing to do here is to get this kind of separation into the design so that we can let the protocols do the heavy lifting for us.

**Comment by tbkka** [comment]
Any progress on this?  I thought I might look at it some as part of rethinking the core protocol structure.

**Comment by allevato** [comment]
Nothing major; I'm still getting caught up on other projects after my vacation and the huge size of my optional-property PR was effectively blocking anything else I wanted to look at. Feel free to poke at it if it helps with the other work you're doing!

**Comment by tbkka** [comment]
Since this would affect the API between the generated code and the library, I've labelled it accordingly.
