### ISSUE TITLE
Suggestions on handling types not in the protobuf spec?

### ISSUE THREAD

**Issue by GalCohen** [apple/swift-protobuf#929]
I'd like to use more strict types that are backed by strings for representing fields, like the `URL` type. 

I realize that if it's not in the protobuf spec it's not supported... but I'm curious if you guys have some solutions / design patterns for this. My thinking is a type for serialization that then gets converted to another type that contains the special fields, but that seems like a lot of extra work mapping the fields from one object to another...  

Any other suggestions for handling this sort of thing?  Thanks!

**Comment by tbkka** [comment]
The most robust approach I've seen is to "wrap" the generated type.  That is, define a struct that contains the generated message type and provides customized accessors.

To be concrete, suppose you want to share a _request_ data structure between server and client.  You could define `message RequestProto` in your proto file and a separate `struct Request` in your Swift code.  You could then decode like this:
```
  let encoded: Data = ...
  let raw = try RequestProto(serializedData: encoded)
  let request = Request(wrapping: raw)
```
With this approach, your `Request` can delegate and convert representations as necessary:
```
struct Request {
  private var wrapped: RequestProto
  init(wrapping: RequestProto) {
     wrapped = wrapping
  }
  public var url : URL {
     get { return URL(wrapped.urlString) }
     set { wrapped.urlString = newValue.asString }
  }
}
```

That can be a lot of work if you have to provide delegating accessors for every field.  A simpler but slightly less robust approach is to extend the generated type with additional accessors for the same data.  This allows you to provide simplifying accessors for specific fields without having to delegate everything:
```
extension RequestProto {
  public var asUrl : URL {
    get { return URL(self.urlString) }
    set { self.urlString = newValue.asString }
  }
}
```
This approach is less robust because it doesn't hide the raw `urlString` field; it just provides an alternate way to get/set it.

**Comment by GalCohen** [comment]
Thanks, I like that approach. It does, however have another downside: 

If i could serialize directly to URL, I could fail serialization immediately on a poorly constructed URL, but with the setter/getter, I actually end up with an optional that I must bubble up throughout the code:
```
public var url : URL? {
     get { return URL(wrapped.urlString) }  //   -------->  gotta deal with the optional here :( 
     set { wrapped.urlString = newValue.asString }
  }
```

Still, it might be less maintenance than my initial approach.
