### ISSUE TITLE
Camel case naming of field variables and enum cases results in invalid Swift

### ISSUE THREAD

**Issue by jhahan** [apple/swift-protobuf#931]
* macOS 10.15.2

* Xcode 11.3 Build version 11C29

* Swift 4.2

* SwiftProtobuf 1.7.0

Camel casing the field names and enum cases when their names start with an underscore followed by a number results invalid identifiers for Swift language.

**Sample proto snippet**
```
syntax = "proto2";
option swift_prefix = "_2world";
message _2Test__Class_chekc_Any_cHANge {
    optional int32 _5while = 1;
    enum _44Enum__Type {
        _2my_type1 = 0;
        _44Enum__Type_2my_type2 = 1;
        _2my_type3 = 2;
    }
    optional _44Enum__Type __2allowed_enums = 2;
}
```
**Snippet from generated code**
```
var 5While: Int32 {                    // Invalid identifier (starts with a digit)
    get {return _5While ?? 0}
    set {_5While = newValue}
}
enum _44Enum__Type: SwiftProtobuf.Enum {
    typealias RawValue = Int
    case 2MyType1 // = 0               // Invalid identifier (starts with a digit)
    case 44Enum_Type2MyType2 // = 1    // Invalid identifier (starts with a digit)
    case 2MyType3 // = 2               // Invalid identifier (starts with a digit)
}
```
I went through the code and found that it can be fixed by updating either  the `splitIdentifier` method or the `sanitize` family of methods. There is also a method to check identifier validity (#138).

Preventing digit from inserting first in the `splitIdentifier` method or appending a leading underscore if a string starts with a digit in `sanitize` method can fix this issue. I would submit a PR for review with test cases if the more appropriate method of the above two for updating is known.

https://github.com/apple/swift-protobuf/blob/32d6b4d7830b124231d9debf3e30a4318370a4cf/Sources/SwiftProtobufPluginLibrary/NamingUtils.swift#L221

https://github.com/apple/swift-protobuf/blob/32d6b4d7830b124231d9debf3e30a4318370a4cf/Sources/SwiftProtobufPluginLibrary/NamingUtils.swift#L387

https://github.com/apple/swift-protobuf/blob/32d6b4d7830b124231d9debf3e30a4318370a4cf/Sources/SwiftProtobufPluginLibrary/SwiftLanguage.swift#L109

**Comment by thomasvl** [comment]
At the moment, we also somewhat rely on the proto files following the [protocol buffers style guide](https://developers.google.com/protocol-buffers/docs/style).  Out of curiosity, what was your original proto file that caused you to end up filing this?

One last question:

> I went through the code and found that it can be fixed by updating either the `splitIdentifier` method or the `sanitize` family of methods. There is also a method to check identifier validity (#138).

What's the reference to issue 138 here for?  That doesn't seem directly related to the text.

**Comment by thomasvl** [comment]
Currently, the only place the code does validation to ensure things are valid identifiers is when we try to shorten the enum cases (removing the prefix). In all other places, we assume that input follows the style guide.  For messages this should already be a valid identifier, for enums/cases these also should be valid identifiers.

So from a generation pov, should we validate all names to ensure they are valid identifiers?  Odds are some of these sorta cases would break for other languages also for the same reasons.

**Comment by tbkka** [comment]
As Thomas pointed out, this only affects people whose proto files violate the protocol buffers style guide.  As such, I don't have a strong opinion how we fix it as long as it doesn't inadvertently change the generated result for inputs that do follow the style guide.

I'm curious how you would suggest changing `splitIdentifier`?  I think that would be the better location if it could be done there without changing the generated code for other people.  The `sanitize` method would be safer but it doesn't know anything about the original name from the proto file so it is going to produce names that are harder for people to understand.

**Comment by jhahan** [comment]
@thomasvl I cannot share the complete file, but it looks similar to the below snippet.

**sites_idenetifier.proto**
```
enum AllowedSites {
    youtube = 1;
    _4shared = 2;
    icloud = 3;
    _4sync = 4;
}

message _4SharedProperty {
}

message SiteProperty {
   required AllowedSites site = 1;
   optional YoutubeProperty youtubeprops = 2
   optional _4SharedProperty _4sharedprops = 3;
}
```

`--java_out` and `--cpp_out` generate valid code for the above snippet. I am not sure, but the files I am trying to use exist in our codebase before any style guides are published. Is it mandatory to follow the style guide to get compiled in Swift?.

> What's the reference to issue 138 here for? That doesn't seem directly related to the text.

I referenced that issue because its issue fix introduced a method to check for a valid Swift identifier, but only for enum cases. It can validate all the generated identifiers.

**Comment by jhahan** [comment]
> I'm curious how you would suggest changing `splitIdentifier`?

Updating the digit insertion part with an empty check can prevent inserting digits in the beginning by prepending an underscore.
```diff
    if scalar.isDigit {
      if last.isDigit {
        current.append(scalar)
      } else {
-       out.append(current)
-       current = makeUnicodeScalarView(from: scalar)
+       if out.isEmpty {
+         out.append(current)
+         current = makeUnicodeScalarView(from: "_")
+         current.append(scalar)
+       } else {
+         out.append(current)
+         current = makeUnicodeScalarView(from: scalar)
+       }
      }
    } else if isUpper {
```

**Comment by thomasvl** [comment]
@tbkka @allevato thoughts in this space.

If we aren't going to assume folks somewhat follow the style guide, I believe we should do validation on everything (enums, message, enum cases, fields, extension fields), not just the initially reported things here.

It is also worth pointing out [this proposal](https://forums.swift.org/t/allow-more-characters-like-whitespaces-and-punctuations-for-escaped-identifiers/32073) is what what timely, as it would be another way to dealing with this without having to stick prefix/suffixes on these things.

**Comment by allevato** [comment]
It's been a while since I've looked closely enough at our name sanitization logic to know what it would do in cases that aren't straightforward `camel_case`, but I think it's a bit surprising that a field named `_5while` would end up having the leading underscore removed *and* the `w` uppercased. In a case like that, I would possibly expect the property name to just remain `_5while` and for the underlying storage property to be `__5while`, maybe.

I guess when we split the identifier, if the first component is empty (because the original string started with an underscore), we end up just ignoring it, and things continue fine as long as the thing after the underscore is an identifier-safe character?

A style guide is a _style guide_, but if the proto compiler/language/spec allows those identifiers to exist without emitting errors, then at a minimum we should gracefully generate something that's valid Swift, even if it's not as "pretty" as some of the nicer identifiers we could generate for names that do satisfy the style guide.

In this case, it's probably enough to just keep the leading underscore if it's present. If a field has a leading underscore in a proto, that's usually significant of _something,_ and I'm not sure we should ever be removing it.

**Comment by thomasvl** [comment]
> It's been a while since I've looked closely enough at our name sanitization logic to know what it would do in cases that aren't straightforward `camel_case`, but I think it's a bit surprising that a field named `_5while` would end up having the leading underscore removed _and_ the `w` uppercased. In a case like that, I would possibly expect the property name to just remain `_5while` and for the underlying storage property to be `__5while`, maybe.
> 
> I guess when we split the identifier, if the first component is empty (because the original string started with an underscore), we end up just ignoring it, and things continue fine as long as the thing after the underscore is an identifier-safe character?

Split basically works by using an underscore or a change from numbers/letters (or a chance in case of the letters), to decide something is a "segment", and splits on those, so `_5while` -> `["", "5", "while"]`.

As mentioned before, we currently never actually do any _identifier safe_ checks for messages, enums, or fields.  The check is only wired in when we are trying to strip enum cases down to a shortened form.  So in my mind, the question is do we want to do _identifier safe_ checks in _all_ places?

**Comment by tbkka** [comment]
I think of our current name translation as two conceptually distinct phases:  The first phase implements a simple general strategy for converting names to camel case without any detailed knowledge of Swift semantics.  The second phase sanitizes names that conflict with Swift reserved words or which violate Swift conventions.  The final result should be that any legal proto input results in valid Swift output.

In those terms, I think we can boil this discussion down to three options.  I'm currently inclined to adopt the first and third one:

General strategy adjustment #1:  @jhahan's suggestion to insert an underscore before a leading digit would be a sensible adjustment to our general camel-casing strategy.

General strategy adjustment #2:  I think @allevato made a good point about how people use underscores to flag an identifier as "significant" in some sense.  That suggests we might instead skip the camel-casing for identifiers that begin with underscores + digit.

Swift specifics:  We already feed generated identifiers through sanitization logic to ensure the final result is valid Swift.  This logic either modifies the name or uses backtick escapes to fix any problems.  I believe this would be the appropriate place to fill in the _identifier safe_ checks @thomasvl mentioned.  Since proto's identifier character set is generally a subset of Swifts, I think this would only require adjusting the `sanitize` methods to add an underscore before identifiers that have invalid first characters.

**Comment by thomasvl** [comment]
Is _Swift specifics_ your third?  So you are saying don't do your second item?

**Comment by thomasvl** [comment]
Quick comments to capture them (so I don't forget later)

- The current _sanitize_ check don't like leading underscores, is we start allowing that, we'll need to double check the current users to be sure they are still gone.
- If we start doing more changes (prefixing/suffixing) we also really need to think about what it means for interactions between fields.  We currently don't really check for this.  We also use a leading underscore in proto2 syntax for the private property that backs the fields, so that too could start to conflict.

**Comment by thomasvl** [comment]
And I've been shown some other proto files that don't follow the style guide, so odds are we need to do better validation/sanitation across the board.

So, I'll look at cutting a release with the current changes on master, then we can look at making changes to ensure we always get valid identifiers, pending what that results in, we'll see if it means a version break or what.
