### ISSUE TITLE
Enum fields are not emitted in message

### ISSUE THREAD

**Issue by eutampieri** [apple/swift-protobuf#933]
* OS: macOS 10.14.6
* Xcode version: Version 11.3 (11C29) (`xcodebuild -version` fails with `xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance`
* SwiftProtobuf 1.7.0 (`da75a93ac017534e0028e83c0e4fc4610d2acf48`)
With this protobuf message I don't see anything encoded when I encode an `Header`.
```proto
message Header {
    MessageType        type        = 1;
    MessageCompression compression = 2;
}

enum MessageType {
    CLUSTER_CONFIG    = 0;
    INDEX             = 1;
    INDEX_UPDATE      = 2;
    REQUEST           = 3;
    RESPONSE          = 4;
    DOWNLOAD_PROGRESS = 5;
    PING              = 6;
    CLOSE             = 7;
}

enum MessageCompression {
    NONE = 0;
    LZ4  = 1;
}
```
Here's the code
```swift
let hdr = Header.with {
    $0.compression = .none
    $0.type = .clusterConfig
}
do{
    print("\(try String(decoding: hdr.serializedData().base64EncodedData(), as: UTF8.self))")
    print("\(try hdr.textFormatString())")
} catch {
    print("ERROR")
}
```
Here's the output
```


```

**Comment by thomasvl** [comment]
While you don't say it, it sounds like you used a proto3 syntax file.  For proto3 syntax, the spec says that for singular numeric fields (int, enums, etc.), the zero value is not serialized; size that is also the default, there is no reason to encode it, parsing back will still yield a zero value for the field. So in your example, you are using two zero values, so the binary encoded size would be zero because neither field needs to encode something.

Setting to the zero value effectively clears the field, which is why the TextFormat for the message also doesn't show anything.

If you use a proto2 syntax file, they it has different behaviors around explicitly setting the default value, and maintain the fact that the field was _set_ and serializes it (the fields in that case have _clear_ methods to unset them).

**Comment by eutampieri** [comment]
Ok sorry for having bothered you and thanks for the thorough explanation

**Comment by thomasvl** [comment]
No worries, it can confuse folks new to protocol buffers.

**Comment by tbkka** [comment]
Since this is a common question, I'll add some more detail for others who may see this.

Empty messages are valid for protobuf.  For proto3, it just means that all fields have the default value.  You can see this by trying to decode the result back again.  Let's expand your original program to decode the message again and print out the result:
```
import SwiftProtobuf

func printHeader(title: String, hdr: Header) {
  print("\(title)")
  print("  Compression: \(hdr.compression)")
  print("  Type: \(hdr.type)")
}

let hdr = Header.with {
    $0.compression = .none
    $0.type = .clusterConfig
}

printHeader(title: "Original header:", hdr: hdr)

do{
   let encodedBinary = try hdr.serializedData()
   print("Encoded: \(String(decoding: encodedBinary.base64EncodedData(), as: UTF8.self))")
   let decodedFromBinary = try Header(serializedData: encodedBinary)
   printHeader(title: "Decoded again", hdr: decodedFromBinary)

   let encodedText = hdr.textFormatString()
   print("<<< Encoded text >>>")
   print(encodedText)
   print("<<< End Encoded text>>>")
   let decodedFromText = try Header(textFormatString: encodedText)
   printHeader(title: "Decoded again", hdr: decodedFromText)
} catch {
    print("ERROR")
}
```

When I run the above, I get this output:
```
Original header:
  Compression: none
  Type: clusterConfig
Encoded: 
Decoded again
  Compression: none
  Type: clusterConfig
<<< Encoded text >>>

<<< End Encoded text>>>
Decoded again
  Compression: none
  Type: clusterConfig
```
Even though the encoded data is empty, it still decodes to the exact same values.

If I change the initialization of `hdr.compression` to `lz4`, I get this:
```
Original header:
  Compression: lz4
  Type: clusterConfig
Encoded: EAE=
Decoded again
  Compression: lz4
  Type: clusterConfig
<<< Encoded text >>>
compression: LZ4

<<< End Encoded text>>>
Decoded again
  Compression: lz4
  Type: clusterConfig
```
Note that only the `compression` field was actually written out.  The `type` field was still omitted, since it is still default.
