### ISSUE TITLE
Could you add option to treat Messages with empty fields as Swift enums?

### ISSUE THREAD

**Issue by lolgear** [apple/swift-protobuf#939]
In this case I would like to have enum instead of structure.
```protobuf
// Abc doesn't have fields. We can treat it as namespace ( or enum ) in Swift.
message Abc {
  message MyStructure {
    string myValue = 1;
  }
}
```

```swift
enum Abc { // Namespace
  struct MyStructure {
    // fields and inits
  }
}
```

Moreover, I don't need a lot of generated code as empty decoding.
```swift
  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let _ = try decoder.nextFieldNumber() {
    }
  }
```

**Comment by thomasvl** [comment]
Swift is just generating like all the languages would in this case.  If you'd really like to see this feature in protocol buffers, I'd suggest bring it up in the main protocol buffers repo/list to see about general support for it.

Historically we don't try to avoid options that change the swift generation because it can cause problems when one project wants a proto generated with the option set one way and another wants it set a different way.

**Comment by thomasvl** [comment]
Looks like this got asked upstream, so closing it out in favor of that.
