### ISSUE TITLE
[Curiosity] Why don't you use swift-syntax to generate files?

### ISSUE THREAD

**Issue by lolgear** [apple/swift-protobuf#941]

**Comment by allevato** [comment]
There are a few reasons, but the main one is that this project predates swift-syntax.

Even if we wanted to migrate it (which we would need there to be significant benefits from in order to undertake), swift-syntax's current APIs are a bit too low-level for _generating_ (as opposed to parsing) code. We wouldn't simply be saying "generate a struct with these properties", for example. Instead, we'd have to specify every individual structural node in the syntax tree (a function declaration alone has several, encompassing generic argument lists, regular argument lists, the output, and so forth), as well as every single token that we want to appear in the final source—curly braces, commas, and so forth. In addition, we'd have to specify the way that indentation and internal spacing needs to be attached to those tokens. This would all be a bit painstaking and verbose with the APIs that exist today (although swift-format could help slightly with the whitespace parts).

One day someone will likely create a more friendly API that removes these difficulties and makes generating code closer to just specifying the important parts and letting the library fill in the punctuation and such. (I think someone started to contribute something like this as a separate library target in swift-syntax, but it hasn't been worked on in a while.)

Another quirk is that swift-syntax's APIs are tied very closely to the internal representation of the syntax tree in the compiler, and those nodes/APIs aren't stable; there have been quite a few breaking changes between 5.1 and 5.2, for example. Even for code that looks the same when written as text, its syntax tree might be shaped fairly differently. Unless that changes in the future, doing generation using the syntax trees would require us to keep chasing those changes and updating our generator (unless a simplifying API like the one mentioned above hid those details), even though the _actual_ code we'd be generating wouldn't be changing.
