### ISSUE TITLE
Could you add extension for getter/setter properties that correspond to enum cases of one of field?

### ISSUE THREAD

**Issue by lolgear** [apple/swift-protobuf#942]
Hi!

For example, I have a following protobuf structure:

```protobuf
message MyPage {
    oneof content {
        Content.Text text = 1;
        Content.Image image = 2;
    }
    message Content {
        message Text {}
        message Image {}
    }
}
```

and corresponding generated code:

```swift
struct MyPage {
  var content: OneOf_Content?

  var text: MyPage.OneOf_Content.Text {
    get {
      if case .text(let v)? = _storage._content {return v}
      return MyPage.OneOf_Content.Text()
    }
    set {_uniqueStorage()._content = .text(newValue)}
  }

  var image: MyPage.OneOf_Content.Image {
    get {
      if case .image(let v)? = _storage._content {return v}
      return MyPage.OneOf_Content.Image()
    }
    set {_uniqueStorage()._content = .image(newValue)}
  }

  enum OneOf_Content {
    case text(Text), image(Image)

    struct Text {}
    struct Image {}
  }
}
```

`text` and `image` fields are sugar accessors to cases of content and in getters they could return empty structures.

So, if I would like to create MyPage, I need only `content` field that wraps all cases of `MyPage.Content`.

Again, it could be done via option and it doesn't affect protobuf, because these fields exist, but in extension.

**Desired output**

```swift
struct MyPage {
  var content: OneOf_Content?

  enum OneOf_Content {
    case text(Text), image(Image)

    struct Text {}
    struct Image {}
  }
}

extension MyPage { // derived properties for enum cases -> self.content: OneOf_Content?
  var text: MyPage.OneOf_Content.Text {
    get {
      if case .text(let v)? = _storage._content {return v}
      return MyPage.OneOf_Content.Text()
    }
    set {_uniqueStorage()._content = .text(newValue)}
  }

  var image: MyPage.OneOf_Content.Image {
    get {
      if case .image(let v)? = _storage._content {return v}
      return MyPage.OneOf_Content.Image()
    }
    set {_uniqueStorage()._content = .image(newValue)}
  }
}
```

**Comment by thomasvl** [comment]
So you want an option just to remove generating the helpers?

If you compile the generated sources into the module that uses them, Swift should (eventually if not now) dead strip away those other accessors if you don't call them.

The accessor are generated because it is documented that it is safe (with a footnote or two) to move a field into a oneof as the proto file evolves.  If we only generated the enum with associated values, it would be a source breaking change.

As far as adding an option: options have two main downfalls -
1. More complexity for the generator and thus to try and test in the generator and resulting code.
2. Option don't scale when a proto ends up being used my multiple things.  One piece of code may want the option set one way and the other another way.  Then they can't share the generated code and have to go to interesting hacks to get distinct/no-colliding generations and they code using both can never pass a message from one to the other.

Instead, for Swift we try to rely on the compiler always getting better and drop code that isn't used/needed, but generate a stable interface to help avoid breaking changes for developers as much as possible.

**Comment by allevato** [comment]
> So you want an option just to remove generating the helpers?

If I'm reading it correctly, it doesn't appear that the request is even to remove them, but to simply move them to an extension. I don't see any benefit from doing that, because they're still going to be part of the type. It would just shift the code around in the generated output.

**Comment by thomasvl** [comment]
> If I'm reading it correctly, it doesn't appear that the request is even to remove them, but to simply move them to an extension.

Oops, that's what I get for not having coffee this morning.

**Comment by lolgear** [comment]
@allevato @thomasvl 
The benefit is separation of convenient accessors and "real" stored properties.

**Comment by allevato** [comment]
That benefit seems questionable when weighed against the consequences:

* It would move the computed properties much farther away from the `oneof` property they correspond to. You personally might prefer they be farther apart, but a different reader might prefer that related declarations stay locally grouped, which leads to the second point that @thomasvl already mentioned:

* It would add complexity to the generator for individuals' style preferences but which have no effect on the semantics of the generated code.
