### ISSUE TITLE
Remove init() method from generated struts from message

### ISSUE THREAD

**Issue by Banck** [apple/swift-protobuf#968]
Hello!
As I noticed, you add init() method for all structs, which were generated from messages from proto.
That's why we can't init our models with default swift structs init method with all params.
Example:
```
struct GetLocalizationsRequest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var platform: String = String()

  var appName: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}
```
If you remove init() then we will can init GetLocalizationsRequest like:
`GetLocalizationsRequest(platform: "iOS", appName: "client")
`

**Comment by tbkka** [comment]
I find this tempting, actually, though I'm curious what other folks think.

In the past, people have suggested we _add_ initializers to support this usage.  We've consistently refused this for two reasons:
1. More code.  Some of our users are very sensitive to the size of the generated code, so we try to only add generated code when it provides a major benefit.
2. Protobuf evolution.  Generally, adding new fields or rearranging fields in a proto file is not expected to break any code.  This is especially important for large organizations where there are many proto files being shared between many different software teams.

Obviously, _removing_ code doesn't suffer from the first concern above.  The second is still valid, though.  Any thoughts?  @thomasvl @allevato @Lukasa ??

**Comment by Lukasa** [comment]
I continue to believe that having a memberwise init would be useful for absence of surprise. I understand point (2), and we can push people towards `make` for that reason, but I’d like the option of the default memberwise initialiser.

**Comment by cburrows** [comment]
I think suppressing the compiler's memberwise initializer is the better design. I'm pretty convinced by point (2), and the fact that we have `with` to get initialized message instances out of swift expressions.

In addition to (2), a memberwise initializer would contain parameters for anything we generate into the struct that is not necessarily a protobuf field, such as `unknownFields` in the example. `oneof`'s would be collapsed into their Swift enum field as well.

**Comment by thomasvl** [comment]
This comes up enough it was one of the reasons I added the FAQ to the docs:

https://github.com/apple/swift-protobuf/blob/master/Documentation/FAQ.md#why-arent-there-memberwise-initializers

**Comment by allevato** [comment]
In addition to the points above, it's important to note that removing `init()` would only make the default memberwise initializer available to callers within the same module as the generated code. It may be the case that most users generate their messages with the default visibility of `internal` so this doesn't impact them, but the minute you move your messages to a shared framework or make them part of an SDK, you would now have an initializer that some of your clients can't access.

So fundamentally, even if users _can_ take the code we generate and include it as part of a module that also contains other business logic, because of the fact that they aren't the authors of the generated code, I think we should take measures to ensure that it's "effectively the same as `public`" to them, and that means being very deliberate about the APIs we expose instead of taking advantage of compiler synthesis*.

\* Here I only mean completely implicit synthesis like memberwise `init`. Anything that has to be explicitly declared, like protocol conformances that are synthesized, are fine—there's still a declaration of intent there.

**Comment by tbkka** [comment]
Thanks for the discussion.  I'm going to close this issue since it sounds like the earlier concerns still apply:  In essence, the compiler-synthesized member wise initializers interact with protobuf conventions in surprising ways.  In addition, people can define their own convenience initializers via extensions.
