### ISSUE TITLE
Empty Packed Enum fails validation

### ISSUE THREAD

**Issue by flynnhowling** [apple/swift-protobuf#988]
In `BinaryEncodingSizeVisitor.swift` the method `visitPackedEnumField<E: Enum>(value: [E],  fieldNumber: Int)` does not follow the pattern of all other packed field types in that it adds
```
    guard !value.isEmpty else {
      return
    }
```
Before the general pattern of calculating size: 
```
    let tagSize = FieldTag(fieldNumber: fieldNumber,
                           wireFormat: .varint).encodedSize
    serializedSize += tagSize
    var dataSize = 0
    for v in value {
      dataSize += Varint.encodedSize(of: Int32(truncatingIfNeeded: v.rawValue))
    }
    serializedSize += Varint.encodedSize(of: Int64(dataSize)) + dataSize
```

However, when actually writing the binary it will still write the field number (`BinaryEncodingVisitor.swift`)
```
    encoder.startField(fieldNumber: fieldNumber, wireFormat: .lengthDelimited)
    var packedSize = 0
    for v in value {
      packedSize += Varint.encodedSize(of: Int32(truncatingIfNeeded: v.rawValue))
    }
    encoder.putVarInt(value: packedSize)
    for v in value {
      encoder.putVarInt(value: v.rawValue)
    }
```

This causes the calculated size to be different from the actual size when the message is serialized to data.

**Comment by thomasvl** [comment]
Do you have a fail case?

This may be one of the grey areas in the library impl, because the `traverse` method will already check the array to ensure it isn't empty.  So the `visitors` don't really have to check these sorta things because they won't get called in the first place.

From a pure performance pov, we should delete the checks, but from a general safety pov, we should uniformly check the args.
